>hvPORB
MA------------------------------------------------------LQAA
--TSFLPSALSARKEG-----------AAKDSA-FFGV-RLA--DGLKLDATSLGLRTK-
--RVNTS-SVAIRAQ-AAAVSAPTAT-----PASPAGKKTVRTGNAIITGASSGLGLATA
KALAESGKWHVIMACRDYLKTARAARAAGMPKGSYTIVHLDLASLDSVRQFVKNVRQLDM
PIDVVVCNAAVYQPTAKEPSFTADGFEMSVGVNHLGHFLLARELLEDLKASDY-PSKRLI
IVGSITGNTNTLAGN--VPPKANLGDLRGLAAGLNGVGSAAMIDGAE-FDGAKAYKDSKV
CNMLTMQEFHRRYHEETGVTFASLYPGCIATTGLFREHIPLFRLLFPPFQKYITKGYVSE
EEAGKRLAQVVSEPSLTKSGVYWSWNKNS----ASFENQLSEEASDTEKARKVWELSEKL
VGLA-
>atPORC
MA------------------------------------------------------LQAA
--YSLLPSTISIQKEG---K----FNASLKETT-FTGS-SFS--NHLRAEKISTLLTIKE
QRRQKPRFSTGIRAQ-T-VTATPPAN-----EASPEQKKTERKGTAVITGASSGLGLATA
KALADTGKWHVIMACRNFLKAEKAARSVGMSKEDYTVMHLDLASLESVKQFVENFRRTEQ
PLDVLVCNAAVYQPTAKEPSFTAEGFEISVGTNHLGHFLLSRLLLDDLKKSDY-PSKRMI
IVGSITGNTNTLAGN--VPPKANLGDLRGLASGLNGQNSS-MIDGGE-FDGAKAYKDSKV
CNMLTMQELHRRYHEETGVTFASLYPGCIATTGLFREHIPLFRLLFPPFQKYITKGYVSE
EEAGKRLAQVVSDPSLGKSGVYWSWNNNS----SSFENQLSKEASDAEKAKKLWEVSEKL
VGLA-
>atPORA
MA------------------------------------------------------LQA-
--ASLVSSAFSVRKDG---KLNASASSSFKESS-LFGV-SLS--EQSKADFVSSSLRCKR
EQSLRNN-KAIIRAQ-AIATSTPSVT-----KSSLDRKKTLRKGNVVVTGASSGLGLATA
KALAETGKWHVIMACRDFLKAERAAQSAGMPKDSYTVMHLDLASLDSVRQFVDNFRRAEM
PLDVLVCNAAVYQPTANQPTFTAEGFELSVGINHLGHFLLSRLLIDDLKNSDY-PSKRLI
IVGSITGNTNTLAGN--VPPKANLGDLRGLAGGLNGLNSSAMIDGGD-FVGAKAYKDSKV
CNMLTMQEFHRRFHEDTGITFASLYPGCIATTGLFREHIPLFRTLFPPFQKYITKGYVSE
SEAGKRLAQVVADPSLTKSGVYWSWNKTS----ASFENQLSQEASDVEKARRVWEVSEKL
VGLA-
>csPORA
MA------------------------------------------------------LQA-
--ASLVSPALSIPKEG---K----SSVCLKDSS-LFGI-SFS--DHLKSEFSSSTLRCK-
-RELNQQ-IGAIRAQ-TTATESPAVN-----KATPDGKKTLRKGSVVITGASSGLGLATA
KALAETGKWHVIMACRDFLKAERAAKSAGITKENYTVMHLDLASLDSVRQFVDNFRQSGR
PLDVLVCNAAVYLPTAKEPTFTAEGFELSVGTNHLGHFLLSRLLLEDLNKSSY-PSKRLI
IVGSITGNTNTLAGN--VPPKANLGDLRGLAGGLNGLKSS-MIDGGE-FDGAKAYKDSKV
CNMLTMQEFHKRYHEETGITFASLYPGCIATTGLFREHIPLFRILFPPFQKFITQGYVSE
DEAGKRLAQVVSEPSLTKSGVYWSWNKNS----ASFENQLSQEASDAEKARKVWELSEKL
VGLA-
>hvPORA
MA------------------------------------------------------LQ--
----LLPSTLSVPKKG---S--SMGAVAVKDTAAFLGV-------SSKAKKASLAVRTQ-
----------VATAP-SPVTTSPGST-----ASSPSGKKTLRQGVVVITGASSGLGLAAA
KALAETGKWHVVMACRDFLKASKAAKAAGMADGSYTVMHLDLASLDSVRQFVDAFRRAEM
PLDVLVCNAAIYRPTARTPTFTADGHEMSVGVNHLGHFLLARLLMEDLQKSDY-PSRRMV
IVGSITGNSNTLAGN--VPPKASLGDLRGLAGGLSGASGSAMIDGDESFDGAKAYKDSKV
CNMLTMQEFHRRYHEETGITFSSLYPGCIATTGLFREHIPLFRTLFPPFQKFVTKGFVSE
AESGKRLAQVVAEPVLTKSGVYWSWNKDS----ASFENQLSQEASDPEKARKVWELSEKL
VGLA-
>taPORA
MA------------------------------------------------------LQ--
----LLPSTLSVPKKG---S--SMGAAAVKDTAAFLGV-------SSKAKKASLAVRTQ-
----------VATAP-SSVTTSPGSA-----TAKPSGKKTLRQGVVVITGASSGLGLAAA
KALAETGKWHVVMACRDFLKASKAAKAAGMADGSYTVMHLDLASLDSVRQFVDAFRRAEM
PLDVLVCNAAIYRPTARTPTFTADGHEMSVGVNHLGHFLLARLLMEDLQKSDY-PSRRMV
IVGSITGNSNTLAGN--VPPKASLGDLRGLAGGLSGASGSAMIDGDESFDGAKAYKDSKV
CNMLTMQEFHRRYHEETGITFSSLYPGCIATTGLFREHIPLFRTLFPPFQKFVTKGFVSE
AESGKRLAQVVAEPSLTKSGVYWSWNKDS----ASFENQLSQEASDPEKARKVWELSEKL
VGLA-
>atPORB
MA------------------------------------------------------LQA-
--ASLVSSAFSVRKDA---KLNA-SSSSFKDSS-LFGA-SIT--DQIKSEHGSSSLRFK-
-REQSLR-NLAIRAQ-TAATSSPTVT------KSVDGKKTLRKGNVVVTGASSGLGLATA
KALAETGKWNVIMACRDFLKAERAAKSVGMPKDSYTVMHLDLASLDSVRQFVDNFRRTET
PLDVLVCNAAVYFPTAKEPTYSAEGFELSVATNHLGHFLLARLLLDDLKKSDY-PSKRLI
IVGSITGNTNTLAGN--VPPKANLGDLRGLAGGLNGLNSSAMIDGGD-FDGAKAYKDSKV
CNMLTMQEFHRRFHEETGVTFASLYPGCIASTGLFREHIPLFRALFPPFQKYITKGYVSE
TESGKRLAQVVSDPSLTKSGVYWSWNNAS----ASFENQLSEEASDVEKARKVWEISEKL
VGLA-
>asPOR
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------VVVITGASSGLGLAAA
KALAETGKWHVVMACRDFLKASKAAKAAGMADGSYTVMHLDLASLDSVRQFVDAFRRAEM
PLDVLVCNAAIYRPTARKPTFTAEGVEMSVGVNHLGHFLLARLLLEDLQKSDY-PSRRLV
IVGSITGNDNTLAGN--VPPKANLGDLRGLAGGLTGASGSAMIDGDESFDGAKAYKDSKV
CNMLTMQEFHRRYHEDTGITFSSLYPGCIATTGLFREHIPLFRTLFPPFQKFVTKGFVSE
AESGKRLAQVVGEPSLTKSGVYWSWNKDS----ASFENQLSQEASDPEKARKVWELSEKL
VGLA-
>crPOR
------------------------------------------------------------
--MALTMSAKSVSARA---Q----VSSKAQAAP-AVAVSGRT--SSRVMPAPALAARSS-
-VARTPL---VVCAA-TATAPSPSLADKFKPNAIARVPATQQKQTAIITGASSGLGLNAA
KALAATGEWHVVMACRDFLKAEQAAKKVGMPAGSYSILHLDLSSLESVRQFVQNFKASGR
RLDALVCNAAVYLPTAKEPRFTADGFELSVGTNHLGHFLLTNLLLDDLKNAPN-KQPRCI
IVGSITGNTNTLAGN--VPPKANLGDLSGLAAGVPAAN--PMMDGQE-FNGAKAYKDSKV
ACMMTVRQMHQRFHDATGITFASLYPGCIAETGLFREHVPLFKTLFPPFQKYITKGYVSE
EEAGRRLAAVISDPKLNKSGAYWSWSSTT----GSFDNQVSEEVADDSKASKLWDISAKL
VGLSA
>dcPOR
MA------------------------------------------------------LQA-
--ASFLPSSFSINKEG---K----ANVSLKETS-LFGV-TFS--DSLRTDFSS--LRTRR
GCRQISQ-TGAIRSQ-A-VATTPSVN-----RATGEGKKTLRKGSVIITGASSGLGLATA
KALAETGKWHVIMACRDFLKAERAAKSAGMPKENYTIMHLDLASLDSVRQFVETFRRSER
PLDVLVCNAAVYFPTAKEPTYTADGFELSVGTNHLGHFLLSRLLLDDLNKSDY-PSKRLI
IVGSITGNTNTLAGN--VPPKANLGDLRGLAGGLNGMNSSAMIDGAE-FDGAKAYKDSKV
CNMLTMQEFHRRYHEETGITFASLYPGCIATTGLFREHIPLFRTLFPPFQKYITKGYVSE
AESGKRLAQVVSEPSLTKSGVYWSWNKDS----ASFENQLSEEASDVEKARKVWEVSEKL
VGLA-
>mpPOR
MPKRSNGSLVVRCAVSVVRFSKENVSCDLASENFTFSRDSFPVVSTVLRVSEAVYRMAA-
--VASLGSALSVSSAALSQNVSV-SNNATKESA-FLGL-RMG--EVAK--FGGALLSVST
VAANLKS-KPGVLSV-N-AVTAPAET-----MNKPSSKKTATKSTCIITGASSGLGLATA
KALADTGEWHVIMACRDFLKAERAARSVGIPKDSYTVIHCDLASFDSVRAFVDNFRRTER
QLDVLVCNAAVYFPTDKEPKFSAEGFELSVGTNHMGHFLLARLLMEDLQKAKD-SLKRMI
IVGSITGNSNTVAGN--VPPKANLGHLRGLAGGLNGVNSSSMIDGGE-FDGAKAYKDSKV
CNMFTMQEFHRRYHAETGITFSSLYPGCIAETGLFRNHVTLFRTLFPPFQKYITKGYVSE
EEAGKRMAQVVSDPKLSKSGVYWSWNKDS----GSFENELSEEASNPEKAKRLWELSERL
SGLV-
>psPOR
MA------------------------------------------------------LQT-
--ASMLPASFSIPKEG---K----IGASLKDST-LFGVSSLS--DSLKGDFTSSALRCK-
--ELRQK-VGAVRAE-TAAPATPAVN-----KSSSEGKKTLRKGNVVITGASSGLGLATA
KALAESGKWHVIMACRDYLKAARAAKSAGLAKENYTIMHLDLASLDSVRQFVDNFRRSEM
PLDVLINNAAVYFPTAKEPSFTADGFEISVGTNHLGHFLLSRLLLEDLKKSDY-PSKRLI
IVGSITGNTNTLAGN--VPPKANLGDLRGLAGGLTGLNSSAMIDGGD-FDGAKAYKDSKV
CNMLTMQEFHRRYHEETGITFASLYPGCIATTGLFREHIPLFRTLFPPFQKYITKGYVSE
EESGKRLAQVVSDPSLTKSGVYWSWNNAS----ASFENQLSQEASDAEKARKVWEVSEKL
VGLA-
>pbPOR
MA----------------------------------------------------------
------------------------------------------------------------
---------------------------------------QDQKPTVVITGASSGVGLYAA
KALVKRG-WHVVMACRNLEKADSAAKSLGMSPDSYTLMHIDLGSLDSVRKFVTQFRESGK
SLDALVCNAAVHMPLLKEPMRSPEGYELSVATNHFGHFLLCNLLLEDLKHSTH-NDPRLI
ILGTVTANSKELGGKIPIPAPADLGDLSGLEAGFKA--PIAMIDGKP-FKAGKAYKDSKL
CNMITSRELHRRYHDSTGIVFNTLYPGCVADTPLFRNSLPVFQKVFPWFQKNITGGYVSQ
ELAGERTAQVVADPEFKQSGVHWSWGNRQKEGRESFVQELSEKVTDDAKAKRMWELSEKL
VGLA-
>sPOR
ME----------------------------------------------------------
------------------------------------------------------------
---------------------------------------QPMKPTVIITGASSGVGLYGA
KALIDKG-WHVIMACRNLDKTQKVADELGFPKDSYTIIKLDLGYLDSVRRFVAQFRELGR
PLKALVCNAAVYFPLLDEPLWSADDYELSVATNHLGHFLLCNLLLEDLKACPD-ADKRLI
ILGTVTANSKELGGKIPIPAPPDLGNFEGFEAGFKK--PIAMINNKK-FKSGKAYKDSKL
CNMLTTRELHRRFHQETGIVFNSLYPGCVADTPLFRNHYSLFRTIFPWFQKNVTKGYVSQ
ELAGERVAMVVADDKFKDSGVHWSWGNRQQAGREAFVQELSEQGSDAQKAQRMWDLSEKL
VGLV-

>gi|224285707|gb|ACN40569.1| unknown [Picea sitchensis]
MAASSIMGTLHQTHIGSAAFALQKEGGHSASANSAFLGVSVAEHGKREFGFPVLRAKKVTSRNTNIARLR
AQTVAAPVETKEAPASKKTDRKGNVIITGASSGLGLATAKALGESGEWHIIMACRDFVKAERMARTVGIP
KENYTVMHLDLASLESVRQFADNFKHSGRPLDVLVCNAAVYLPTAKVPTFTAEGFELSVGTNHLGHFLLS
RLLLEDLKKSDFKSKRVIIVGSITGNTNTLAGNIPPKANLGDLRGLSGRLNGVNSSPMIDGGEFDGAKAY
KDSKVCNMLTMQEFHRQYHEETGITFASLYPGCIATTGLFREHIPPFRLLFPPFQKYITKGFVSEEEAGK
RLAQVVSDTSLTKSGVYWSWNNDSASFENQLSEEASDPEKARKVWAISEKLVGLA

>gi|157338196|emb|CAO39240.1| unnamed protein product [Vitis vinifera]
MAMQAAALVPSAFSIPKEGKGSASFKESGLFGVSLSDHVKADFSSSALRNKRKPSVGAIRAQTAATTPAI
TRATPEGKKTLRKGTVVITGASSGLGLATTKALAETGKWHIIMACRDFLKAERAARSAGLSKENYTVMHL
DLASLDSVRQFVDNFKRSERPLDVLVCNAAVYLPTAKEPTFTADGFELSVGTNHLGHFLLARLLLDDLKQ
SDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGMAGGLNGLNSSAMIDGGAFDGAKAYKDSKVCNML
TMQEFHRRYHEDTGITFASLYPGCIATTGLFREHIPLFRLLFPPFQKFITKGYVSEEESGKRLAQVVSEP
SLTKSGVYWSWNKNSASFENQLSQEASDADKARKVWELSEKLVRLA

>gi|225446944|ref|XP_002264042.1| PREDICTED: hypothetical protein isoform 2 [Vitis vinifera]
MALQAASLLPSAVSIHKEGKSNASLKETGFFEVSVSDHLKAELSLGLSKNKELKRRKLPVGVIRAQTATT
PAISQASPEGKKTLRKGNVIITGASSGLGLATAKALAETEKWHIIMACRNFLKADRAAKSAGIAKENYTV
MHLDLASLESVRQFADNFRRSGRPLDVLVCNAAVYLPTAKEPTFTAEGFELSVGTNHLGHFLLSRLLLDD
LKQTDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLAGGLNGINGSPMIDGGEFDGAKAYKDSKVC
NMLTMQEFHRRYHEETGITFASLYPGCIATTGLFREHIPLFRLLFPPFQKYITKGYVSEEEAGKRLAQVV
TDPSLTKSGVYWSWNKNSASFQNQLSQEASDAEKARKVWEISEKLVGLA

>gi|148909246|gb|ABR17723.1| unknown [Picea sitchensis]
MGTLLQTHIGSVALALQKEGGHSASTKDSAFLGVSLVEHGKKEFSFPVIRAKKVTSRNTSVPRIRAQTVA
APVETKEAPASKKTDRKGNVIITGASSGLGLATAKALGESGEWHIIMACRDFLKAERMARAVGIPKENYT
VMHLDLASLESVRQFADTFRRSGRPLDVLVCNAAVYFPTAKVPTFTAEGFEMSVGTNHLGHFLLSRLLLE
DLKKSDFDSKRVIIVGSITGNTNTLAGNIPPKANLGDLRGFAGGLNGVNISPMIDGGEFDGAKAYKDSKV
CNMLTMQEFHRRYHEETGITFASLYPGCIATTGLFREHIPLFKLLFPPFQKYITKGFVSEDEAGKRLAQV
VSNPSLAKSGVYWSWNNNSASFENQLSEEASDPEKAKKVWEISEKLVELA

>gi|255553815|ref|XP_002517948.1| short-chain dehydrogenase, putative [Ricinus communis]
MALKAPSTLPSSISICKEGKSNVSLKEAGFFGVSVSLPNHLKAECNYSLVRSKELKKRATPTGTIRAQTA
TTTPAIDEAAPVAKKTLRKGNVIVTGASSGLGLATAKALAETGEWNVIMACRNFLKAERAAKSVGIPKEN
YTVMHLDLASLDSVRQFAGNFRQSGMPLDVLVCNAAVYFPIAKEPTFTAEGFELSVGTNHLGHFLLARLL
LDDLKQSDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLVGGLNGLNSSPMIDGGEFDGAKAYKDS
KVCNMLTMQEFHRRYHEETGVAFASLYPGCIAETGLFREHIPLFRLLFPPFQKYITKGYVSEEVAGKRLA
QVVSDPSLGKSGVYWSWNQYSSSFENQLSEEASDTEKAKKLWEISEKLVGLA

>gi|211909305|gb|ACJ12925.1| protochlorophyllide oxidoreductase B [Chorispora bungeana]
MTLQAASLVSSAFSVRKDGKLNASSSSFKDSSLFGVSITDLIKSEHGSSSIRFKREHNLRNVAIRAQTAA
TSSPSVTKSSGEGKKTLRKGNVVVTGASSGLGLATAKALAETGKWHVIMACRDFLKAERAAKSAGMPKGS
YTVMHLDLASLDSVRQFVDNFRRSEMPLDVLVCNAAVYFPTAKEPTYSAEGFELSVGTNHLGHFLLSRLL
LDDLKKSDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLAGGLNGLNSSAMIDGGDFDGAKAYKAS
KVCNMLTMQEFHRRCHEETGVTFASLYPGCIASTGLFREPIPLFRFLFPPFQKYITKGYVSETESGKRLA
QVVSDPSLTKSGVYWSWNKASASFENQLSQEASDVEKARKVWEISEKLVGLA

>gi|224117218|ref|XP_002317511.1| predicted protein [Populus trichocarpa]
MALQAASLVSSAFVFPKEGKSNAYFKDSSLFGVSLSEHVKADFSSCALKCKREFNQGVGAVRAQTMVAAT
PALDRASSESKKTLGQGTCIVTGASSGLGLATAKALAETGKWHIIMACRNFLKAERAAKSAGIAKENYTI
MHLDLASLDSVRQFVDTFRRSGRPLDVLVCNAAVYLPTAKEPAFTAEGFELSVGTNHLGHFLLSRLLLED
MKISDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLSGGLNGLNRSAMIDGGVFDGAKAYKDSKVC
NMLTMQEFHRRLHEETGIAFASLYPGCIATTGLFREHIPLFRLLFPPFQKYITKGFVSEHEAGKRLAQVV
SDPSLTKSGAYWSWNKHSASFQNQLSQEASDAEKARKVWEISEKLVGLA

>gi|21068893|dbj|BAB93003.1| NADPH:protochlorophyllide oxidoreductase [Nicotiana tabacum]
MALQAAALVPSAFSISKEGKASANLKNSSLFGVSLSDYSKSDFGSSSFKVKSQRRLSNGAVRATMVASPD
VTTNSPAGKKTLRKGCVIVTGASSGLGLATAKALSETGKWHVIMACRDFLKAEKAAKSVGMPKENYTIMH
LDLASLDSVRQFVDNFRRSGRPLDVLVANAAVYQPTAKEPSFTAEGFEISVGTNHLGHFLLSRLLLDDLK
QSDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGMAGGLNGINSSAMIDGGEFDGAKAYKDSKVCNM
LTMQEFHRRYHEETGITFASLYPGCIATTGLFREHIPLFRLLFPPFQKYITKGFVSETEAGKRLAQVVSD
PSLTKSGVYWSWNKDSASFENQLSEEASDVEKARKVWEVSEKLVGLA

>gi|226500452|ref|NP_001149903.1| protochlorophyllide reductase B [Zea mays]
MALQAATSFLPSALSARKEGSSVKDSAFLGVHLADDGLKLETAALGLRTKRVITSVAIRAQAAAVSSPSV
TPASPSGKKTLRKGTAIITGASSGLGLATAKALAETGKWHVIMACRDFLKASRAAKAAGMDKDSFTVVHL
DLASLDSVRQFVKNVRQLEMPVDVVVCNAAVYQPTAKEPSYTADGFEMSVGVNHLGHFLLARELLSDLQS
SDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLAGGLNGIGGSAMIDGGEFDGAKAYKDSKVCNML
TMQEFHRRYHEETGVTFASLYPGCIATTGLFREHIPLFRLLFPPFQKYITKGYVSEEEAGKRLSQVVSDP
SLTKSGVYWSWNKNSASFENQLSEEASDADKAKKLWEISEKLVGLA

>gi|255587362|ref|XP_002534245.1| short-chain dehydrogenase, putative [Ricinus communis]
MASSLVSSTFVVLKEGKSSASFKDSSLFGVSLSDHLKADHSSSAFRFKREPNQRVGAVRAQTMATASPAV
NRAAPEGKKTLRKGSVIVTGASSGLGLATAKALAETGKWHIIMACRDFLKTERAAKSAGISKENYTIMHL
DLASLDSVRQFVDNFKRSGRPLDVLVCNAAVYLPTAKEPTFTAEGFELSVGTNHLGHFLLSRLLLEDLQK
SDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDMRGLAGGLNGLNSSAMIDGGNFDGAKAYKDSKVCNML
IMQEFHRRFHEETGITFASLYPGCIATTGLFREHIPLFRTLFPPFQKYITKGYVSEDEAGKRLAQVVSDP
SLTKSGVYWSWNKDSASFENQLSQEASDADKARKVWEISEKLVGLA

>gi|21068895|dbj|BAB93004.1| NADPH:protochlorophyllide oxidoreductase [Nicotiana tabacum]
MALQAASLLPSAFSIHKEGKSCATLKDSSLFGVALSYNQKSKFIPPAAWNKELTKKIAAVPIRAQIAATT
PAVNQSTSEQKKTLRKGNVIITGASSGLGLATAKAIGETGEWHVIMACRDFLKAEKAAKSVGIPKENYTV
MHLDLASLESVRQFVDTFRRSGRPLDALVCNAAVYLPTAKEPTFTADGFELSVGTNHLGHFLLSRLLLDD
LKQSDYPQKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLSGGLNSLNCSPMIDGGEFDGAKAYKDSKVC
NMLTMQEFHRRFHEETGIAFASLYPGCIAETGLFRNHIPLFRALFPPFQKYITKGYVSEAEAGKRLAQVV
RDPSLSKSGVYWSWNNTSSSFENQLSKEASDAEKARKLWEVSEKLVGLA

>gi|34915978|dbj|BAC87879.1| Protochlorophyllide reductase chloroplast precursor [Physcomitrella patens subsp. patens]
MSTCAVAALSSPPTSFTSERVTSGITASVQPSAFLGTKISVCKGASVLSRAVSASISRQPLVAPIRAQGV
AAPADTKAPTTTKKTDTKSTVIITGASSGLGLATAKVLADSGEWHVIMACRDFLKAERAARAVGMPKDSY
TVIHCDLSSLNSVKQFVDNVRQSGRPLDVLVCNAAVYLPTAKEPRYTADGFELSVGTNHLGHFLLANMLM
EDIQHKENDTNRRVIIVGSITGNTNTIAGNVPPKANLGDLRGLAGGLDGVRSSVMIVGGEFDGAKAYKDS
KVCNMLTMQEMHRRFHEKTGVTFASLYPGCIATTGLFREHYQLFRTLFPPFQKYITKGYVSEEEAGKRLA
QVVSDPTLNKSGVYWSWNNQSNSFENELSQEASDAEKAKKLWEISEKLVNLS

>gi|90398977|emb|CAJ86249.1| H0801D08.7 [Oryza sativa (indica cultivar-group)]
MALQVQAALLPSALSVPKKGNLSAVVKEPGFLSVSQKAKKPSLVVRAVATPAAPVASPGAGTSKADGKKT
LRQGVVVITGASSGLGLAAAKALAETGKWHVVMACRDFLKAATAAKAAGMAAGSYTVMHLDLASLDSVRQ
FVDNFRRSGMPLDALVCNAAIYRPTARQPTFTADGYEMSVGVNHLGHFLLARLMLDDLKKSDYPSRRLII
LGSITGNTNTLAGNVPPKAGLGDLRGLAGGLRGQNGSAMIDGAESFDGAKAYKDSKICNMLTMQEFHRRF
HEETGITFASLYPGCIATTGLFREHIPLFRLLFPPFQRFVTKGFVSEAESGKRLAQVVGDPSLTKSGVYW
SWNKDSASFENQLSQEASDPEKARKLWDLSEKLVGLA

>gi|13699822|gb|AAD20020.2| NADPH-protochlorophyllide oxidoreductase [Vigna radiata]
MAVQAASLVSGYFSVAKEGKPGMSLRNTTMFGLSLEDALKADFSSLSFSCKREFQKKVCPLRVQSVATTP
GVTKASPEGKKTLRKGSVIITGASSGLGLATAKALAETGKWHVIMACRDFLKAERAAKSSGISKENYTVM
HLDLASLDSVRQFVDNFRQSGRPLDVLVCNAAVYLPTASEPTHTADGFELSVGTNHLGHFLLSRLLLEDL
NKSDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLAGGLNGLNTSAMIDGGSFDGAKAYKDSKVCN
MLTMQEFHRRYHEETGITFASLYPGCIATTGLFREHIPLFRLLFPPFQKFITKGFVSEDESGKRLAQVVE
ITNKRLWRWLYTKKVGMSV

>gi|224126713|ref|XP_002319908.1| predicted protein [Populus trichocarpa]
MALQAASILPSTVSIYKEGKSNASLKETGFFGVSVPNNHLKAEFDCSLIKSKEFRKRELPVRTIRAQTAT
TTPAITEAAPEAKKTLRKCVVVITGTSSGLGLATAKALSETGQCHVIMACRNFLKAERAAKTAGIPKENY
TVMHLDLASLESVRQFVDTFRRSGMPLDVLVCNAAVYLPTAKEPTYTAEGFELSVGTNHLGHFLLARLLL
DDLKKSDYPTKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLVGGLNDLNSSPMIDGGEFDGAKAYKDSK
VCNMLTMQELHRRYHEETGITFASLYPGCIAETGLFRNHIPLFRTLFPPFQKYITKGYVSEEEAGKRLAQ
VVSDPSLTKSGVYWSWNKNSSSFENQLSKEASNAEKALKLWEISEKLVGLA

>gi|7330644|gb|AAC60560.2| NADPH-protochlorophyllide-oxidoreductase; POR [Pinus mugo]
MGTLLQTHIGSVAFALQKEGGHSASAKDSAFLGVSLVEHGKKEFSFPVIRAKKVTSRNTNVPRIRAQTVA
APVETKDAPASKKTDRKGNVIITGASSGLGLATAKALGESGKWHIIMACRDFLKAERMARSVGIPKENYS
VMHLDLASLESVRQFADNFRRSGRPLDVLVCNAAIYLPTAKLPTYTAEGFELSVGTNHLGHFLLSRLLLE
DLKTSDFNSKRVIIVGSITGNTNTLAGNVPPKANLGDLRGLAGGLNGVNISPMIDGGEFDGAKAYKDSKV
CNMLTMQEFHRRYHEETGITFASLYPGCIATTGLFREHIPLFRLLFPPFQKYITKGFVSEEEAGKRLAQV
VSNPSLTKSGVYWSWNNNSGSFENQLSEEASDPEKAKKLWEISEKLVGLA

>gi|58003345|gb|AAW62234.1| NADPH-protochlorophyllide oxidoreductase [Musa acuminata]
MALQASFLPSALSARKEGKVACTVKESAFLGSSILEHHKSHPVLRTKRESNHSVGVVKAQTTAVAAPGLN
QSAVHGKKVLRKGVVVITGASSGLGLAAAKALAETEKWHVVMACRDFLKAEKAAQSAGMAKENYSIMHLD
LASLDSVRQFVHAFRQSGRPLDVLVCNAAIYRPTARTPTYTADGYEMSVGVNHLGHFLLANMLLEDLKKS
DYPSRRLIILGSITGNTNTLAGNVPPKAGLGDLRGLAGGLDGRNSSAMIDGGAFDGAKAYKDSKICNMLT
MQELHRRFHEDTGITFASLYPGCIATTGLFREHIPLFRLLFPPFQKFITKGFVSEDESGQRLAQVVGDPS
LLKSGVYWSWNNNSASFENQLSEEASDAVKAQKLWEISEKLVGLA

>gi|212721052|ref|NP_001132676.1| hypothetical protein LOC100194154 [Zea mays]
MALQAALLPSTLSSVPKKCSLAVAAKDTAFLSVSQKKVQAASLSVRTRVATTAPVATPGSSTAAKDGKKT
VRQGVVVITGASSGLGLAAAKALAETGKWHVVMACRDFLKAAKAAKGAGMADGSYTIMHLDLASLDSVRQ
FVDSFRRAGMPLDSLVCNAAIYRPTARTPTFTADGYEMSVGVNHLGHFLLARLLLDDMQKSDYPSRRLII
LGSITGNTNTLAGNIPPKAGLGDLRGLAAGLRGQNGSAMIDGSESFDGAKAYKDSKICNMLTMQELHRRY
HEETGITFASLYPGCIATTGLFREHIPLFRLLFPPFQKFVTKGFVSEAESGKRLAQVVSDPSLTKSGVYW
SWNKDSASFENQLSQEASDPEKAKKLWEISEKLVGLA

>gi|159046683|ref|YP_001542351.1| protochlorophyllide oxidoreductase [Dinoroseobacter shibae DFL 12]
MTLDPMPRAIVTGASSGVGLHATKSLIDRGWHVTMACRDLAKAEAAARSLDLDPGRYALAHLDLGSLASV
RAFHANIARDHDSLDALVCNAAVYKPRLTQPGRSPDGFEISVATNYFGHFLLANLMLPLLEGAPSPRLIT
LGTVTANSEEFGGKVPIPAPADLGDFAGLKAGFRAPVAMIDGKPFKAGKAYKDSKLCTMMMSRELHTRHH
ARTGIVFATLYPGCVADTPLFRDTPKAFQTIFPWFQKNVTKGYVSQALSGERVAMVVADPEFAQSGVHWS
WGNRQREGRSAFAQGLSTKATDAARSAELWELTAALTGLTTPAEPVAA

>gi|16331782|ref|NP_442510.1| protochlorophyllide oxidoreductase [Synechocystis sp. PCC 6803]
MEQPMKPTVIITGASSGVGLYGAKALIDKGWHVIMACRNLDKTQKVADELGFPKDSYTIIKLDLGYLDSV
RRFVAQFRELGRPLKALVCNAAVYFPLLDEPLWSADDYELSVATNHLGHFLLCNLLLEDLKACPDADKRL
IILGTVTANSKELGGKIPIPAPPDLGNFEGFEAGFKKPIAMINNKKFKSGKAYKDSKLCNMLTTRELHRR
FHQETGIVFNSLYPGCVADTPLFRNHYSLFRTIFPWFQKNVTKGYVSQELAGERVAMVVADDKFKDSGVH
WSWGNRQQAGREAFVQELSEQGSDAQKAQRMWDLSEKLVGLV

>gi|166364106|ref|YP_001656379.1| protochlorophyllide oxidoreductase [Microcystis aeruginosa NIES-843]
MIQDKKPTVIITGTTSGVGLYAAKSLAQRGWFVVMACRDIPKMEQAAKELNIPRDNYCIEFIDLGSLDSV
RRFVKNFRALGRSLTALVCNAAIYLPLLKEPLRSPDGYELSMATNHLGHFLLSNLLLEDLKNSPSPDRRL
VILGTVTHNPDELGGKIPPRPDLGDLEGFAKGFKEPITMADGKKFESVKAYKDSKVCNVLTMRELHKRYH
QSTGITFTSLYPGCVADTPLFRNHYPFFQQFFPWFQKNITGGYVSQELAGERVAMVVADPEYRQSGAYWS
WGNRQKKEGKSFVQRVSPQARDDERGAKMWEYSAKLVGLA

>gi|158334370|ref|YP_001515542.1| protochlorophyllide oxidoreductase [Acaryochloris marina MBIC11017]
MEQHQKQTVVVTGASSGVGLYAAKALALTGKWHVIMACRNFLKAETAAQSVGIPRDSYTVIHLDLACFES
IHRFVKDFREMGRSLDALVCNAAIYMPLLKKPLHTAEGYELNVGTNHLGHFLLCNLMLEDLMRSGYDQRR
LIILGTVTANPKELGGKIPIPAPPDLGDMRGLEAGFKAPVSMINGKKFKPGKAYKDSKLCNMLTMRELHR
RFHESTGITFSALYPGCVATTGLFRNHFALFRFLFPKFQRFITGGFVTEELAGTRVAQVVSDPLFGKSGV
YWSWGNRQKEGRPSFEQEMSNESLDDTKAQRLWELSEGLVGLSSQDTSMPQMSTSR

>Oryza_sativa_PORB_ORYSJ_gi|75248671|sp|Q8W3D9.1|PORB_ORYSJ RecName: Full=Protochlorophyllide reductase B, chloroplastic; Short=PCR B; AltName: Full=NADPH-protochlorophyllide oxidoreductase B; Short=POR B; Flags: Precursor
MALQAATTTSFLPSALSARKEGAVKDSAFLGVRLGDGLKLETSALGLRTKRVSTSSVAIRAQASAAVSSP
TVTPASPSGKQTLRKGTAVITGASSGLGLATAKALAETGRWHVVMGCRDFLKASRAAKAAGMEKGSYTIV
HLDLASLDSVRQFVANVRRLEMPVDVVVCNAAVYQPTAKQPSFTADGFEMSVGVNHLGHFLLARELLADL
TSSDYPSKRLIIVGSITGNTNTLAGNVPPKANLGDLRGLASGLDGVSSSAMIDGGEFDGAKAYKDSKVCN
MLTMQEFHRRYHGETGVTFASLYPGCIATTGLFREHVPLFRLLFPPFQKYITKGYVSEEEAGKRLAQVVS
DPSLTKSGVYWSWNNNSASFENQLSEEASDPEKAKKVWELSEKLVGLADHDQ

>gi|226460431|gb|EEH57725.1| light-dependent protochlorophyllide oxido-reductase chloroplast precursor [Micromonas pusilla CCMP1545]
MSAQMFASSTVARAAPVSKFGKKADGVSARKAIARAPMTNRRVQTSPKAAFTVYAAVTKLKTAIVTGASS
GLGLYTTKSLIEKGDYHVVMACRSVEKAEREAKRLGFDKSKYTVMELELGSLENVRSFVKKFRGNGKLCK
NLQTLICNAAIYYPNAVEPTFTQDGFEETVGVTHLGHFLLSNLLLRDLVAADDLGIDKRLCIVGSVTANT
NTLAGQVPPRAAIGDMSGLANGLNGDRNKGAMIDGDRFIGPKAYKDAKLCNILTIKEMNRRWHEETGITF
STMYPGCIADTPLFRNHTPIFRFLFPLIQKYITKGYVTMEEAGNRLASVNSEPQYTKSGAYWAWKGGGDQ
LMDNYWDNSNRTEAFDNTPSKEAGDMQKAAKCFDLSVEVVGLKENEVGPKAGSYNFLNLLGGNKKNSKTP
VAA

>gi|116058730|emb|CAL54437.1| POR_DAUCA Protochlorophyllide reductase, chloroplast precursor (ISS) [Ostreococcus tauri]
MRAVAAHYRAPTRTRRAPAIRQPSTSRARRTSTLAVARAAGSSSQNIMPSNGANKPVAIITGASSGLGLY
TAKALIEKGYFVVMAVRDPRKGETKANELGFDKKSYAVMYCELGELASVREFCSGFRRSPYVKNFQALVC
NAALYLPNATVPSYTKDGFEECVGVNHLAHHLMCLELLDDLAKAPDANMKRLIIVGSVTGNTNTLAGQVP
PRAGLGDLSGLRNGFKNSDRNQGAHIDGSRFIGAKAYKDSKLCNMLDIKVFAERYGESTGIKFSTMYPGC
IADSNLFRNHTPFFRWLFPILQKNVTKGYVSEEEAGQRLASIVYDPRYTEQGAYWAWKGGGDQLWDNFNN
NNEDTRTIAFNNKPSREGRDMAKANAMFDISTELVGYKPNVIDGVSKAFDRVISSATEKISK

