>LISAS-O66148|POR_PLEBO
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------maqdqkptvvitgassgvglyaakalvk--rg-whvvmacrnlekad
saakslgms--------------pd-------------sytlmhidlgsldsvrkfvtqfr--es
gks------ld--alvcnaavhm-----p----llkepmrspegyelsvatnhf---ghfllcnl
lledlk-hsthn-----------dprliilgtvta--------------nskelggkipipapad
lgdl--sgle-----agfk----apiamidgkp-fkagkaykdsklcnmitsrelhrryhd----
-------st-givfntlypgcva---dtpl-frns----------lpvfqkvfpwfqkni---tg
gyvsqelagertaqvvadpefkqsgvhwsw-----------gn---rqkegre------------
----------sfvqel--s-ekvtdda---kakrmwelseklvgla-
>LISAS-Q59987|POR_SYNY3
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------meqpmkptviitgassgvglygakalid--kg-whvimacrnldktq
kvadelgfp--------------kd-------------sytiikldlgyldsvrrfvaqfr--el
grp------lk--alvcnaavyf-----p----lldeplwsaddyelsvatnhl---ghfllcnl
lledlk-acpda-----------dkrliilgtvta--------------nskelggkipipappd
lgnf--egfe-----agfk----kpiaminnkk-fksgkaykdsklcnmlttrelhrrfhq----
-------et-givfnslypgcva---dtpl-frnh----------yslfrtifpwfqknv---tk
gyvsqelagervamvvaddkfkdsgvhwsw-----------gn---rqqagre------------
----------afvqel--s-eqgsdaq---kaqrmwdlseklvglv-
>Trichodesmium_erythraeum_IMS101_1332
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mkenhkstvvitgassgvglhaakalak--tgewyvvmacrdiskae
kvaqevgmt--------------qd-------------sytvmhldlaslevvkrfvktfr--es
grs------le--alvcnaavyl-----p----llkepmrsidgyeisvatnhl---ghfllcnl
mledlk-kspak-----------dkrlvilgtvta--------------npkelggkipipappd
lgnl--qgfe-----qgfk----tpisminakk-fksgkaykdsklcnvltmrelhrryyk----
-------st-givfsslypgcva---dtpl-frnh----------yplfqklfplfqkni---tg
gyvsqdlagervaavvkdpeykesgiywsw-----------gn---rqkkdrk------------
----------sfvqev--s-deasddd---kaiklwelssklvgls-
>Nostoc_punctiforme_PCC_73102_1344
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mvqdrkstvvitgassgvglyaakalae--rg-wyvvmacrdvakaq
laaqsvgip--------------hq------------gsytimhidlgsldsvrqfvknfr--as
ghs------ld--alvcnaaiym-----p----likeplrspegyeltvttnhl---ghfllcnl
mledlk-ksss------------eprlvilgtvth--------------npdelggk--ipprpd
lgdl--qgfa-----egfk----epismidgkk-fepvkaykdskvcnvltmrelhqryhe----
-------st-givfnslypgcva---etpl-frnh----------yplfqkifplfqkyi---tk
gyvsqelagervaavvadpeynqsgvywsw-----------gn---rqkedgk------------
----------sfvqkv--s-pqarddd---kgdrlwqlsaklvgla-
>Synechococcus_sp._PCC_7335_1364
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------meqpqssnviitgassgvglyaakslaa--rg-whvimacrnlpkae
rvakevgmp--------------eg-------------sytilkldlssldsvrqfvedfr--at
grs------ld--alvvnaaiyk-----p----slkspersvdgyeisvatnhl---ghfllcnl
lledmk-kaahp-----------eprlvtlgtvta--------------npkelggkipipappd
lgdl--kgme-----lgfk----spiamidgkk-fkpgkaykdsklcnmltmlemhrryhd----
-------et-givfnalypgcva---esdl-frda----------pklfqtifpffqkni---tg
gyvseeesgdrvakvvdeegfnksgvywsw-----------gn---rqdknre------------
----------afcqev--s-neaadan---kagklwdlseklvgla-
>Cyanobium_sp._PCC_7001_1384
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------maadptpgtvlitgttsgvglhatkalvd--rg-wtvvtanrdpvraa
aaaeslgip--------------sa-------------qlhhlridlgdldsvragvetlvs-sl
grp------ld--alvinaavyk-----p----rlkqperspqgyelsmatnhl---ghflliql
llpdle-hsthp-----------srrvvilgtvta--------------nskelggkipipapad
lgdl--sgfa-----agfk----apiamasgka-fkpgkaykdsklcnmittqelhrrlhg----
-------st-givftslypgcva---dtpl-frnt----------prlfqkifpwfqknv---tg
gyvsqalagervaqvvadpefavsgvhwsw-----------gn---rqkqggr------------
----------qfsqel--s-dkasnpd---tarkvweyslklvel--
>Synechococcus_sp._RS9917_1392
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------mglnaakalvd--rg-wrvvtanrdpvraa
qaaeslglp--------------sa-------------qlhhlridlgdldsvragvealig-sl
pge------ld--alvcnaavyk-----p----rlkeperspqgyeismatnhf---ghflliql
lmptlq-asshp-----------srrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----qgfq----apismasgkp-fkpgkaykdsklcnmitsqelhrrlhe----
-------pt-givfsslypgcva---dtpl-frdt----------pkafqtifpwfqkni---tg
gyvtqalagervaqvvadpdfgtsgvhwsw-----------gn---rqkkdgr------------
----------qfsqel--s-dkatdpr---taqrvwdlsmqlvgva-
>uncultured_marine_type-A_Synechococcus_5B2_1394
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlitgttsgvglnatkalva--rg-wtvitanrspqraa
gaadaleip--------------ke-------------rlqhvlmdlsdldsvrrava-----al
psg------vd--alvcnaavyk-----p----klklperspqgfeismatnhf---ghflliql
lldriq-assht-----------skrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----sgfk----qpvsmasgka-fkpgkaykdsklcnmittqelhrrlha----
-------et-gitfnslypgcva---dtpl-frnt----------pkafqtifpwfqkni---tg
gyvsqalagervaqvvadadfaesgvhwsw-----------gn---rqkqngq------------
----------qfsqel--s-dkatdpd---tarkvwdlsmqlvgl--
>Synechococcus_sp._RCC307_1396
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------------plaivtgassgvglwttkalid--qg-wtvvmacrdgakaq
qalvelglg--------------rp------------aeaiilpldlsdfesvkafvelfr--gl
nrp------lt--alvinaavyk-----p----llkepewsaqgyelsmatnhl---ghfllarl
llddlk-aspaa-----------dkrlitlgtvta--------------nskelggkipipapad
lgdl--sgfa-----qgfk----apiamasgkk-fkpgkaykdsklcnmitslelhrrfhg----
-------at-gisfsslypgcva---dtpl-frns----------lpafqkifpwfqkni---tg
gyvsqalagervaqvvadpafrssgahwsw-----------gn---rqkkdgk------------
----------qfeqel--s-dkasdpa---talrvwdlssalvgl--
>uncultured_marine_type-A_Synechococcus_GOM_5D20_1412
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlitgttsgvglnatcalvk--rg-wtvitanrspqraa
taaeemdip--------------ke-------------rlkhvlmdlgdldsvrravd-----al
pdr------ld--avvcnaavyk-----p----klkqpdrspqgyeismatnhf---ghfllvql
llgrlq-nsshp-----------srrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfq----epvsmasgks-fkpgkaykdsklcnmittqelhrrlhg----
-------nt-gitftslypgcva---dtpl-frnt----------pkafqtifpwfqkki---tg
gyvsqslagervadvisnsdfaesgvhwsw-----------gn---rqkkdgq------------
----------qfsqel--s-dkvtdpv---tarrvwdlsmqlvgl--
>Synechococcus_sp._WH_8102_1416
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlitgttsgvglnatcalvk--rg-wtvitanrspqraa
aaaddmdlp--------------ke-------------rlqhvlmdlgdldsvrravd-----al
pdr------ld--avvcnaavyk-----p----klkqperspqgyeismatnhl---ghfllvql
llgrlq-nsshp-----------srrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfk----ypvamasgkp-fkpgkaykdsklcnmistqelhrrlhg----
-------es-gitftslypgcva---dtpl-frnt----------pkafqtifpwfqkni---tg
gyvsqalagervadvvahpdfaesgvhwsw-----------gn---rqkkdgq------------
----------qfsqel--s-dkatdpd---tarrvwdlsmqlvgl--
>Synechococcus_sp._BL107_1422
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------------vlitgttsgvglntakslas--rg-wqvitanrspqraa
aaaddlgip--------------ke-------------rlqhvlmdlgdlesvrravq-----sl
pat------ld--avvcnaavyk-----p----klkqperspqgyelsmatnhl---ghfllihl
lldrlk-gskhp-----------srrvvilgtvta--------------nskelggkipipapad
lgdl--sgfy-----qgfl----dpiamangqp-fkpgkaykdsklcnmittqelhqrlhq----
-------dt-gitfsslypgcva---dspl-frnt----------prafqtifpwfqkni---tg
gyvtqalagdrvaqvvadpdfaesgvhwsw-----------gn---rqkkdgq------------
----------qfsqel--s-dkatdpe---tassvwdlskqlvgl--
>Thermosynechococcus_elongatus_BP-1_1440
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------dqprptviitgassgvglyatkalan--rg-whvimacrnlekae
qaaknlqip--------------pe-------------aytilhldlsslasvrgfvesfr--al
nrp------lr--alvcnaavyy-----p----llkepiysvdgyeitvatnhl---ghfllinl
lledlk-nspes-----------dkrlvilgtvta--------------nrkelggkipipappd
lgnl--egfe-----kgfk----kpiamingkp-fksgkaykdsklcnmltarelhrrfhe----
-------st-givfnslypgcva---dtpl-frhh----------fplfqklfplfqkki---tg
gyvsqelagervamvvadpefrqsgvhwsw-----------gn---rqkegrk------------
----------afvqel--s-aeasdeq---karrlwelseklvgl--
>Lyngbya_sp._PCC_8106_1448
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------meqhqkstvvitgassgvglqaakalak--kg-wyvvmacrnlekte
kaaqtvgip--------------ad-------------tytiipldlaslesvhqfvktfr--es
gks------ld--alvcnaavyl-----p----lekepqrsadgyelsvatnhl---ghfllcnl
mledlk-hsats-----------eprliilgtvta--------------npkelggkipipappd
lgnm--qgle-----agfq----apismidgkk-fksgkaykdsklcnvltmrelhrryhe----
-------st-givfsslypgcva---ttal-frnh----------yplfqkifpwfqkni---tg
gyvseelagervamvvaepeyntsgvywsw-----------gn---rqkegrk------------
----------sfmqev--s-nealddn---kaeklwklsaklvgm--
>Fremyella_diplosiphon_Fd33_1454
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------meqnrkstvvitgassgvglytakaman--kg-whvvmacrnlakae
eaaqsvgip--------------rd-------------shtilhldlgsldsvrqfvsnfr--at
gkt------ld--allcnaaiym-----p----likeplwspegyeltmttnhl---ghfllcnl
mledmk-nspyr-----------drrlvilgtvth--------------npdelggk--ipprpd
lgnl--egfs-----agfk----apitmidgkk-fepvkaykdskvcnvltmrelhrryhe----
-------st-gitfsslypgcva---etpl-frnh----------yplfqkifplfqkyi---tg
gyvsqdlsgervaavladpeykqsgaywsw-----------gn---rqkkdgk------------
----------sfvqrv--s-pqardde---kaerlwdlseklvgl--
>Synechococcus_sp._WH_5701_1472
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvmitgassgvglyaakalaq--rg-whvvmacrdlakak
aaasslaip--------------es-------------slthlqvdlgdlesvrrlvnafh--at
grs------ld--alvcnaavyk-----p----rlkqperspqgyeismatnhl---ghflliqa
llddmk-ksshp-----------srrlvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfk----apismanska-fkpgkaykdsklcnmittqelhrrlhd----
-------st-giifsslypgcva---dtpl-frnt----------prafqtifpwfqkni---tg
gyvsqelagervaqvvadpafavsgahwsw-----------gn---rqkangq------------
----------qfiqel--s-dkasdpe---taaktwdlsmklvgl--
>Crocosphaera_watsonii_WH_8501_1474
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mvenrqstvvitgassgvglyaakalad--rg-wyvvmacrnqpkah
qaaqslgia--------------ld-------------aytvmhidlgnldsvrqfaqdfr--at
gkt------ld--alvcnaaiym-----p----llkeplrspegyelsmttnhl---ghfllcnl
mledls-hssap-----------ekrmvilgtvth--------------npdelggk--ipprpd
lgnl--egfa-----dgfk----epismvdgkn-fepvkaykdskvcnvltmreldrryhe----
-------st-givftslypgcva---dtpl-frnh----------yplfqkifpwfqknv---tg
gyvsqelagervadvvtkpeygesgsywsw-----------gn---rqkkdrq------------
---------aafvqnv--s-pqaqdea---kaekmwnlseklvgl--
>2Nostoc_sp._PCC_7120_1338
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------maqdrkstvivtgassgvglyaakalak--rg-whvvmacrnlekae
qaaqevgip--------------kd-------------sysiihidlgsldsvrqfvndfr--at
gks------ld--allcnaaiym-----p----likeplrspegyeltmttnhl---ghfllckl
mledlq-kssav-----------dkrlvilgtvth--------------npdelggk--ipprpd
lgnl--egfa-----qgfk----ppismidgkk-fepvkaykdskvcnvltmrelhrryhe----
-------st-gitftslypgcva---etpl-frnh----------yplfqkifplfqkyi---tg
gyvsqelagervadviaapeykqsgaywsw-----------gn---rqkkdgk------------
----------sfvqkv--s-pqardde---kaerlwdlseklvgl--
>2Cyanothece_sp._CCY0110_1346
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mvenhkstviitgassgvglyaakalad--rg-wyvvmacrnqpkah
qaaqsvgip--------------ld-------------sytvmsidlgsldsvrqfvkdfr--at
gks------ld--alvcnaaiym-----p----llkeplrspegyelsmttnhl---ghfllcnl
mlqdlk-rspap-----------ekrvvilgtvth--------------npnelggk--ipprpd
lgnl--egfa-----egfk----epvsmidgkk-fepvkaykdskvcnvltmrelhrryhe----
-------nt-gvvftslypgcva---dtpl-frnh----------yplfqkifpwfqkni---tg
gyvsqelagervadvvtkpeygqsgsywsw-----------gn---rqkkdrk------------
---------aafvqkv--s-pqaqdea---kaermwelseklvgl--
>2Nodularia_spumigena_CCY9414_1358
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------maqdqkstvvitgassgvglqaaralsq--kg-wyvvmacrnlskae
naakslgme--------------pd-------------sytvmhidlgslesvrqfvkdfr--as
gks------ld--alvcnaaiym-----p----likeplrspegyelsvatnhl---ghfllcnl
lledlk-nspss-----------eprlvilgtvth--------------npkelggk--ipprpd
lgdl--qgfa-----agfk----epiamidgkk-fepvkaykdskvcnvltmrelhrryhe----
-------sh-gitfsslypgcva---ttal-frnh----------yplfqkifplfqryi---tg
gfvteeesgdrvaevvsdpqynqsgaywsw-----------gn---rqkkngk------------
----------sflqev--s-neasddd---kaermwelsaklvgla-
>2Arthrospira_maxima_CS-328_1362
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mvqdqkstvivtgassgvglyaakalad--rg-ahvimacrnlekae
aaaqelgip--------------ed-------------srtilhidlgslesvrrfinsfr--at
grt------le--glvcnaaiym-----p----likeplrspegyeltmttnhl---ghfllcnv
mmedmk-rspae-----------dkrmvilgtvth--------------npdelggk--ipprpd
lgdl--egfa-----kgfr----epvsmidgkk-fepvkaykdskvcnvltmrelhrryhe----
-------et-gitftslypgcva---dtpl-frnh----------yplfqkifpifqkyi---tk
gyvsqelagervaavvldeeyrqsgaywsw-----------gn---rqkkgrq------------
----------sfvqrv--s-pqardee---raekmwnlslklvela-
>2Dinoroseobacter_shibae_DFL_12_1380
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mtldpmpraivtgassgvglhatkslid--rg-whvtmacrdlakae
aaarsldld--------------pg-------------ryalahldlgslasvrafhania--rd
hds------ld--alvcnaavyk-----p----rltqpgrspdgfeisvatnyf---ghfllanl
mlplle-gapsp-------------rlitlgtvta--------------nseefggkvpipapad
lgdf--aglk-----agfr----apvamidgkp-fkagkaykdsklctmmmsrelhtrhha----
-------rt-givfatlypgcva---dtpl-frdt----------pkafqtifpwfqknv---tk
gyvsqalsgervamvvadpefaqsgvhwsw-----------gn---rqregrs------------
----------afaqgl--s-tkatdaa---rsaelweltaaltgl--
>2Synechococcus_sp._CC9605_1398
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlitgttsgvglnatcalvk--rg-wtvitanrspqraa
aaadeldlp--------------kd-------------rlkhvlmdlgdldsvrravd-----al
per------ld--avvcnaavyk-----p----klkqperspqgyeismatnhf---ghfllvql
llgrlk-asthp-----------skrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfk----dpvamasgkp-fkpgkaykdsklcnmittqelhrrlhg----
-------dt-gitftslypgcva---dtpl-frnt----------pkafqtifpwfqkni---tg
gyvsqslagervadvvahpdfaesgvhwsw-----------gn---rqkkdge------------
----------qfsqel--s-dkatdpe---tarrvwelsmklvg---
>2Synechococcus_sp._RS9916_1400
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlvtgttsgvglntvkalas--qg-wtvitgnrspqraa
gaadaldip--------------ke-------------rlkhiqmdlgdldcvrrava-----sl
dqp------id--alvcnaavyk-----p----rlkqaerspqgyeismatnhl---ghfllihl
lmpalq-asthp-----------skrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfq----epitmannka-fkpgkaykdsklcnmittqelhrrlhg----
-------et-givfsslypgcva---dtpl-frnt----------pkafqtifpwfqkni---tg
gyvtqalagervaqvvsdpdfavsgvhwsw-----------gn---rqkkdgq------------
----------qfsqel--s-dkatdpq---taervwdlsmklvglg-
>2Cyanothece_sp._PCC_7424_1482
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mqqqpkstviitgassgvglqaakalal--sg-wyvimacrdlektr
rvakevgmp--------------sg-------------symiihidlaslesvrqfvrdfr--ai
grs------ld--alvcnaaiym-----p----llkeplrspegyeltvatnhl---ghfllcnl
mledlk-kssas-----------ppklvilgtvth--------------npdelggk--ipprpd
lgdl--kgfa-----egfk----epytmidgkk-fepvkaykdskvcniltmrelhrryhe----
-------st-givfnslypgcva---ttal-frnh----------yplfqklfplfqkhi---tg
gfvseelsgqrvaqvvtdpafaqsgvywsw-----------gn---rqkkngn------------
----------afvqkv--s-sqardde---naerlwelseqlvgl--
>2Microcoleus_chthonoplastes_PCC_7420_132
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------meqhqkstvvitgassgvglyaakalaq--rgnwhvvmacrnlekaq
naaqevgmp--------------ed-------------sytimhidlgslesvrqfvakfr--es
gks------ld--alvcnaaiym-----p----llkeplrspegyelsvatnhl---ghfllshl
mledlk-hssae-----------sprlvilgtvth--------------npdelggk--ipprpd
lgql--kgfe-----agfk----ephsmidgkk-fepvkaykdskvcnvltmrelhrryhe----
-------st-givfsslypgcva---dtpl-frnh----------yplfqkifplfqkhi---tg
gyvsqelsgervaavvadpeysqsgvywsw-----------gn---rqkkdgk------------
----------sfvqkv--s-pqarddq---kgermwelsaklvgva-
>Synechococcus_sp._PCC_7002_150
-----------------------------------------------------------------
-----------------------------------------------------------------
---------------------dqqktaiitgassgvglygakalad--kg-whvvmacrnlekte
rvakevgip--------------ea-------------srtimhldladfdsvrkfvadfr--at
gkt------ln--slvcnaavyl-----p----lakepqrnkdgyelcvatnhl---ghfllcnl
mledlk-nspaa-----------dkrlvilgtvta--------------npkevggkipipappd
lgdl--qgma-----agfk----ppvamidgki-fkpgkaykdsklcniltmrelhnryhk----
-------dt-giifnsfypgcva---etgl-frnh----------yglfrkifpwfqkni---tg
gyvteevagerlakvvadsgfdvsgvywsw-----------gn---rqqqgre------------
----------afmqev--s-dealddn---kadvlwdlsaklvgm--
>2Synechococcus_sp._JA-2-3B&apos_a_2-13__162
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mqgqeqptvvitgassgvglysalalak--rg-whvvmacrdldkay
rvaqqvgip--------------qg-------------sytlmqidlaslasvrrfveqfr--nw
grs------ld--alvcnaaiym-----p----llkqplrspegyeltmatnhl---ghfllchl
mledlk-rstyp-----------drrlvilgtvth--------------npkelggk--ippqph
lgdl--rgfa-----qgfk----dpismadggk-fepvkaykdskvcniltmrelhrlfhe----
-------st-gitflslypgcva---ttal-frhh----------yplfqklfpwfqkni---tg
gfvsqelagervaqvvadpefrrsgfywsw-----------gn---rqrknak------------
----------pfnqev--s-deaadda---kakllwdlseklvgv--
>2Cyanothece_sp._PCC_7425_170
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------mgqdqkptviitgassgvglyaakalan--kg-fhiimacrdlhkag
qaaqtvgip--------------qg-------------syslmhidlgdldsvrrfarevs--as
grp------lk--alvcnaaiym-----p----llkeplrspegyeltmttnhl---ghfllcnl
lledlk-qsrve-----------dkrvvilgtvth--------------npdelggk--vyprpd
lgkf--egfa-----agfk----epvsmvdgkk-fepvkaykdskvcnvltmkeldrryhd----
-------tt-nitfsslypgcva---dtpl-frnh----------yptfqklfplfqkyi---tg
gyvsqelagervaqvvadpefresgaywsw-----------gn---rqkqgrk------------
----------afmqkv--s-rqarnnd---kaeqmwvlseklvgla-
>2uncultured_marine_type-A_Synechococcus_GOM_4P21_182
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlitgttsgvglnatkalve--rg-wtvitanrspqraa
gaademeip--------------kd-------------rlqhvlmdlgdldsvrsave-----kl
pgg------vd--alvcnaavyk-----p----klkqperspqgyeismatnhf---ghfllvql
lldrir-asshp-----------srrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfl----epismasgkp-fkpgkaykdsklcnmittqelhrrlhg----
-------et-gitftslypgcva---dtpl-frnt----------pkafqtifpwfqkni---tg
gyvsqalagervaqvvadpdfaesgvhwsw-----------gn---rqskdgq------------
----------qfsqel--s-dkatdpd---tarrvwdlslrlvgl--
>2uncultured_marine_type-A_Synechococcus_GOM_3O12_204
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlitgttsgvglnatsalvk--rg-wtvitanrspqraa
aaaddvdlp--------------kd-------------rlqhvlmdlgdldsvrravd-----al
peq------ld--avvcnaavyk-----p----klkqperspqgyeismatnhf---ghfllvql
lldrlk-asshp-----------skrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfq----epvsmasgkp-fkpgkaykdsklcnmittqelhrrlhg----
-------et-gitftslypgcva---dtpl-frnt----------pkafqtifpwfqkni---tg
gyvsqslagervadvvanpdfaesgvhwsw-----------gn---rqkkdgq------------
----------qfsqel--s-dkatdpv---taqrvwdlsmqlvgl--
>2Synechococcus_sp._WH_7805_206
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlitgttsgvglnatralvs--rg-wtvitanrspqraa
aaadeldlp--------------ke-------------rlqhvlmdlgdlesvrqavd-----al
pet------ld--avvcnaavyk-----p----klkqperspqgyeismatnhf---ghfllvql
llgrlq-nsshp-----------srrvvilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfk----dpiamasgkp-fkpgkaykdsklcnmittqelhrrlha----
-------dm-gitftslypgcva---dtpl-frnt----------pkafqtifpwfqkni---tg
gyvsqalagervadvvanpdfaesgvhwsw-----------gn---rqkkdgq------------
----------qfsqel--s-dkatdpd---tarrvwelsmqlvgl--
>2Synechococcus_sp._CC9311_220
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tvlitgttsgvglnatqalvr--qg-wtvitanrnpqraa
gaadqldip--------------rg-------------rlhhilmdlgdlesvrhave-----nl
sig------id--alvcnaavye-----p----klkqpkrspqgyelsmatnhl---ghflliql
lldrlk-asshp-----------skrivilgtvta--------------nskelggkipipapad
lgdl--sgfe-----agfq----dpvsmasgql-fkpgkaykdsklcnmittqelhrriya----
-------dt-gisctslypgcva---dtpl-frnt----------pkafqvifpwfqkki---tg
gyvsqslagervamvvanpafnqsgvhwsw-----------gn---rqkkdgq------------
----------qfsqel--s-dkatnpd---varrvwelsmklvgl--
>2Prochlorococcus_marinus_subsp._marinus_str._CCMP1375_226
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------qsapgtvlitgttsgvglyatkalid--lg-wkvitanrsperae
kaavklglp----------fr-cpk-------------qlqhisidlsdldsvskgvkdlld-kl
dep------ld--alvcnaavym-----p----rlskprrspqgyelsmatnhf---ghflmiql
llenls-kskrpvwk-grswgiessrlvmlgtvta--------------nykelggkipipapad
lgdl--sgfk-----egfl----dpicmasgkr-fkpgkaykdsklcnmitiqelhrrfkd----
--------s-svvfsslypgcva---ntkl-frnt----------pkifqwlfplfqrfv---tg
gfvsqplagkrvaqvvsspefgisgvhwsw-----------gn---rqkknge------------
----------qfsqkl--s-eritdpe---tasdvwdlsmkl-----
>2Gloeobacter_violaceus_PCC_7421_228
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------tviitgassgvglhaadslaq--sgrwhvvmacrdkakaq
naaaslgmr--------------pq-------------sytivhldlaslasvrrfvqdfr--al
gqp------ld--alvcnaavyt-----p----tareprytadgfelsvgtnhl---ghfllcnl
lledlq-nspaa-----------eprlvilgtvth--------------npkelggs--ipprpd
lgdl--rgle-----qgfk----aphtmidgka-ynpvkaykdskvcnlltmrelhrrfht----
-------sh-kitfsalypgcva---tsgl-fres----------prlfqilfpvfqkyv---tg
gfvseaeaggrvaalvddpaysrsgvywsw-----------gn---rqkkdgk------------
----------sfiqdv--s-teasded---karrlwdlsaglvgla-
>2Prochlorococcus_marinus_str._MIT_9515_234
-----------------------------------------------------------------
-----------------------------------------------------------------
---------------------stkglvlitgttsgvglntlkpllr--fg-weviavnrsnkrai
eiahqsltd----------se-mk--------------nmhfieidlsdlddvrngcdeilk-kf
kkp------in--smicnaavyk-----p----rlrkpersaqgfensmavnhf---ghflminl
lidkil-sseneiylngkvtkf-kpritvlgtvta--------------nyselggripipapan
lgnl--sgfk-----ngfl----apismangkk-fkpgkaykdsklcnmitvqelskkysn----
-------er--iiinslypgcva---dtkl-frnt----------pwifrflfpifqkfi---tk
gyvsqrlagervaqvatfkkyakpavhwsw-----------gn---rqksgrk------------
----------afsqkl--s-kriidsd---iskqtyeltrklvgl--
>41_Cyanothece_sp._PCC_7822_132
-----------------------------------------------------------------
-----------------------------------------------------------------
----------------------rkstaiitgassgvglqaakalad--lg-wyvvmacrdiektk
rvaqevgmp--------------ad-------------syniiyidlaslqsvrefvkyfr--al
srp------ld--alvcnaaiym-----p----llkeplwspdgyeltmatnhl---ghfllcnl
mlddlk-qsavk-----------paklvilgtvth--------------npnelggk--ipprpd
lgnl--qgfa-----agfk----apysmidgka-fepvkaykdskvcniltmrelhrryha----
-------st-giifnslypgcva---ttal-frnh----------ypkfqkyfplfqkyi---tg
gfvseelsgqrvaqvvaepdfaqsgvywsw-----------gn---rqkkngq------------
----------afvqkv--s-tqagdda---kavrlwelseqlvgl--
>55_Cyanothece_sp._PCC_8801_164
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------tqdqk-tviitgassgvglyaakaliq--kwgyhvvmacrnldkty
rvaqelgfp--------------sd-------------sytvlpidlgslgsvryfvqafr--et
kkp------ld--allcnaaiym-----p----llkeplrspegyeltmttnhl---ghfllcnl
lledlq-rsssp-----------eprvvilgtvth--------------npdelggk--ipprpd
lgnl--egfe-----agfv----ephsmidgkk-fepvkaykdskvcnvltmrelhrryhd----
-------st-gitfsslypgcva---ttal-frnh----------yplfqklfplfqkhi---tg
gfvseelagervadvvaapeynqsgsywsw-----------gn---rqkkdre------------
----------sfvqqv--s-pqardde---kaekmwdlsaqlvgla-
>61_Synechococcus_elongatus_PCC_6301_178
-----------------------------------------------------------------
-----------------------------------------------------------------
----------------------qqptviitgassgvglygakalaa--rg-whvvmacrnlqkaa
eaakslgin--------------pe-------------nyslmeidlgslasvrrfvdqfr--at
grs------ld--alvcnaavyl-----p----rlkepqrspegyeisvatnhf---ghfllcnl
llddlk-rspap-----------ekrlvilgtvta--------------nskelggkipipapad
lgnl--egle-----agfk----apiamidgkk-fkpgkaykdsklcnmittrelhrrfhd----
-------st-givfgslypgcva---dtpl-frnt----------pklfqkifpwfqkni---tg
gyftqelagervaqvvadpefktsgvhwsw-----------gn---rqqkdrq------------
----------sfvqel--s-dkasddr---taqrlwdlsaklvgl--
>65_Microcystis_aeruginosa_PCC_7806_188
-----------------------------------------------------------------
-----------------------------------------------------------------
----------------------qkptviitgttsgvglyaakslaq--rg-wfvvmacrdipkme
qaakelnip--------------rd-------------nyciefidlgslnsvrrfvknfr--al
grs------lt--alvcnaaiyl-----p----llkeplrspdgyelsmatnhl---ghfllsnl
lledlk-nspsp-----------drrlvilgtvth--------------npdelggk--ipprpd
lgdl--egfa-----kgfk----epitmadgkk-fesvkaykdskvcnvltmrelhkryhe----
-------st-gitftslypgcva---dtpl-frnh----------ypffqqffpwfqkni---tg
gyvsqelagervaivvadpqyrqsgaywsw-----------gn---rqkkegk------------
----------sfvqrv--s-pqardee---rgekmweysaklvgla-
>71_Prochlorococcus_marinus_str._MIT_9313_220
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------------gtvlitgttsgvglyackalvy--rg-wqvitanrhplrav
aaaervgip--------------aa-------------qlthlrmdlsdlqsvrdgvetllg-sl
eqp------ld--alvcnaavyq-----p----rlrkpkrsaqgyelsmatnhf---ghflliql
llenlg-kak--vfqsargsylsaarvvilgtvta--------------nykelggkipipapad
lgnl--sgfe-----qgfh----apismasgks-fkpgkaykdsklcnmittqelhrrlhe----
-------qs-gilftslypgcva---dtpl-fryt----------pkifrflfpifqrli---tg
gyvtqakagqrvaqvvtnpefgvsgvhwsw-----------gn---rqkknre------------
----------sfrqel--s-eratdpi---takrvwelsmklvgl--
>74_Paulinella_chromatophora_232
-----------------------------------------------------------------
-----------------------------------------------------------------
------------------------gtvlvtgtssgvglytakalia--kg-whvisvsrniekak
lalqnfggn--------------na-------------nlthltidlgdlnsvkncvhefr--rl
gkt------ld--alvcnaavyl-----p----rlkepiispqgyeismatnhl---ghflliql
llsdlq-lsrhp-----------srrivilgtvta--------------nskelggkipipapad
lgdl--sgfe-----egfq----mpismanskk-fkpgkaykdsklcnmitarelhrrlhn----
-------st-giifsslypgcva---dtpl-frnt----------psafqtifpwfqkni---tg
gyvsqglagervaavvtdrnfaqsgvhwsw-----------gn---rqkrngk------------
----------efvqel--s-nqasdeg---tskklwdlsmnlvdi--
>78_&apos_Nostoc_azollae&apos__0708_252
-----------------------------------------------------------------
-----------------------------------------------------------------
----------------------rqstvvitgtssgvglqaakalaq--tgqwqvvmacrnlskae
eaaqsvgir--------------qg-------------sytiihldlasldsvrqfvkdfr--at
grs------ld--alvcnaaiym-----p----likeplwspdgyelsvatnhl---ghfllcnl
mledlk-kssas-----------eprlvilgtvth--------------npnelggk--ipprpd
lgdl--kgfe-----agfk----apysmidgkk-fepvkaykdskvcnvltmrelhrryhe----
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------
>83_&apos_Nostoc_azollae&apos__0708_278
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
--------t-gitfsslypgcva---ttal-frdh----------yplfqklfpifqkyi---tg
gfvseeeagkrvaevvadpaynqsgmywsw-----------gn---rqkkngk------------
----------sfvqkv--s-neasded---kaerlwelsaklvgla-
>39_>gi|82582335|sp|Q5F389.2|WWOX_CHICK_RecName__Full=WW_domain-containing_oxidoreductase_190
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------viiitgansgigfetaksfal--hg-ayvilacrnmsrgn
davqrilee----------wh-ka--------------kveamtldlaslrsvqnfaeafk--sk
nmp------lh--ilvcnaaifg---s-s-------wc-ltedglestfqvnhl---ghfylvql
ledilr-rss-------------parvvvvssesh--------------rfteik-d--ssgkld
fsll--spsk---------------------ke-ywamlaynrsklcnilfsnelnrrl------
------sph-gvtsnsvhpgnmi---yssi-hrnww------------vytllftlarpf-----
-tksmqqgaattvycataaeleglggmyfn-----------nc---c------------------
--------------rclps-aearnel---tavalwelserli----
