>58_Phaeodactylum_tricornutum_CCAP_1055/1_170
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------------vvitgassglglncattlak--tgryfvvmacrdvekgk
qvakekglp--------------dn-------------syvvmklelgnlqsvrdfvsnlkafka
arp------lt--hlicnaavyk-----p----kdpepawtddgfemsmgvnhl---ghfllvhl
lmddms-rak-------------garvcivgsitg--------------ntntvgggl-vypqad
lgkl--qgfe-----kgak----kpvamadgkp-ffgakaykdskvcnmmtvselnrlyhk----
-------dt-givfssmypgcia---etal-frek----------rpwfrkafpwfmkyv---tg
gyvgmeeagerlaqviddpqctksgvywsw-----------ng---gaqt---vgrwspdgkprg
aggsgg---eifenqq--s-davrdlp---takkmwklsreavgls-
>59_Thalassiosira_pseudonana_CCMP1335_172
-----------------------------------------------------------------
-----------------------ssqirtqrlttsnnnniiamptntysqsptilsemlttaelp
qklyfpkedkepakvlgglkigtrkltvitgassglglncaatlak--tgrhfvvmacrdvekgk
rvakefgmp--------------dd-------------syvvmklelgslqsvrdfvfnlkafks
arp------vn--nlicnaavyk-----p----tdpepawtddgfeqsmginhf---ghfllvnl
mvddla-kak-------------garccivgsitg--------------nsntv--gl-vyprad
lgnl--qgfa-----qgak----epiamadgkp-ffgakaykdskvcnmmtvselhrryhd----
-------st-giafssmypgcia---etql-frek----------rpwfqkafpwfmkyv---tg
gyvgmeeagerlaqvvddpqctksdvywsw-----------ng---gaqq---vgrwsddgkpkg
aggsgg---eifeneq--s-davrdre---taqkmwdysvravgl--
>66_Bigelowiella_natans_192
-----------------------------------------------------------------
-----------------------------------------------------------------
---------------------------vitgassglglntarslie--sgkwhvvmavrdpekar
reaermgfp--------------kd-------------rysieevelssfesvrrmakkl---kr
grq------id--tlicnaalyl-----p----ahqnpeytvdgyetslqvnhl---shflllnl
llptik-ksr-------------dprvivvgsitg--------------ntntvggga-vwpwad
lgkl--ngla-----ekagte--kgpemingga-wngakaykdsklanmmtifeadrrlhk----
-------ds-gvtfstmypgcia---etgl-frdk----------kpwfrklfplfmryv---tg
gyvseweagdrlaevassdrckesgvywgw-----------ng---aaktvaylkpgtdasnrgl
tgaggag---gsieelpps-pearnae---karrlwelsakavgl--
>76_Thalassiosira_pseudonana_CCMP1335_248
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------------vvitgcssglgretvknlla--tdkyhvvgavrdvdkme
avaeldgfn--------------md-------------nfkimelelnsfesvdkfcdnlkdyql
akp------id--rlicnagvyq-----p----sldyakwsvdgheqtmqinfl---shflmisk
lmpgms-vap-------------dprvimvgsvtg--------------ndntvgggg-vypiad
lknl--dgfk-----agfk----npiamadgyg-figakaykdsklclmmtsnflhskyhr----
-------nt-giafssiypgcia---etpl-frek----------rawfrkyfpifmkyi---tg
gyvgvdeagqrlfqvahdprcsksgvywsw-----------n-----------------------
-----------------------------------------------
>77_Phaeodactylum_tricornutum_CCAP_1055/1_250
-----------------------------------------------------------------
-----------------------------------------------------------------
---------------------------iltgassglgrktamallr--tgeyhvigavrdldkme
avaevdgfd--------------le-------------nftpmycelnsfesvrsfcenveefrm
skp------id--rlicnagvyq-----p----slehakwsldnheqtmqinfl---shflmist
mmksmm-esp-------------dprvimvgsvtg--------------ndntvgggg-vypiad
lhel--eglk-----qgfk----npiemadgyg-figakaykdsklclmmmanflhtkynk----
-------lt-gisfasmypgcia---espl-frek----------rpwfrkyfpifmkfi---tg
gyvgeheagqrlfqvahdprcsksgvywsw-----------ng---gpregrgveaiekggqisg
gggagggwdsifendq--s-gkvldve---talnlfkystditg---
>39_>gi|82582335|sp|Q5F389.2|WWOX_CHICK_RecName__Full=WW_domain-containing_oxidoreductase_190
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------viiitgansgigfetaksfal--hg-ayvilacrnmsrgn
davqrilee----------wh-ka--------------kveamtldlaslrsvqnfaeafk--sk
nmp------lh--ilvcnaaifg---s-s-------wc-ltedglestfqvnhl---ghfylvql
ledilr-rss-------------parvvvvssesh--------------rfteik-d--ssgkld
fsll--spsk---------------------ke-ywamlaynrsklcnilfsnelnrrl------
------sph-gvtsnsvhpgnmi---yssi-hrnww------------vytllftlarpf-----
-tksmqqgaattvycataaeleglggmyfn-----------nc---c------------------
--------------rclps-aearnel---tavalwelserli----
