>58_Phaeodactylum_tricornutum_CCAP_1055/1_170
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------------vvitgassglglncattlak--tgryfvvmacrdvekgk
qvakekglp--------------dn-------------syvvmklelgnlqsvrdfvsnlkafka
arp------lt--hlicnaavyk-----p----kdpepawtddgfemsmgvnhl---ghfllvhl
lmddms-rak-------------garvcivgsitg--------------ntntvgggl-vypqad
lgkl--qgfe-----kgak----kpvamadgkp-ffgakaykdskvcnmmtvselnrlyhk----
-------dt-givfssmypgcia---etal-frek----------rpwfrkafpwfmkyv---tg
gyvgmeeagerlaqviddpqctksgvywsw-----------ng---gaqt---vgrwspdgkprg
aggsgg---eifenqq--s-davrdlp---takkmwklsreavgls-
>59_Thalassiosira_pseudonana_CCMP1335_172
-----------------------------------------------------------------
-----------------------ssqirtqrlttsnnnniiamptntysqsptilsemlttaelp
qklyfpkedkepakvlgglkigtrkltvitgassglglncaatlak--tgrhfvvmacrdvekgk
rvakefgmp--------------dd-------------syvvmklelgslqsvrdfvfnlkafks
arp------vn--nlicnaavyk-----p----tdpepawtddgfeqsmginhf---ghfllvnl
mvddla-kak-------------garccivgsitg--------------nsntv--gl-vyprad
lgnl--qgfa-----qgak----epiamadgkp-ffgakaykdskvcnmmtvselhrryhd----
-------st-giafssmypgcia---etql-frek----------rpwfqkafpwfmkyv---tg
gyvgmeeagerlaqvvddpqctksdvywsw-----------ng---gaqq---vgrwsddgkpkg
aggsgg---eifeneq--s-davrdre---taqkmwdysvravgl--
>62_Ostreococcus_tauri_182
-----------------------------------------------------------------
----------------------------------------------rtrrapairqpstsrarrt
stlavaraagsssqnimpsngankpvaiitgassglglytakalie--kg-yfvvmavrdprkge
tkanelgfd--------------kk-------------syavmycelgelasvrefcsgfrrspy
vkn------fq--alvcnaalyl-----p----natvpsytkdgfeecvgvnhl---ahhlmcle
llddlakapdan-----------mkrliivgsvtg--------------ntntlagq--vpprag
lgdl--sglr-----ngfknsdrnqgahidgsr-figakaykdsklcnmldikvfaeryge----
-------st-gikfstmypgcia---dsnl-frnh----------tpffrwlfpilqknv---tk
gyvseeeagqrlasivydpryteqgaywawkgggdqlwdnfnn---nnedtrti-----------
----------afnnkp--s-regrdma---kanamfdistelvg---
>66_Bigelowiella_natans_192
-----------------------------------------------------------------
-----------------------------------------------------------------
---------------------------vitgassglglntarslie--sgkwhvvmavrdpekar
reaermgfp--------------kd-------------rysieevelssfesvrrmakkl---kr
grq------id--tlicnaalyl-----p----ahqnpeytvdgyetslqvnhl---shflllnl
llptik-ksr-------------dprvivvgsitg--------------ntntvggga-vwpwad
lgkl--ngla-----ekagte--kgpemingga-wngakaykdsklanmmtifeadrrlhk----
-------ds-gvtfstmypgcia---etgl-frdk----------kpwfrklfplfmryv---tg
gyvseweagdrlaevassdrckesgvywgw-----------ng---aaktvaylkpgtdasnrgl
tgaggag---gsieelpps-pearnae---karrlwelsakavgl--
>69_Ostreococcus_lucimarinus_CCE9901_212
-----------------------------------------------------------------
-----------------------------------------------------------------
---------------------------ivtgsssglglytakalik--ng-yfvvnavrspekmq
vkanelgld--------------es-------------syaimylelgdlqsvrdfatefrrsky
vkn------fq--alvcnaalyl-----p----natvpsytkdgfeecvgvnhl---ghhllsll
llddlaeapdan-----------mkrliivgsvtg--------------ntntlagq--vpprag
lgdm--sglr-----ngfknsdrnqgalidgtr-figakaykdsklcnmldikafaerfge----
-------st-gikfstmypgcia---dsnl-frnh----------taffrwffpilqknv---tk
gyvseeeagerlasivydpryseqgaywawkgggdqlwdnynn---nnddtrti-----------
----------afnnkp--s-kegrdma---kanevfdistelvg---
>76_Thalassiosira_pseudonana_CCMP1335_248
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------------vvitgcssglgretvknlla--tdkyhvvgavrdvdkme
avaeldgfn--------------md-------------nfkimelelnsfesvdkfcdnlkdyql
akp------id--rlicnagvyq-----p----sldyakwsvdgheqtmqinfl---shflmisk
lmpgms-vap-------------dprvimvgsvtg--------------ndntvgggg-vypiad
lknl--dgfk-----agfk----npiamadgyg-figakaykdsklclmmtsnflhskyhr----
-------nt-giafssiypgcia---etpl-frek----------rawfrkyfpifmkyi---tg
gyvgvdeagqrlfqvahdprcsksgvywsw-----------n-----------------------
-----------------------------------------------
>77_Phaeodactylum_tricornutum_CCAP_1055/1_250
-----------------------------------------------------------------
-----------------------------------------------------------------
---------------------------iltgassglgrktamallr--tgeyhvigavrdldkme
avaevdgfd--------------le-------------nftpmycelnsfesvrsfcenveefrm
skp------id--rlicnagvyq-----p----slehakwsldnheqtmqinfl---shflmist
mmksmm-esp-------------dprvimvgsvtg--------------ndntvgggg-vypiad
lhel--eglk-----qgfk----npiemadgyg-figakaykdsklclmmmanflhtkynk----
-------lt-gisfasmypgcia---espl-frek----------rpwfrkyfpifmkfi---tg
gyvgeheagqrlfqvahdprcsksgvywsw-----------ng---gpregrgveaiekggqisg
gggagggwdsifendq--s-gkvldve---talnlfkystditg---
>84_Ostreococcus_lucimarinus_CCE9901_280
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------tetkkrvvitgsnsgigldaatklaa--sgdwvvvlacrtrakae
aakani-ls----------at-nad-----------ganiecvecdlssldsvrafvrevr--k-
tgg------vd--alclnagvey-----s----gdpvvhrtrdgfeetfgvnhl---ghfllanl
lledle-kssea-----------hprivvtasevh--------------dpaspggs--vgsgah
igdl--rgle----rdg------aafemadge-afdadkaykdsklanmlfmyelerrlqa----
------rns-kitvnafgpglit---rtgl-frnq----------nplfvkvfdfatnei---fh
vaetvsgggnclvfmltdpsleg-sggvyw-----------nn---dlspgapp-slvaagh---
----------kfaqtn-ss-vesndav---eaqklwklseslvgla-
>85_Ostreococcus_tauri_282
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------kkrvvitgansgiglsaattlal--sgewtvalacrtkekse
qaraem-vs----------rg-vae------------sdvecyecdladldsvracarelr--r-
ngs------id--alalnagvef-----s----gdpvvhrtaqgleetvgvnhl---ghflltnl
lledle-rsela-----------hprivvtasevh--------------dpaspggs--vgngat
lgsl--egfe----rdg------krfemadgg-nfdadkaykdsklmnmlftyelerrlre----
------rgs-kitvnafgpglit---rtgl-frhq----------nplfvkvfdfatnev---fh
vaetvdrggdclvymleepsleg-vggvyf-----------nn---glapgtpp-t----gh---
----------kfertd-ss-vesnnqd---earklwvisedfvgl--
>90_Thalassiosira_pseudonana_CCMP1335_302
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------kqrilitgsnsgigldaaqrlal--rgh-evvlacrtldkai
aaadkiktn----------ia-ndsedavdaialiktlkltpmecdladlksidsfvnelk--kt
ssgeegrmmfd--avcynaglsr-----nt---aatdvlrtkqgfeltvgtnhf---ghfylnhl
mmplik-kdg--------------grmvvtasgvh--------------dpdspgga--qgipat
lgdl--agleqavargd------gkfdmvdgg-efnadkaykdsklcnvlftrelqrrlke----
------sgs-nvkvncfnpgliv---gtgl-frdq----------nqvftkvfdvaatsl---fk
vgetthwgggaleymalssevanergglfy-----------t-----appgsskygddafgr---
----------efkatq-as-kearasdvdgkakrfwelseklvgv--
>95_Gymnochlora_stellata_338
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------------vmitgantgigraaaeqlct--agh-svivvcrtivkaq
ktieeikat----------fg-dkv-----------tgnliplecdvsdldsvrrlvrdfr--dl
nlp------ln--vlvanagisl-----naqekgdeftqrskdgfeltiatnyl---ghflltnl
llpdle-ksg-s-----------dsrivitgsevh--------------dpsspggs--vgpgat
lgdl--sglk-------------skapmvdgg-pydadkaykds---nhvfmlelqrrlka----
------kgv-tvtansfgpglit---rsaf-fknq----------nglfsrlfdfatndi---fh
vaetvdfggaclsymalskdleg-kggl-w-----------ln---avqpgkp------------
----------vfeqlq-ps-ieardtk---kakmlydmsleavgla-
>96_Synechococcus_sp._WH_7805_346
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------------ilitgassgigleatrrlal--sgh-qltlfcrtperge
qtrsqlvaa----------ga-m-------------psqvswlladladlrsvqsacdqll--dr
aep------ld--alvlnagqqr-----a----gaeapvfspqgleitfavnql---ahqliatr
llpllr-lgs-------------qprlvitasdvh--------------npasgggr--vgqpad
lgdl--aglk-----ag------agfamldgsasfdgdkaykdsklcnvllgrelnrql------
-------da-mmpviawspglviprssggf-frhnr-------qsnplgmllfalvardv---lr
vtesvqtagrlladlitdsgyaa-sgfsyw-----------sn---rlvrpgv--------h---
----------rfseae-ts-aegadlq---kavdlfrlsddli----
>34_Prochlorococcus_marinus_str._MIT_9312_168
-----------------------------------------------------------------
-----------------------------------------------------------------
--------------------------ilitggnsgigffaivnllk--tkn-nlyiliksefrkn
dflirieky----------fe-kny---------lskylniiencdlsdlenikkikdyli--sk
nif------ld--vvilnaglqy-----t----gsfypkvskqgieltfavnhl---ahfylini
ikdfvs-nke-------------esriiitssdvh--------------dpkssggn--igkkag
lnnl--vdfr-----kk------vagrfln----fnadesyknsklcnilfakelakkfki----
------sss-kisvitwapglvipdddsgf-frysk-------cfnlfgyfifskvakni---lg
isesvenagkilseivfdssfnn-iayihl-----------sn---klisfkk--------h---
----------klvagk-vs-deansse---lasklwifseei-----
>39_>gi|82582335|sp|Q5F389.2|WWOX_CHICK_RecName__Full=WW_domain-containing_oxidoreductase_190
-----------------------------------------------------------------
-----------------------------------------------------------------
-------------------------viiitgansgigfetaksfal--hg-ayvilacrnmsrgn
davqrilee----------wh-ka--------------kveamtldlaslrsvqnfaeafk--sk
nmp------lh--ilvcnaaifg---s-s-------wc-ltedglestfqvnhl---ghfylvql
ledilr-rss-------------parvvvvssesh--------------rfteik-d--ssgkld
fsll--spsk---------------------ke-ywamlaynrsklcnilfsnelnrrl------
------sph-gvtsnsvhpgnmi---yssi-hrnww------------vytllftlarpf-----
-tksmqqgaattvycataaeleglggmyfn-----------nc---c------------------
--------------rclps-aearnel---tavalwelserli----
>94_Arabidopsis_thaliana_490
-----------------------------------------------------------------
-----------------------------------------------------------------
----------------------kdknilitggnsgigfyatinllk--akn-nlyipirsiprkd
qfffkllky----------fd-kky---------ldkylnlienidlanlrnieilrdyln--kk
nvs------fd--viilnaglqy-----t----gsfypkvskqgieltfavnhl---ahfylvns
liglin-nkk-------------esriiitssdvh--------------dpkssggn--vgkkag
lnnl--vnfk-----qe------itgkyln----fnsdkayknsklcnilfakelskrlqi----
------kay-evavitwapglvipnedlgf-frysk-------kfnffgyiifsiiakni---lg
isenvenagkllseivtdpefnn-ikylhl-----------sn---klvffkk--------h---
----------kllkse-is-eeanksd---lalrlwnlseel-----
