>1_Trichoplax_adhaerens_0
------------------iitggntgigketaidfakrga--rvila--crnetkgesaa
qdirqatgn-------d-------------n----vvfkhldlasfksirsfaedink--
-------------------neksldilvnnag--------------vace--rqltedgl
emimgvnhf---ghflltnlvld-kikes-kn-s----rivvvaswghs------lir--
--si---n-fddi--qne---k-------dfn--ylnvycqsklanvyftrelakrleg-
--hgilvntlhpgsvr-tei-f---------r-hmnpc---------tklvgypv-----
---almffksakqgaqttiqlavseeingmtglyfencr-----------pvqm------
------k---phalddea-akrlwklseemtgl-
>2_Oryza_sativa_Indica_Group_2
astadqvtaglsaagltaivtgassgigaetarvlairga--hvvma--vrnlaaaqpvr
dailadapa-------a-------------s----ldlmeldlasmdsvrafasdfaa--
-------------------kglplnilinnag----------v---matp--fslskdgi
elqfatnhv---ghfllthllle-tmkkt-sresnvegrivnvsseghr-----------
------------------------------yn--sigaygqsklanilhanelarrfkde
g-vnitanslhpgsii-tnl-l---------rhhsi-----------ldvlhrtl-----
---gklvlknaqqgaattcyvalhpqvkgvsgkyfsdsn-----------vnea------
------s---ekgndmel-akrlweysiel----
>3_Drosophila_pseudoobscura_pseudoobscura_12
------------------ivtggntglgretvrelarrga--tvyma--crdrdkgekar
keiaketkn-------s-------------n----vfsrecdlssldsvrnfvdgfkk--
-------------------eqdklhilinnag----------v---fwep--rsltkegf
emhlgvnhi---ghfllthllld-llkqs-ap-s----rivvvsskahe-------rg--
--ri---q-vddi--nsk---q-------syd--egtaycqsklanilftrelarrleg-
--tavtvnalnpgiad-tei-a---------r-nmiff-----rtklaqtilrpl-----
---lwslmksprngaqttlfaaldsdldhvsgqyfsdcr-----------pkel------
------a---paakdddm-arwlwsqsekwtgi-
>4_Oryza_sativa_Indica_Group_20
------------------iqsggasgigletsrvfalrga--hviia--arnteaasvvr
kkiieenpk-------a-------------h----idvlkldlsslksvrafadqfns--
-------------------mnlplnilinnag----------v---mfcp--fglsedgv
emqfatnhl---ghflltnllld-nmkat-akstgiegrivnlssvahl-------hty-
pkgi---e-fdkl--nde---k-------tyd--dkmaygqsklanilhakelsrrlkeg
g-anitincvhpglim-tnl-m---------rhsff-----------lmrvlqfa-----
---tyilwksvpqgaattcyvglnpqlkgvtgqyfadcn-----------vekt------
------s---rfarndal-akqlwefsekl----
>5_Zea_mays_32
-------------------itggasgigletsrvfalrga--hvvia--arnteaasear
ktimeknpt-------a-------------r----idvlkldlsslksvrafvdqfns--
-------------------mklplnilinnag----------v---mfcp--fqlskdgv
emqfatnhl---ghflltnllld-tmkat-akstgiegrivnlssvahh-------hty-
pkgi---d-fdnl--nde---k-------iyn--dkmaygqsklanllhakelsrrlkee
g-anitvnsvhpglim-tnl-m---------rhsfv-----------lmkvlqva-----
---tyilwknvpqgaattcyvglspqlkgvtgkyfadcn-----------vekt------
------s---klarseel-akqlwdfseel----
>6_Oryza_sativa_Indica_Group_40
------------------vvtgatngigketarvlalrga--evilp--artlesgmkvk
qslaeeips-------s-------------k----lhvmemdlssldsvrsfaksfns--
-------------------syrhlnvlinnag----------v---mscp--fglskdgi
elqfatnhv---ghflltnllld-kmkat-aketglqgriinvssishr------gsd--
gscf---d-ldkl--ndk---s-------kyr--pfkayghsklanilhanelsrrfqee
g-cnltanslhpgvia-tnl-p---------rhiltns---------liisifsv-----
---mkpflksipqgaatscylalhpglkdvsgkyfadcn-----------eatp------
------t---avardael-akklwefseelt---
>7_Medicago_truncatula_42
------------------iitggasgiglettrvlalrkv--hviia--arniesaeeak
qqitqenks-------a-------------r----vdimkldlcstksvrsfvdnfia--
-------------------ldlplnilinnag----------i---mfcp--fkiseegi
emqfatnhl---ghflltnllld-kmkqt-akttgiegriinlssiahr-------ytyf
rkgi---k-feki--ndk---k-------ghs--skkaygqsklanilhanelsrrlqee
g-vnitvnsvhpgvim-tpl-m---------ryssy-----------tmhllkif-----
---sfyiwknvpqgaattcyvalhpsvkgvtgkyfvdcn-----------efkp------
------s---ayaknkll-akklwdfsnkl----
>8_Drosophila_mojavensis_48
------------------iitgansgigketakdlagrga--riima--crnletanavk
deivketnn-------n-------------k----vvvkkldlgsqksvrefaadivk--
-------------------tepkidvlihnag--------------malafrgqtsedgi
eltmatnhy---gpfllthllid-vlkks-ap-s----rivivaselyr-------la--
--sv---n-vnkl--npi---g-------tfp--aaylyyvskfaniyfarelakrleg-
--tnvtvnflhpgmid-sgi-w---------r-nvpfp---------lnipmmai-----
---tkgffkttkagaqttiylatsdevanvsgkyfmdck-----------eatl------
------n---aaamdmek-arqiweesvkivkl-
>9_Zea_mays_54
-------------------itggasgigletsrvfalrga--hvvia--arnteaasear
ktimeknpt-------a-------------r----idvlkldlsslksvrafvdqfns--
-------------------mklplnilinnag----------v---mfcp--fqlskngv
emqfatnhl---gyflltnllld-tmkat-akstgiegrivnlssvahh-------hty-
pkgi---d-fdnl--nde---k-------iyn--dkmaygqsklanllhakelsrrlkee
g-anitvnsvhpglim-tnl-m---------rhsfv-----------lmkvlqva-----
---tyilwknvpqgaattcyvglspqlkgvtgkyfadcn-----------vekt------
------s---klarseel-akqlwdfseel----
>10_Psychroflexus_torquis_ATCC_700755_56
------------------vitgatsglgkqatkvlaskna--kvila--vrntqkaedvv
meirkdfpn--a----k------------------leirhldlgklksvqtfaeefts--
-------------------dysqldvlinnag----------i---mmcp--ysktedgf
eiqmgtnhf---ghfaltgllipllletk-ds------rvvatssiahk-------sg--
--si---n-fddi--nwe---s------rkys--tikaysdsklanlyftyelvrkykgn
p-naplftvahpggtn-tdl-g-------------------------rhmsitrll----
---aplfgqnvetgtlpslraatdlnats--gdyfgpks-ffesrgypvivqp-------
------n---kmaqneen-akrlweiseqltgv-
>11_Oryza_sativa_Japonica_Group_58
------------------vvtgatngigketarvlalrga--evilp--artlesgmkvk
qslaeeips-------s-------------k----lhvmemdlssldsvrsfaksfns--
-------------------syrhlnvlinnag----------v---mscp--fglskdgi
elqfatnhv---ghflltnllld-kmkat-aketglqgriinvssishr------gsd--
gscf---d-ldkl--ndk---s-------kyr--pfkayghsklanilhanelsrrfqee
g-cnltanslhpgvia-tnl-p---------rhiltns---------liisifsv-----
---mkpflksipqgaatncylalhpglkdvsgkyfadcn-----------eatp------
------t---avardael-akklwefseelt---
>12_Populus_trichocarpa_64
----------------taivtgassgigtetarvlalrgv--hvimg--vrnmaagrdvk
eaivkeips-------a-------------k----vdameldlsslasvrnfasdfns--
-------------------sghplnllinnag----------i---mapp--fmlskdnm
elqfatnyl---ghfllanllld-tmkkt-alesnregriinvssefhr-------ypy-
pegi---r-fdki--ndq---s-------gyk--kfqaygqsklanvlhanelmrrfked
g-vnitanslhpgvia-tnl-f---------rhntsla-----ddnpirvflesa-----
---arlvlknvqqgaattcyvalnpqvkgasgeyfsgcn-----------ltka------
------s---smakdael-akklwdfsmnlv---
>13_Brassica_napus_68
----------------taiitggtsgigleaarvlgmrga--hviia--srntkaandsk
emilqmypn-------a-------------r----idclqldlssiksvrsfihqfla--
-------------------lnvplnilinnag----------v---mfcp--fqlsedgi
esqfatnhi---ghflltnllld-kmkss-aresgiegrivnlssiaht-------yty-
tegi---m-fdyi--ndp---d-------rys--ekkaygqsklanllhsnalsrklqee
g-vnitinsvhpglit-tnl-f---------rhsgl-----------gmavlkam-----
---sfflwknipqgaattcyvalhpdlkdvtgkyfadcn-----------vttp------
------s---nfatdttl-adklwdfsiklv---
>14_Arabidopsis_thaliana_78
----------------taiitggtsgigleaarvlamrga--hviia--arnpkaanesk
emilqmnpn-------a-------------r----vdylqidvssiksvrsfvdqfla--
-------------------lnvplnilinnag----------v---mfcp--fkltedgi
esqfatnhi---ghflltnllld-kmkst-aresgvqgrivnlssiaht-------yty-
segi---k-fqgi--ndp---a-------gys--erraygqsklsnllhsnalsrrlqee
g-vnitinsvhpglvt-tnl-f---------rysgf-----------smkvfram-----
---tflfwknipqgaattcyvalhpdlegvtgkyfgdcn-----------ivap------
------s---kfatnnsl-adklwdfsvfli---
>15_Vitis_vinifera_98
----------------tavvtgassgigtetsrvlalhgv--hvima--vrnvdagrnvk
etilkeipt-------a-------------k----vdvmeldlsslpsvrkfaseyks--
-------------------lglplnllinnag----------v---matp--fllshdni
elqfatnhl---ghflltnllle-tmknt-aresgregrivnvsseghr-------fpy-
segi---c-fdki--nde---s-------ayn--svyaygqsklanilhanelakrlqee
g-veitanslhpgaia-tnl-l---------ryhsf-----------ldgivnmv-----
---gkyvlknipqgaattcyvalhpqvkgvsgeyfadsn-----------iakp------
------s---skgkdael-gkklwefsisl----
>16_Pediculus_humanus_corporis_100
------------------litgsnsgigketarelakrna--cvima--crdlnnanlai
ndirkttts-------g-------------e----lvpmhldlasfasikdfsekale--
-------------------kfpkidvlinnag----------v---yfplsqsqktkdgf
emnfginhl---ghflltqllie-rikds-ap-s----rivivsstlhe-------sg--
--vl---d-lndl--nmt---k-nmdsvkklr--nnpaycasklanmyhsrelasrlkn-
--tgvdvyavcpgfty-tgl-f---------rysdikw--------wqyimfmpi-----
---allflrtswqgaqtvllcacdkslkgvsgnfyrnck-----------eyk-------
------s---ktnfdpki-qsalwekseelvnl-
>17_Ricinus_communis_102
----------------taivtgassgigvetarvlalrdv--hvvma--vrnvdagrnvk
esilkeipt-------a-------------k----idvmqfdlssmasvrkfaseyis--
-------------------sglplnllinnag----------v---matp--fmlsqdni
erqfatnhv---ghflltdllle-tmknt-aressregrivnvssaghr-------fty-
regi---r-fdkl--nde---a-------gyn--silaygqsklanilhagelarrlked
g-vdisvnslhpgaid-tnl-l---------ryhsv-----------ingivslv-----
---akyviknvqqgaattcyvalhpqvkgvtgeyfsdsn-----------iatp------
------t---sqakdadl-akrlwdfsvrl----
>18_Ixodes_scapularis_104
----------------tviitgsntgigketarelarrna--rvila--crnqdkardaa
edifkttgr-------h------------------vvcmqldlcsfdsvrnfankvia--
-------------------seerldvlinnag--------------mmce-wgrltkdgf
evtfqanhl---ghfllthlllg----ks-qp-s----rivvvgsvgqt-------lg--
--rl---d-indl--sfg---e-------ywf--pllnycttkqcnmlftvelsrrlqg-
--tgvtvncchpgyvr-sdian---------rsedm-----------qtwlfnrl-----
---ldaygknvkqgsettvylavsedvetisgkyfsdck-----------ksfa------
------v---pwatdrik-akqlweeslkm----
>19_Xenopus_tropicalis_106
----------------tvivtganvgigkmtaldmakrga--rvila--crvketgeaaa
ydirklsgn-------n-------------q----vvfmkldlaslesvrsfcrafls--
-------------------seprldilinnag----------l---sgfg----ktaegy
nivfgvnhl---ghflltsllld-rlkqs-tp-s----rivvlasyahe-------wg--
--ki---d-fnki--sv--------psehvkd--tlqsycdsklcnvlfarelanrlqg-
--tsvtcysvhpgtvh-tnl-a---------r-slpsw---------ikvliepv-----
---swlflrtpmngaqtsiycavqegiemysgryfdncq-----------vrqv------
------k---pharddav-akklwevsermtgla
>20_Nasonia_vitripennis_110
----------------tvlitgctsgigretardlakrga--riima--crnveaasklk
delvketgn-------t-------------q----lvvrkldlssldsvrdfanqvnr--
-------------------eesrldvlihnag--------------taetfnkkvsddgl
emtmatnhy---gpfllthllid-llkks-tp-s----rivivaselyr-------ia--
--tl---n-lnnp--npt---a-------tlp---aylyyvskyanivftlelarrleg-
--sgvtvnclhpgmid-sgi-w---------r-svpap---------lswglqli-----
---ikgffktpeqgaqttihlavsdelegvngkyyldck-----------essl------
------s---sgvsdpak-gkkfweisetlakl-
>21_Zea_mays_114
----------------taivtgassgigaetartlalrga--hvima--vrslpaaqavk
davlaqapg-------a-------------k----ldvmeldlssmasvrafasqfid--
-------------------rglplnilinnag----------v---maip--falskdgi
emqfatnhv---ghfllthllld-tmkrt-shesnlegrivnvsseghr-------lay-
regi---r-fdki--nde---s-------vys--sigaygqsklanilhanelarrfeed
n-vnitanslhpgsii-tnl-l---------ryhsi------------------------
------------------------------------------------------------
----------------------------------
>22_Capsella_rubella_116
----------------taivtgassgigvetarvlalrgv--hvvma--vrntgsgakvk
enivnqvpg-------a-------------k----ldvmeldlsslesvrkfaseyks--
-------------------aglplnllinnag----------i---macp--fmlskdni
elqfatnhl---ghflltkllld-tmknt-sreskregrivnlsseahr-------fsy-
pggv---r-fdki--ndk---s-------sys--smraygqsklcnvlhanelakqlkdd
g-vnitanslhpgai---------------------------------------------
------------------------------------------------------------
----------------------------------
>23_Aedes_aegypti_122
----------------tvivtgansgigketardlakrga--rvima--crnmetaakar
deivketgn-------n-------------n----vflkkldlssqasirefatdvlk--
-------------------tetkldvlihnag--------------faetfkksksvdgi
eftmatnhy---gpfllthllid-llkrs-ap-s----rivivaselyr-------fa--
--sv---d-lnnl--npv-----------nsl--pgylyyvskcanimftrelarrleg-
--tnvtanclhpgmid-sgi-w---------r-nvpfp---------ltipmavm-----
----kaffktnvegaqtslhlacssevegisgkyfrdck-----------eagl------
------t---agisdmek-akklweesvkmvkl-
>24_Ricinus_communis_128
----------------taiitgassgigaetarvlalrgv--hvima--vrnvkagttvk
eeilenipt-------a-------------k----idvmeldlsvissvrnfaseyis--
-------------------lglplnilinnag----------i---stsk--qmlskdni
einfainhl---ghflltnllle-tmknt-aggsniqgriiivsslghl-------far-
--di---p-fdel--nki---s-------shn--ssmgyprsklanvlhanelakrfkee
g-vditanslhpglif-tni-l---------rhnaf-----------hrvifgla-----
---nkfllknvqqgaatscyvalnpqvkgvngqyfvdcn-----------igkp------
------n---slvedeel-akklwdyslsli---
>25_Nostoc_punctiforme_PCC_73102_130
------------------ivtgsssgigyetarvlankqa--sviia--vrnldkgnkal
akilqqnkd--a----d------------------vkvmeldlanlasvknfaenfqk--
-------------------nyvrldllinnag----------v---mipp--yskttdgf
elqfgtnhl---ghfaltgqllerlidte-ds------rivnvssgahs-------ig--
--ki---d-fddl--nwe---k------rsya--kwkaygdsklanlyftyeldrklkdk
g-idtlvtashpgwta-tel-q---------r---------------taggvvkyl----
---ngilaqditmgalptlraateaglkg--aeyfgpng-fmemrgypikves-------
------n---elskdqai-akklwevsekltnv-
>26_Ostreococcus_tauri_134
--------------ravaivtganaglgretaralvkkgy--avvla--trdvergeraa
aevraaaag--agaggt------------------aeamradladfesirrfarafea--
-------------------kyerldalvcnag----------v---malp-nrettvdgn
etqmqvnhl---ghflltslllptmlktp-sndk----rivnvssvahn-------fg--
--tl---d-fhni--nsegffg------ypfl--gwatygrtkmanvlftfelhrrlras
giddvcvnavhpgvvd-tel-n---------r---------------n------------
------------------------------------------------------------
----------------------------------
>27_Tetraodon_nigroviridis_138
----------------taivtgssggigkatalglaqrga--rvvla--crsqekgeaaa
fdirqesgn-------n-------------q----vvfmhldlsslksvrrfaqtflq--
-------------------teprldilvnnag----------v---mspg----rtedgf
gmalgvnhl---ghflltnllle-rlrrc-gp-s----rvvtvaallhr-------lg--
--rv---d-fall--asr---kdlvpgestws--sfraycssklcnvlfsrelanrleg-
--tavtcyslhpglvy-sdl-g---------r-slsvw---------lqllllpl-----
---aklffadaeggsqtvlhcalregieplsgryfssca-----------lqqv------
------g---apgrddav-akklwevserltgls
>28_Gossypium_hirsutum_144
------------------ivtgassgigvettrvlalrgv--hvvma--vrnadagrnvk
esilkeips-------a-------------k----idvmeldlssmasvrkfasqyqs--
-------------------snlplnllinnag----------v---matp--fmlsqdki
elqfatnhl---ghflltdllle-tmkrt-aresniegrivnvsseghr-------iay-
regi---r-fdki--nde---s-------gyy--twyaygqsklanilhakelaqrlkee
e-veitanslhpgaiistnl-m---------rhhgl-----------intvgqml-----
---gkyflknipqgaattcyvalnpqvkgvsgeyfldsn-----------ignp------
------s---akakdadl-akklwdfs-------
>29_Mycobacterium_abscessus_148
----------------tviitgansglgletarelarvga--hvima--vrntekgnaaq
asikgs-----------------------------tevrqvdvadlasvrafadtveg--
-----------------------adilvnnag----------i---mmvp--paktvdgf
esqigtnhl---gafaltnlllpkltd-----------rviavssvahr-------ag--
--ki---d-ltdl--nye---r------rryt--ragaygasklanllftkelqrrlsaa
g-spvraltvhpgvaa-telqs---------h---------------sgnpifelalkt-
---gnlfaqnaahgalptlyaa-sqdlpg--dtyigpdg-pfeakgyptrvgr-------
------s---graqdtet-akglwrlseqltgvs
>30_Trichoplax_adhaerens_154
---------kaklhhktviitggntgigkataidlaqrga--rvila--crseskgkeav
ediiqqsgn-------s-------------e----vifcpldlaslqsvrdfadyvne--
-------------------kedrvdillnnag----------i---mmcp--ysktqdgf
emqigtnhf---ghflltnllld-klktc-ap-s----riinvsslaht-------mg--
--ki---n-fddi--nse---k-------gyg--svaaysqsklanvlftrelakrlqg-
--tavtanslhpgavd-tel-q---------r-hfsvr-----kfsflnslitpl-----
---iwlgfktpkqgaqtsifcavdeslegvsgkyfsdcr-----------ektc------
------a---kqaydddv-akrlwhlseeltgls
>31_Pisum_sativum_158
----------------taivtgassgigaettrvlalrga--hvimg--vrnmvaakdvk
dtilkdips-------a-------------k----vdaieldlssldsvkkfasefns--
-------------------sgrplnilinnag----------i---macp--fklskdni
elqfatnhi---ghflltnllld-tmkkt-treskkegrivnvaseahr-------fay-
pegi---r-fdki--ndq---s-------syn--nwraygqsklanvlhanqltkhlked
g-vnitanslhpgtiv-tnl-f---------rhnsa-----------vnglinvi-----
---gklvlknvqqgaattcyvalhpqvkgvsgeyfsdsn-----------vykt------
------t---phgkdvdl-akklwdfsinlv---
>32_Vitis_vinifera_162
----------------taivtgassgigtettrvlalrgv--hvvmg--vrnmsagkevk
eaivkeipt-------a-------------k----vdameldlssmasvrkfaseyns--
-------------------sglplnilinnag----------i---mavp--ymlskdni
emqfatnhl---ghflltnllld-tmkkt-trksrkegrivnvssmahr-------ypy-
regi---r-fdki--ndk---s-------gys--slfaygqsklanvlhanelarrfked
g-vditanslhpgaiv-tnl-f---------rcssi-----------vsglvntv-----
---gklvlknvqqgaattcyvalhpqvkgvsgqyfsdcn-----------iakp------
------s---sqakdpel-akklwefsmnlv---
>33_Ricinus_communis_164
----------------taiitgatsgigvetarvlakrgv--rvvip--ardlkkaaeak
etiqkespk-------a-------------e----ilifetdlssfasvkkfysdfla--
-------------------lglplnilinnag----------i---fsqn--lefsedki
emtfatnyl---ghflltellle-kmiet-aagtgiqgriinlssvihs------wvk--
rdsf---s-fnqm--irp---k-------nyn--gtrayaqsklatilhakemarqlkar
n-arvtinavhpgivk-tgi-i---------rahkg----------yitdslyfi-----
---askllkstsqgasttcyvalspqaegatgkyfadcn-----------esnc------
------s---alandese-ahklwklsralih--
>34_Prochlorococcus_marinus_str._MIT_9312_168
-----------------ilitggnsgigffaivnllktkn--nlyil--iksefrkndfl
iriekyfeknylskyln-------------------iiencdlsdlenikkikdylis--
-------------------knifldvvilnag----------lq--ytgsfypkvskqgi
eltfavnhl---ahfyliniikdfvsnke-es------riiitssdvhdpkssggnigk-
kagl---nnlvdfrkkvagrfl-------nfn--adesyknsklcnilfakelakkfkis
s-skisvitwapglvipdddsg---------ffrysk----------cfnlfgyfifskv
aknilgisesvenagkilseivfdssfnniayihlsnkl--isfkkhklvagkv------
------s---deanssel-asklwifseei----
>35_Populus_trichocarpa_170
----------------taiitgatsgigvetaralakkgm--rivip--ardlkkaagvk
eaiqkespn-------a-------------e----iiifetdmssfvsvkrfcsgfla--
-------------------lglplnilinnag----------i---ysqk--lefsedki
emtfatnyl---ghylmtellle-kmiet-aeqtgiqgriinlssvihs------wvk--
rdaf---c-lqkm--lsp---k-------syd--gtraysqsklanilhvkeiarqlrar
n-arvtinavhpgivk-tgi-l---------rasykgf---------ltdslyfi-----
---askllkstsqgasttcyvalsqqiegvsgkyfadcn-----------eskc------
------s---tlandese-aqklwmqthalm---
>36_Picea_sitchensis_174
----------------taiitgatsgigaetarvlakrga--rliip--arnlkaaedvk
sriqkeipt-------a-------------e----iivmeldlssfasirrfatnfns--
-------------------cdlplnilinnag----------k---fche--fqvsqdgf
emtlatnhl---ghflltrllln-kmiet-anetgiqgrivnvssgihs------wmg--
reri---q-fdql--ndp---k-------syd--atrayaqsklanilhtkelslrlekm
k-anvtansihpgivr-tri-t---------rdrdg----------litdlvffl-----
---askllksipqaasttcyvavhpnlksisgkyfadcn-----------easa------
------s---svandpnk-amelwrdsdaiv---
>37_Mus_musculus_182
----------------tvlitgansglgrataaellrlga--rvimg--crdraraeeaa
gqlrqelcq-------aggagpd---gtdgq----lvvkeldlaslrsvrafcqkllq--
-------------------eeprldvlinnag----------v---fhcp--ytktedgf
emqfgvnhl---ghflltnlllg-llkss-ap-s----rivvvssklyk-------yg--
--ei---n-fedl--nse---q-------syn--ksfcysrsklanilftrelarrleg-
--tnvtvnvlhpgivr-tnl-g---------r-hihip-------llarplfnlv-----
---swaffktplegaqtsiylacspdvegvsgryfgdck-----------eeel------
------l---pkamdesv-arklwdisevmv---
>38_Danio_rerio_186
----------------tvivtgantgigkatamdlarrga--rvila--crdegraqaav
tdiqretgs-------k-------------e----vlymhldlaslksvrsfaenflk--
-------------------kesrldilinnag----------l---vigg----ktedgf
grmfgvnhl---ghflltdlllk-rlkec-gp-s----rivtvssmaha-------wg--
--km---d-fnci--naq---kdlgkgnsalg--llmlyshsklcnvlfthelakrlkg-
--tnvtcyslhpgaik-tel-s---------r-hsniw---------wslfmapi-----
---fllffkdvvsgaqtslhcalqegieplsgryfsgca-----------vqnv------
------s---akarddaa-akklweiserfvgla
>39_'>gi|82582335|sp|Q5F389.2|WWOX_CHICK_RecName__Full=WW_domain-containing_oxidoreductase_190'
----------------viiitgansgigfetaksfalhga--yvila--crnmsrgndav
qrileewh--------k------------ak----veamtldlaslrsvqnfaeafks--
-------------------knmplhilvcnaa----------i---fgss--wcltedgl
estfqvnhl---ghfylvqlled-ilrrs-sp-a----rvvvvsseshr-------ft--
--eik-ds-sgkl--dfs---llsp-skkeyw--amlaynrsklcnilfsnelnrrlsp-
--hgvtsnsvhpgnmiyssi-h---------rnww------------vytllftl-----
---arpftksmqqgaattvycataaeleglggmyfnncc-----------rclp------
------s---aearnelt-avalwelserli---
>40_Homo_sapiens_204
----------------vvvvtgansgigfetaksfalhga--hvila--crnmaraseav
srileewh--------k------------ak----vetmtldlallrsvqhfaeafka--
-------------------knvplhvlvcnaa----------t---falp--wsltkdgl
ettfqvnhl---ghfylvqllqd-vlcrs-ap-a----rvivvsseshr-------ft--
--din-ds-lgkl--dfs---rlsp-tkndyw--amlaynrsklcnilfsnelhrrlsp-
--rgvtsnavhpgnmmysni-h---------rsww------------vytllftl-----
---arpftksmqqg----------------------------------------------
----------------------------------
>41_Pan_troglodytes_208
----------------vvvvtgansgigfetaksfalhga--hvila--crnmaraseav
srilgewh--------k------------ak----veamtldlallrsvqhfaeafka--
-------------------knvplhvlvcnaa----------t---falp--wsltkdgl
ettfqvnhl---ghfylvqllqd-vlcrs-ap-a----rvivvsseshr-------ft--
--din-ds-lgkl--dfs---rlsp-tkndyw--amlaynrsklcnilfsnelhrrlsp-
--rgvtsnavhpgnmmysni-h---------rsww------------vytllftl-----
---arpftk---------------------------------------------------
----------------------------------
>42_Homo_sapiens_210
----------------vvvvtgansgigfetaksfalhga--hvila--crnmaraseav
srileewh--------k------------ak----vetmtldlallrsvqhfaeafka--
-------------------knvplhvlvcnaa----------t---falp--wsltkdgl
ettfqvnhl---ghfylvqllqd-vlcrs-ap-a----rvivvsseshr-------ft--
--din-ds-lgkl--dfs---rlsp-tkndyw--amlaynrsklcnilfsnelhrrlsp-
--rgvtsnavhpgnmmysni-h---------rsww------------vytllftl-----
---arpftk---------------------------------------------------
----------------------------------
>43_Trichoplax_adhaerens_216
------------------iitgantgigketaadfarrgg--rvila--crskakgeiaa
eeirhatgn-------d-------------n----vvfkclnlasfqsirsfaedink--
-------------------neksldilvnnag--------------lvve--rqltedgl
emimgvnhf---ghflltnllln-kmkes-kn-a----rivvvasygys------fvr--
--sl---d-fddi--qne---k-------nfs--afnvycqsklanvyftrelakrles-
--dgilvnclhpggvm-tdi-w---------r-dmnkc---------lkafaypf-----
---almlfktpkegaqttihlavsedidglsghyfedcr-----------pvkm------
------k---phalddea-akrlwdvseeltgls
>44_Tribolium_castaneum_224
------------ldnkvvvitgansgigfevakelasrna--mvvla--crkldsakeai
erieqelkk-------k------------lk----mramevdlasllsikqfasnvqk--
-------------------lypevhilvnnag----------v---aypknekhltkdgf
eihfginhl---ghfyltnllld-klkks-tp-s----riiivtsslhe-------kg--
--ti---d-lknl--esg---k--------------nlyansklanayfckelskrvkd-
--tgvsvygvcpgwvy-tal-f---------rhsirwy---------hyimvapi-----
---ayffmrspkqgaqtviycasepglepesgslfrncs-----------lyks------
----------kvnfdenl-glhlwneserli---
>45_Trichoplax_adhaerens_228
----------rnlsggialitgatsgigfetaralalhga--lvimg--chdivkgsiaa
kkitkeep--------l------------ak----idvievdlsslksiacladevlk--
-------------------kyrqlhviicnag----------v---lglp--wrlttdel
eytftvnyi---ghfylvkllte-lliss-sp-a----rvvvisseshr-------fp--
--tt---d-gssf--nve---nilp-skqqfi--pmeaynqsklcgilfsnefnrkysc-
--ygvtsnavhpgnllptsl-c---------rnsw------------fytilfll-----
---arpfakstvqgaatttfcaaarelngvggsyfnncq-----------rcdp------
------s---pesqneel-aralwkytesll---
>46_Strongylocentrotus_purpuratus_238
----------------tvivtgantgigketardlarrga--rvila--crdavrgreae
kdirmstgn-------d-------------d----vifmklnlasfdsirhfaqefnn--
-------------------teerldilvnnag----------v---indg--slrteegh
elvfgvnhl---ghflltnilld-klqkc-ap-s----rvinvssdaym-------fg--
--kl---d-lerl--svn---d---------g--rvksyarsklanvlftrqladkmag-
--tgvvsfslhpgsvn-tei-k---------r-nwagw---------lralapli-----
---sffflksvkagaqtsihcavsddildqsgeffkgcq-----------vqkl------
------s---rtaqdqdl-aqrlwdvslemtgl-
>47_Strongylocentrotus_purpuratus_240
------------------------------------kddy--evima--crsedkanqav
sevqkkvpg-------a-------------k----vsfmkldlnslksvrefsdafha--
-------------------tgkplhvlcnnag--------ltt---gfstkdrletedgf
emtfgvnhl---ghfllthllld-vmkkt-ae-tceevrivntssmlhdpegpggnrgr-
aahl---d-fdnlmmdkp---d-------tfd--gmlayrnsklancafsvelakrleg-
--skitsntlcpgfipatgl-g---------rnetqwaki-------rmavitpllk---
---ligitrtvehgggmvhyvvtspdwkgltgkhstdfk-----------itds------
------s---tesrdpev-gkklwdmsadlv---
>48_Branchiostoma_floridae_242
-------------egktvivtgansgigketakelskrgg--rvima--crnmnkcqear
dqlvqetgn-------e-------------n----vhcqqvdlasfesirkfasrink--
-------------------sepkvdvlinnag----------v---mrcp--hwktadgn
ewqfqvnyl---shflltnllmd-klkaa-eq-g----riintssiaha-------qg--
--ni---n-fddi--nsl---l-------kye--dveaymqsklalvlftlelskrleg-
--tsvtantvypgvtk-tni-g---------qhrltka---------qsimtkpl-----
---mwftlrepkraaqtgvylsvapevadktgkywkdtv-----------ahdp------
------a---ppgrdedv-akklwdlslemtgl-
>49_Xenopus_laevis_252
----------------tvivtganigigkmtaldmarrga--rvila--crvketgeaaa
ydirqlsgn-------n-------------q----vlfmnlnlsslesvrsfcrafls--
-------------------seprldilinnag----------f---sgpg----ktaegy
nivfginhl---ghflltsllld-rlkqs-tp-s----rivalasyahe-------wg--
--ki---d-fnki--sv--------psdhikd--ilqsycdsklcnvlfarelanrleg-
--tgvtcysvhpgtvh-tnl-v---------r-slpnw---------ikacikpf-----
---twlflrtpmdgaqtsiycavqegiemytgryfdncq-----------vrqv------
------k---pharddav-akklwevsermtgla
>50_Populus_trichocarpa_256
----------------taivtgassgigaettrvlalrgv--hvvma--vrnldagrngk
eamlkeipk-------a-------------e----idvmeldlssmtsvrnfaseyts--
-------------------lglplnilinnag----------v---lssp--sklsqdni
ellfatnhigiwghflltnllle-imknt-aqkskqegriinvssvghr-------ivt-
regi---c-fdki--yne---a------------swfsygqsklanilhaselarrlkee
g-eeitanslhpgaih-tnl-l---------rhqgf-----------vnaifslf-----
---gkymtknvqqgaattcyialhpqvkgmsgnyfmdsn-----------iaep------
------s---sqakdael-akklwdfs-------
>51_Oryza_sativa_Indica_Group_264
------------------vvtgassgiglettrvlalrgv--rvvma--vrnvaaghkar
eairaeihg-------a-------------i----vhvlemdlssmdsvrrfasefds--
-------------------lnlplnilinnag----------i---lskd--cirsidgl
elhfatnhi---ghflltnllle-nmkst-srttgvegriinvsssghi-------lty-
pegi---c-fdsv--kdl---s-------rfs--tyiaygqsklanilhstelarilkgd
g-vnisanaihpgfvg-tnl-f---------knwtm-----------anavvnti-----
---grivcktveqgaattcyvalhpqvtgisgkyfsncn-----------letp------
------s---sqasnael-akklwefssnivsaa
>52_Oryza_sativa_Japonica_Group_266
------------------vvtgassgiglettrvlalrgv--rvvma--vrnvaaghkar
eairaeihg-------a-------------i----vhvlemdlssmdsvrrfasefds--
-------------------lnlplnilinnag----------i---lskd--cirsidgl
elhfatnhi---ghflltnllle-nmkst-srttgvegriinvsssghi-------lty-
pegi---c-fdsv--kdl---s-------rfs--tyiaygqsklanilhstelarilkgd
g-vnisanaihpgfvg-tnl-f---------knwtm-----------anavvnti-----
---grivcktveqgaattcyvalhpqvtgisgkyfsncn-----------letp------
------s---sqasnael-akklwefssnivsaa
>53_Danio_rerio_268
----------------tvivtgsnvgigratavdlarrga--rvila--crsqvrgevav
alvkresgs-------q-------------n----vafmqldlaslksvrsfaetflk--
-------------------tekrldilinnag----------v---ykqg----ttedgf
glmfgvnhl---ghflltnllld-rlkec-ap-s----rivtvssimhk-------yg--
--tl---d-fdtl--rth---kefgvgetsrs--ifwiyahsklcnvlfthelakrlqg-
--tnvtcyslhpgavn-sdl-n---------r-nlskm---------trrlikpi-----
---ttlffkdveagaqtslycavqegieslsgryfsnca-----------vqkv------
------e---pkaqddav-akklwevsetlsgls
>54_Arabidopsis_thaliana_274
----------------taivtgassgigeettrvlalrgv--hvvma--vrntdsgnqvr
dkilkeipq-------a-------------k----idvmkldlssmasvrsfaseyqs--
-------------------ldlplnllinnag----------i---macp--fllssdni
elqfatnhl---ghflltnllle-rmkkt-asesnregrivivsseghr-------fay-
regv---q-fdki--nde---a-------ryn--tlqaygqsklgnilhatelarlfkeq
g-vnitanslhpgsim-tnl-l---------ryhsf-----------intignav-----
---gkyvlksipqgaattcyaalhpqakgvsgeylmdnn-----------isdp------
------n---sqgkdkdl-akklwefslrltg--
>55_Zea_mays_280
----------------taivtgatngigketarvlalrga--kviip--artlesglklk
esladevps-------s-------------k----vhvmemdlsclssvrdfarsfns--
-------------------shkhlnllinnag----------i---macp--yqlskdgi
elqfatnhv---ghflltsllld-kmkst-aaetgvqgriinvssvahk------rsd--
gtcf---e-lnkl--ndk---a-------ryq--pfiayahsklanvlhtnelsrrfqee
g-cnltanslhpgviv-tni-i---------ryvagns--------alisalspv-----
---anlvlksvprgaattcylalhpnvkgvsgkyfadcn-----------eatp------
------t---avardsel-akrlwsfseelvki-
>56_Danio_rerio_294
----------------taiitggntgigkataldlagrgm--rvila--crnqkkaeaai
ndikkatgs-------d-------------e----vlfmeldlgslksvrafaetflk--
-------------------sesrldllinnag----------l---vadg----rtedgf
giefgvnhl---ghflltcllld-rlkes-pa-a----rvitlssmayr-------wg--
--ri---d-fdsl--itt---kdlgsgryswq--ffqaycnsklcnvlfthelakrlkg-
--tsvtcysvhpgvvk-tel-s---------r-nvslw---------qkvfiepv-----
---arllfldpktgaqttlhcavqegiehfsgryfscca-----------veev------
------g---akakddav-arklwqiserlsgls
>57_Drosophila_ananassae_298
------------------ivtggntglgketamelarrga--tvyla--crnkekgekaq
leiikatgn-------s-------------n----vfarlcdlssmesirefvedfkk--
-------------------eqnklhilinnag----------v---fwep--rrvtkegf
ethlgvnhi---ghfllthllld-vlkks-ap-s----rivvvaskahe-------rg--
--qi---i-vedi--nse---e-------fyd--egvaycqsklanilfarelakqleg-
--sgvtvnslnpgiad-tei-a---------r-nmiff-----qtkfaqtllrpl-----
---lwammktpkngaqttlyvaldpelenisgqyfsdck-----------lapv------
------s---paalddqm-akwlwaktekwagig
>58_Salmo_salar_308
----------------tvivtggntgigkatalelarrga--rvima--crnqekaelai
sdikretgs-------t-------------d----vvymqldlgslqavrsftetflk--
-------------------tearldllinnag----------l---vadg----rtadgf
giefgvnhl---ghflltcllld-rlkeg-tg-g----rvvtlgsmayr-------wg--
--ni---d-fdal--itn---khlgtgryswq--ffhaycnsklcnvlfnhelakrlkg-
--tnvtcysvhpgvvk-tel-s---------r-ncslw---------qrfiiepi-----
---arllfldpesgaqttlhcalqegieplsgryffcca-----------pqdv------
------v---akgkddav-akklwevserlsgl-
>59_Alcanivorax_sp._DG881_312
----------------tilvtgansgigleavklfaanga--evila--crntakaeaav
eqvreqtpd--a----r------------------livmpldladlasvkafvvalke--
-------------------riskldillnnag----------l---mapp--lqrtqdgf
eiqfgtnhl---ghfaltgplldlleaap-ap------rivqisslahr-------sg--
--ki---m-wgnl--nae---k-------rys--rwpfycqsklanlifakdlhrrlrkr
g-sniqvmaahpgysa-thl-q---------d---------------tipggglf-----
---nkvmaqpaemgclpgvmaatsdevvs--ggyygpdgkilelrgypapafa-------
------r---kitdnegl-aqrlwdeserltgv-
>60_Ricinus_communis_316
----------------tavvtgatsgigtetarvlalrgv--hvimg--vrnivaagdvk
aaiikeipt-------a-------------k----vdamdldlssmasvrkfalnfns--
-------------------sglplnilinnag----------v---atgk--fmlskdnv
eqhfatnhl---ghflltnllle-tmkrt-arksgrvgriinvsseghr-------vsy-
hggi---r-fdni--ndp---s-------gys--ryfaycqsklanvlhanelarrlked
g-anvtanslhpgmip-tnl-f---------ssssils-----nsv-aaglfkml-----
---sgvvlknvqqgaattcyaalhpeverisgayfvnss-----------lgqa------
------s---smardvnl-akklwdfsmdii---
>61_Populus_trichocarpa_318
----------------taivtgassgigaetarvlalrgv--hvvmg--vrnleagravk
eaivkgnpn-------a-------------k----ldamdldlssmasvkkfaedfks--
-------------------lnlplnllinnag----------i---matp--fmlskdni
elqfatnhv---ghflltnllme-tirkt-arasrkegrivnvssrrhk-------fsy-
pegi---r-fakl--ndp---s-------gyn--slsaygqsklanilhanelarqlked
r-vevtansvhpglia-tnl-f---------rhysf-----------ltglvglv-----
---gkyviknvqqgaattcyvalhpkvkamsgqyfadss-----------iaka------
------s---lqandael-atklwdfsldlv---
>62_Prochlorococcus_marinus_str._MIT_9515_338
-----------------ilitggnsgigfyatinllkakn--nlyip--irsiprkdqff
fkllkyfdkkyldkyln-------------------lienidlanlrnieilrdylnk--
-------------------knvsfdviilnag----------lq--ytgsfypkvskqgi
eltfavnhl---ahfylvnsliglinnkk-es------riiitssdvhdpkssggnvgk-
kagl---nnlvnfkqeitgkyl-------nfn--sdkayknsklcnilfakelskrlqik
a-yevavitwapglvipnedlg---------ffrysk----------kfnffgyiifsii
aknilgisenvenagkllseivtdpefnnikylhlsnkl--vffkkhkllksei------
------s---eeanksdl-alrlwnlseel----
>63_Populus_trichocarpa_344
----------------taivtgassgigtettrvlalrca--hvvma--vrnvesgrkvk
eeilkefpt-------a-------------k----idvmhldlnsmesvrkfasefis--
-------------------lglplnllinnag----------i---maap--fmlsqdni
emqfatnhv---ghflltdlvld-tmkkt-alesdregrivivsseahr-------fay-
segi---r-fdki--nde---s-------gyn--siwaygqsklanvlhaneltrrlkee
g-vnitanslhpgsim-tnl-l---------rfhsv-----------insvvtmv-----
---grfalknvqqgaattcyvalhpqvkgvsgeyfmdsn-----------lska------
------s---slakdeel-akklwdfslsl----
>64_Homo_sapiens_352
----------------tvlitggasgiglettrvlalhka--hviia--arnmvaaneak
qlilkeded-------a-------------r----vdvlkldlssiksirefadnlns--
-------------------ldlplnilinnag----------i---mfcp--yqlsedgi
emqfatnhl---ghflltnllld-kmket-arttgvegrivnlssvahi-------hty-
kdgi---r-fnni--ndk---k-------rys--dkraygqsklanilhakelsrrfqee
g-vnitanavhpglim-tnl-f---------khsai-----------lmrtlkff-----
---sfflwknvpqgaattcyvalhpslkgvtgkyyvdcn-----------slgp------
------s---afardeal-arklwdfsnkli---
>65_Arabidopsis_thaliana_364
----------------tvivtgantgigkqtalelakrgg--niila--crdmekceaaa
keirgetln-------h-------------r----vnarhldlaslksirefaakvte--
-------------------eeehvhilinnaa----------v---mrcp--hwttedgf
emqlgvnyl---ghflltnllld-klkas-ap-s----riinvsslahv-------ag--
--hi---d-fedl--nwek--r-------kyd--tkaaycqsklavvvstkelsrrlqg-
--tgvtvnalhpgvar-tel-g---------r-htgmh-----ssafssftlgpi-----
---fwllvkspelaaqpsvylavaeelegvsgkyfdvlk-----------ekpp------
------a---peaedeev-akrlwaesvrlvgl-
>66_Canis_familiaris_368
---------laslrgrtavvtgansgigkmtalelarrga--rvvla--crsrergeaaa
fdlrqesgn-------n-------------e----vifmaldlaslasvrafatafls--
-------------------seprldilihnag----------i---sscg----rtrepf
nlllrvnhi---gpfllthlllp-rlkts-ap-s----rvvvvssaahr-------rg--
--rl---d-ftrl--dh--------pvvgwqq--elrayansklanvlfarelatqleg-
--tgvtcyaahpgpvn-selfl---------r-hvpgw---------lrpllrpl-----
---awlvlraprggaqtplycalqegieplsgryfanch-----------veev------
------p---paarddra-ahrlweasrklagl-
>67_Arabidopsis_thaliana_374
-----------------viitgansgigketakelalrga--kvima--crnidvankvk
deivketkn-------d-------------n----vivkkldlsslssvrsfaedink--
-------------------tegkldvlihnag--------------vaytfekvvtkdgl
dmtmatnhf---gpfllthllid-llkks-kp-s----rivvvaselyv-------faf-
--nf---n-vnml--npv---r-------fwf--paylyyyskfanilfalelsrklen-
--tgvtvnclhpgmid-sgi-w---------r-nvpfp---------lnlfllpl-----
---tkvlfktpqegcqttvncavapelanvtgkyfmnck-----------erel------
------a---gfvkdcak-akkvwelseefvkl-
>68_Arabidopsis_thaliana_376
----------------taiitggtsgigaetarvlakrgv--rvvma--vrdmkkaemvk
eriirenpe-------a-------------d----iilfeidlsslssvarfcsqfls--
-------------------qdlplnilinnag----------v---fspn--lefseeki
eltfatnfl---ghylltemlie-kmidt-aeksgiegriinlssvihn------wvk--
pdcf---s-fpkl--lhp---i------sryn--gtrayaqsklatilhakalskqlkdr
n-anvtinavhpgivk-tgi-i---------r----------------------------
------------------------------------------------------------
------a------------hkglf----------
>69_Branchiostoma_floridae_378
----------------taiitggtsgigaetarvlakrgv--rvvma--vrdmkkaemvk
eriirenpe-------a-------------d----iilfeidlsslssvarfcsqfls--
-------------------qdlplnilinnag----------v---fspn--lefseeki
eltfatnfl---ghylltemlie-kmidt-aeksgiegriinlssvihn------wvk--
pdcf---s-fpkl--lhp---i------sryn--gtrayaqsklatilhakalskqlkdr
n-anvtinavhpgivk-tgi-i---------r----------------------------
------------------------------------------------------------
------a------------hkglf----------
>70_Canis_familiaris_380
----------------tviitgantgigkvtardmaqrga--rvila--crslekaeeaa
keirsqtgn-------k-------------n----vvvhkldlasltsvrqfakvind--
-------------------aeprldvlinnag----------v---mvcp--rwetedgf
emqfgvnhl---ghflltnllld-llkkt-ap-s----rvvtlsslahs------fts--
--gi---d-fddi--nye---k-------dyd--rresyhrsklanvlfsrelarrleg-
--tgvksnslhpgviy-sel-y---------r-hqedf-----vrei-------------
------------------------------------------------------------
----------------------------------
>71_Rhodobacterales_bacterium_HTCC2083_386
----------------tviitgansgigketardlakrga--rvima--crnmetakear
deivkdsgn-------e-------------a----vfvkkldlssqasvrefaaevlk--
-------------------tenkldvlihnag--------------faqtfkktksvdgi
eftmatnhy---gpfllthllid-llkks-ap-s----rivvvaselyr-------fa--
--sv---d-lnnl--npl-----------tsi--pamlyyvsksanimftrelsrrleg-
--tnvtvnclhpgmid-sgi-w---------r-nvpfp---------ltlpmsii-----
----kaffktnaegaqttlylacspevegisgkyfrdck-----------eagl------
------t---ngicdmer-akklweesakmvkl-
>72_Halorubrum_lacusprofundi_ATCC_49239_390
-------------rgrtavvtgansgigkmtalelarrga--rvvla--crsrergeaaa
fdlrqesgn-------n-------------e----vifmaldlanlasvrafatafls--
-------------------seprldilihnag----------i---sscg----rtreaf
nlllrvnhi---gpfllthlllp-clkac-ap-s----rvvvvasaahc-------rg--
--rl---d-fkrl--dr--------pvvgwrq--elrayadtklanvlfarelanqleg-
--tgitcyaahpgpvn-selfl---------r-hvpgw---------lrpllrpl-----
---awlvlraprggaqtplycalqegieplsgryfanch-----------veev------
------p---paarddra-ahrlweaskrlagl-
>73_Trichoplax_adhaerens_392
-----------------ialtgatsgigrraavtlaerga--tvaav--grnrergeala
aesdaaagt--------------------------irfhradlatqsavrdlaaelre--
-------------------sydrldvlahnag----------l---svrs--rtetadgi
eltlavnhl---apylltrelfd-qlags-ap-a----rvvvtasdlhr-------ra--
--tl---d-fddl--qfa---d-------gyd--pleayarsklanvaftleladripea
--agvtanclhpgfvpstnl-f-------------------------rdaalrtrlavri
agllpgvgttrraaadrlvrlvaspeyaertgryvgeee------------mtp------
------a---ddtvdset-rerlwsvsadlvgi-
>74_Monodelphis_domestica_394
----------------tvivtgansgigketardlakrga--rvima--crnmetaakar
deivketgn-------n-------------n----vflkkldlssqasirefatdvlk--
-------------------tetkldvlihnag--------------faetfkksksvdgi
eftmatnhy---gpfllthllid-llkrs-ap-s----rivivaselyr-------fa--
--sv---d-lnnl--npv-----------nsl--pgylyyvskcanimftrelarrleg-
--tnvtanclhpgmid-sgi-w---------r-nvpfp---------ltipmavm-----
----kaffktnvegaqtslhlacssevegisgkyfrdck-----------eagl------
------t---agisdmek-akklweesvkmvkl-
>75_Monodelphis_domestica_406
-----------------vvitgassglgqaaaeevaatgr--hvvla--crdadrgaaaa
deirarvpdas------------------------levleldladlasvraaakall---
-------------------agpplgalvcnag--------------vqvvggirrsrdgh
eltfatnhl---ghflltrllld-hlaea-g-------rivlvssgthygprrsmgfpa-
phwe---n-psal--adp---elsvlddsprs--griryatsklaniyttyelnrrrng-
--rritvnafdpglmpqtgl-a---------rdypdrfrr-------lygriapvlvr--
---avpgvrsvarsaadlswlvtagepgvvsglyfvgrr-----------prkt------
------s---desydrvr-alelwefserlv---
>76_Homo_sapiens_412
--------------ravaivtganaglgretaralvkkgy--avvla--trdvergeraa
aevraaaag--agaggt------------------aeamradladfesirrfarafea--
-------------------kyerldalvcnag----------v---malp-nrettvdgn
etqmqvnhl---ghflltslllptmlktp-sndk----rivnvssvahn-------fg--
--tl---d-fhni--nsegffg------ypfl--gwatygrtkmanvlftfelhrrlras
giddvcvnavhpgvvd-tel-n---------r---------------nlsldfypqlkrm
---gqlitpskalgaksgqyvs--------------------------------------
----------emfnd-------------------
>77_Arabidopsis_thaliana_418
------------------litgatsgigfetaralalhga--lvimg--chdivkgsiaa
kkitkeep--------l------------ak----idvievdlsslksiacladevlk--
-------------------kyrqlhviicnag----------v---lglp--wrlttdel
eytftvnyi---ghfylvkllte-lliss-sp-a----rvvvisseshr-------fp--
--tt---d-gssf--nve---nilp-skqqfi--pmeaynqsklcgilfsnefnrkysc-
--ygvtsnavhpgnllptsl-c---------rnsw------------fytilfll-----
---arpfakstvqgaatttfcaaarelngvggsyfnncq-----------rcdp------
------s---pesqneel-aralwkytesll---
>78_Bos_taurus_420
----------------taiitggtsgigaetarvlakrgv--rvvma--vrdmkkaemvk
eriirenpe-------a-------------d----iilfeidlsslssvarfcsqfls--
-------------------qdlplnilinnag----------v---fspn--lefseeki
eltfatnfl---ghylltemlie-kmidt-aeksgiegriinlssvihn------wvk--
pdcf---s-fpkl--lhp---i-------ryn--gtrayaqsklatilhakalskqlkdr
n-anvtinavhpgivk-tgi-i---------r----------------------------
------------------------------------------------------------
------a------------hkglf----------
>79_Myxococcus_xanthus_DK_1622_424
------------------ivtgassgigvettrvlalrgv--hvvma--vrnadagrnvk
esilkeips-------a-------------k----idvmeldlssmasvrkfasqyqs--
-------------------snlplnllinnag----------v---matp--fmlsqdki
elqfatnhl---ghflltdllle-tmkrt-aresniegrivnvsseghr-------iay-
regi---r-fdki--nde---s-------gyy--twyaygqsklanilhakelaqrlkee
e-veitanslhpgaiistnl-m---------rhhgl-----------intvgqml-----
---gkyflknipqgaattcyvalnpqvkgvsgeyfldsn-----------ignp------
------s---akakdadl-akklwdfs-------
>80_Canis_familiaris_438
----------------tilvtgansgigleavklfaanga--evila--crntakaeaav
eqvreqtpd--a----r------------------livmpldladlasvkafvvalke--
-------------------riskldillnnag----------l---mapp--lqrtqdgf
eiqfgtnhl---ghfaltgplldlleaap-ap------rivqisslahr-------sg--
--ki---m-wgnl--nae---k-------rys--rwpfycqsklanlifakdlhrrlrkr
g-sniqvmaahpgysa-thl-q---------d---------------tipggglf-----
---nkvmaqpaemgclpgvmaatsdevvs--ggyygpdgkilelrgypapafa-------
------r---kitdnegl-aqrlwdeserltgv-
>81_Arabidopsis_thaliana_440
----------------tviitgansglgletarelarvga--hvima--vrntekgnaaq
asikgs-----------------------------tevrqvdvadlasvrafadtveg--
-----------------------adilvnnag----------i---mmvp--paktvdgf
esqigtnhl---gafaltnlllpkltd-----------rviavssvahr-------ag--
--ki---d-ltdl--nye---r------rryt--ragaygasklanllftkelqrrlsaa
g-spvraltvhpgvaa-telqs---------h---------------sgnpifelalkt-
---gnlfaqnaahgalptlyaa-sqdlpg--dtyigpdg-pfeakgyptrvgr-------
------s---graqdtet-akglwrlseqltgv-
>82_Synechococcus_sp._PCC_7002_442
----------------tavvtgatsgigtetarvlalrgv--hvimg--vrnivaagdvk
aaiikeipt-------a-------------k----vdamdldlssmasvrkfalnfns--
-------------------sglplnilinnag----------v---atgk--fmlskdnv
eqhfatnhl---ghflltnllle-tmkrt-arksgrvgriinvsseghr-------vsy-
hggi---r-fdni--ndp---s-------gys--ryfaycqsklanvlhanelarrlked
g-anvtanslhpgmip-tnl-f---------ssssils-----nsv-aaglfkml-----
---sgvvlknvqqgaattcyaalhpeverisgayfvnss-----------lgqa------
------s---smardvnl-akklwdfsmdii---
>83_marine_gamma_proteobacterium_HTCC2148_444
------------------ivtgantglgfetalglaktgc--hvila--crdmdkaaaaa
teirqqipd--a----n------------------vetmaldlsqlasvkefatayrq--
-------------------rhqtlnllinnag----------i---mfpp--ysqtvdgf
esqfcvnyl---ghflltallidlmpdta-es------rvvslssnahk-------fg--
--ki---n-fqdl--qse---q-------nys--ataaygqsklacllfavelqrrlaak
n-knilsvaahpgiap-tel-g-----ryipa---------------flaglirlif---
---vpffansvaqgalptlmaaldpaatg--gdyfgpqg-fgemsgkpgrvek-------
------s---dqakdeai-akqlwetsetli---
>84_Taeniopygia_guttata_446
-----------------vvvtgansgigfetaksfalhga--hvila--crnmaraseav
srileewh--------k------------ak----vetmtldlallrsvqhfaeafka--
-------------------knvplhvlvcnaa----------t---falp--wsltkdgl
ettfqvnhl---ghfylvqllqd-vlcrs-ap-a----rvivvsseshr-------ft--
--din-ds-lgkl--dfs---rlsp-tkndyw--amlaynrsklcnilfsnelhrrlsp-
--rgvtsnavhpgnmmysni-h---------rsww------------vytllftl-----
---arpf-----------------------------------------------------
----------------------------------
>85_Saccharopolyspora_erythraea_NRRL_2338_460
----------------tvivtggntgigkatatalavrga--rvila--crskqkgeeaa
keiraesgn-------d-------------d----vifmqldlasqksirsfaetflk--
-------------------teprldllinnag----------l---aaag----rtedgi
gmilgvnhi---gpflltnllle-rlkec-ap-s----rvvnvsscghd-------lg--
--ti---d-fdci--nth---kklglgssdgd--lfraythsklcnvlfthelakrleg-
--tnvtcyslhpgsvr-sel-g---------r-ditew--------harvlltvv-----
---skffatdpvsgaqttlycslqdgiehlsgryfsdcq-----------lvqv------
------k---aearddgv-akklwevseklcgm-
>86_Trichoplax_adhaerens_466
------------------ivtggntglgretvrelarrga--tvyma--crdkdkgekar
keivketkn-------s-------------n----vfsrecdlssldsvrnfvdgfkk--
-------------------eqdklhilinnag----------v---fwep--rsltkegf
emhlgvnhi---ghfllthllld-llkqs-ap-s----rivvvsskahe-------rg--
--ri---q-vddi--nsk---l-------syd--egaaycqsklanilftrelarrleg-
--tavtvnalnpgiad-tei-a---------r-nmiff-----rtklaqtilrpl-----
---lwslmksprngaqttlfaaldcdldhvsgqyfsdcr-----------pkel------
------a---paakdddm-arwlwsqsekwtgi-
>87_Arabidopsis_thaliana_468
----------------tvivtgantgigktaaadlaqrga--rvica--crsmercnaav
adikretnn-------v-------------q----vvaakldlgsmksirefaqmfkn--
-------------------tekrldilinnag--------------igcrnvdkktedgf
edrmgvnhl---ghflltnllld-mlkqs-qp-s----rivcltslihw------ttt--
--dl---d-fdnl--anh---t-------sts--scdnysrskianilfvlelskrlkg-
--tgvtanavhpglvq-tet-l---------rsarese---gflatsytkfmevv-----
---fllvgndarrgaqttvyaavdpslenvsgqflarck-----------idtp------
------s---pyardeav-akklydmslklvnl-
>88_Arabidopsis_thaliana_470
----------------taivtgassgigvetarvlslrgv--hvvma--vrntdsgakvk
edivkqvpg-------a-------------k----ldvmeldlssmqsvrkfaseyks--
-------------------tglplnllinnag----------i---macp--fmlskdni
elqfatnh-------------ld-tmkst-sreskregrivnlsseahr-------fsy-
pegv---r-fdki--ndk---s---------s--smraygqsklcnvlhaneltkqlked
g-vnitanslhpgaim-tnl-g---------ryfnpy----------lavavgav-----
---akyilksvpqgaattcyvalnpqvagvsgeyfqdsn-----------iakp------
------l---plvkdtel-akkvwdfstkl----
>89_Arabidopsis_thaliana_472
-------------------------------arvlskrga--hvvig--arnmgaaenak
teilrqnan-------a-------------r----vtllqldlssiksikafvrefha--
-------------------lhlplnllinnag----------v---mfcp--yqlsedgi
elqfatnhi---ghflltnllld-tmknt-aktsgvegrilnvssvahi-------yty-
qegi---q-fdsi--ndi---c-------sys--dkraygqsklanilhanelsrqlqee
g-vnitansvhpglil-tnl-f---------qhtal-----------lmrflkff-----
---sfylwknipqgaattcyvalhpsvkgvtgkyfadcn-----------evtp------
------s---klardetl-aqklwdfsvkli---
>90_Physcomitrella_patens_subsp._patens_474
------------------ivtggntglgketvmelarrga--tvyma--crskekgerac
reivketgn-------s-------------n----vfsrecdlssldsirkfaenfkk--
-------------------eqrelhilinnag----------v---fwep--hrltkegf
emhlgvnhi---ghflltnllld-vlers-ap-s----rvvvvasrahe-------rg--
--qi---k-vddi--nss---e-------fyd--egvaycqsklanilftrelakrleg-
--tgvtvnalnpgiad-tei-a---------r-nmiff-----qtkf-------------
------------------------------------------------------------
----------------------------------
>91_Danio_rerio_478
------------------ivtggntglgketvmelarrga--tvyma--crnkekverar
reivketgn-------s-------------n----vfsrecdlssldsirkfaenfkk--
-------------------eqrvlhilinnag----------v---fwep--hrltkegf
emhlgvnhi---ghflltnlllg-vlers-ap-s----rvvvvasrahe-------rg--
--qi---k-vddi--nss---d-------fyd--egvaycqsklanilftrelakrleg-
--tgvtvnalnpgiad-tei-a---------r-nmiff-----qtkf-------------
------------------------------------------------------------
----------------------------------
>92_Tribolium_castaneum_482
----------------tviitgansgigketardlakrga--rvima--crnmetakqaq
eeimaetgn-------t-------------k----llikhvdisslasvrafakeiva--
-------------------tepvidvlihnag--------------vaqgfnnkvtsdgl
eftmatnyy---gpfllthllid-llkrs-dq-g----rivivssklyq-------fa--
--slnpan-insi--npi---n-------yfslfpihlynlskfaeimftqelarrlrg-
--tkvtanclhpgvid-tgi-w---------r-nvpfp---------isilfkpi-----
----qmcfrtpeegartsiylsvspdveqisgqyfrgcr-----------vhql------
------n---rrvqhvar-qhdlweaskklvkl-
>93_'Oryza_sativa__japonica_cultivar-group__488'
----------------tvlitgansglgrataaellrlga--rvimg--crdraraeeaa
gqlrqelcq-------aggagpd---gtdgq----lvvkeldlaslrsvrafcqkllq--
-------------------eeprldvlinnag----------v---fhcp--ytktedgf
emqfgvnhl---ghflltnlllg-llkss-ap-s----rivvvssklyk-------yg--
--ei---n-fedl--nse---q-------syn--ksfcysrsklanilftrelarrleg-
--tnvtvnvlhpgivr-tnl-g---------r-hihip-------llarplfnlv-----
---swaffktplegaqtsiylacspdvegvsgryfgdck-----------eeel------
------l---pkamdesv-arklwdisevmvgi-
>94_Arabidopsis_thaliana_490
-------------kdknilitggnsgigfyatinllkakn--nlyip--irsiprkdqff
fkllkyfdkkyldkyln-------------------lienidlanlrnieilrdylnk--
-------------------knvsfdviilnag----------lq--ytgsfypkvskqgi
eltfavnhl---ahfylvnsliglinnkk-es------riiitssdvhdpkssggnvgk-
kagl---nnlvnfkqeitgkyl-------nfn--sdkayknsklcnilfakelskrlqik
a-yevavitwapglvipnedlg---------ffrysk----------kfnffgyiifsii
aknilgisenvenagkllseivtdpefnnikylhlsnkl--vffkkhkllksei------
------s---eeanksdl-alrlwnlseel----
>95_'Oryza_sativa__japonica_cultivar-group__500'
----------------tvvitgantgigyetakelasrga--rvilg--crnaqkaeaav
nqlvadtrn-------s-------------n----iswklldtssmesvrtfamevlk--
-------------------atdsihvlinnag--------------iagpkercvteegl
evtfatnyl---ghflltnlllp-vlkss-sp-s----riislssvaym-------fg--
--ni---d-fadl--qsms--g-------kfv--tgkvysnsklatvlfttelarrldg-
--tgvtanvlhpgvvn-tpl----------------------------------------
------------------------------------------------------------
-------------------srslmkvgepvfsil
>96_Strongylocentrotus_purpuratus_502
-----------------vvvtgansgigfetaksfalhga--hvila--crnmaraseav
srileewh--------k------------ak----vetmtldlallrsvqhfaeafka--
-------------------knvplhvlvcnaa----------t---falp--wsltkdgl
ettfqvnhl---ghfylvqllqd-vlcrs-ap-a----rvivvsseshr-------ft--
--din-ds-lgkl--dfs---rlsp-tkndyw--amlaynrsklcnilfsnelhrrlsp-
--rgvtsnavhpgnmmysni-h---------rsww------------vytllftl-----
---arpftksmqqg----------------------------------------------
----------------------------------
>97_Danio_rerio_512
----------------tvivtganvgigkmtaldmakrga--rvila--crvketgeaaa
ydirklsgn-------n-------------q----vvfmkldlaslesvrsfcrafls--
-------------------seprldilinnag----------l---sgfg----ktaegy
nivfgvnhl---ghflltsllld-rlkqs-tp-s----rivvlasyahe-------wg--
--ki---d-fnki--sv--------psehvkd--tlqsycdsklcnvlfarelanrlqg-
--tsvtcysvhpgtvh-tnl-a---------r-slpsw---------ikvliepv-----
---swlflrtpmngaqtsiycavqegiemysgryfdncq-----------vrqv------
------k---pharddav-akklwevsermtgl-
>98_Tetrahymena_thermophila_SB210_520
------------------ivtggntglgketvlelarrga--tvyma--crnkekgerar
reivkvtgn-------s-------------n----vfsrecdlssldsirkfaenfkk--
-------------------eqrelhilinnag----------v---fwep--hrltkdgf
emhlgvnhi---ghflltnllld-vmers-ap-s----rvvvvasraha-------rg--
--ri---n-vddi--nss---y-------fyd--egvaycqsklanilftrelakrleg-
--trvtvnalnpgiad-tei-a---------r-nmiff-----qtkfaqtvlrpi-----
---lwslmktpkngaqttlyaaldpdlekvsgqyfsdct-----------lapv------
------a---paalddqm-aqwlwaqsekwaaia
>99_Mycobacterium_bovis_BCG_str._Tokyo_172_530
----------------tvivtgantgigkqtalelakrgg--niila--crdrekceaaa
kdirgetln-------p-------------r----vraehldlaslksirefagkiik--
-------------------eeervdilvnnaa----------v---mrcp--hwttedgf
emqfgvnhl---ghflltnllld-klkas-ap-s----riinlsslahv-------ag--
--hi---d-fedl--nwqi--k-------kyd--tkaaycqsklavvlftkelsrrlqg-
--tgvtvnalhpgvar-tel-g---------r-htgmh-----nsafsgfmlgpf-----
---fwllfkspqlaaqpstylavaeelesvsgkyfdglr-----------ekap------
------s---peaedeev-arrlwtesahlvgl-
>100_Branchiostoma_floridae_536
----------------taivtgassgigvetarvlalrdv--hvvma--vrnvdagrnvk
esilkeipt-------a-------------k----idvmqfdlssmasvrkfaseyis--
-------------------sglplnllinnag----------v---matp--fmlsqdni
erqfatnhv---ghflltdllle-tmknt-aressregrivnvssaghr-------fty-
regi---r-fdkl--nde---a-------gyn--silaygqsklanilhagelarrlked
g-vdisvnslhpgaid-tnl-l---------ryhsv-----------ingivslv-----
---akyviknvqqgaattcyvalhpqvkgvtgeyfsdsn-----------iatp------
------t---sqakdadl-akrlwdfsvrl----
>101_Mycobacterium_tuberculosis_T17_538
----------------taivtgassgigaettrvlalrga--hvimg--vrnmvaakdvk
dtilkdips-------a-------------k----vdaieldlssldsvkkfasefns--
-------------------sgrplnilinnag----------i---macp--fklskdni
elqfatnhi---ghflltnllld-tmkkt-treskkegrivnvaseahr-------fay-
pegi---r-fdki--ndq---s-------syn--nwraygqsklanvlhanqltkhlked
g-vnitanslhpgtiv-tnl-f---------rhn--------------------------
------------------------------------------------------------
----------------------------------
>102_Hydra_magnipapillata_540
----------------tvivtgantgigkqtalelakrgg--niila--crdmekceaaa
keirgetln-------h-------------r----vnarhldlaslksirefaakvte--
-------------------eeehvhilinnaa----------v---mrcp--hwttedgf
emqlgvnyl---ghflltnllld-klkas-ap-s----riinvsslahv-------ag--
--hi---d-fedl--nwek--r-------kyd--tkaaycqsklavvvstkelsrrlqg-
--tgvtvnalhpgvar-tel-g---------r-htgmh-----ssafssftlgpi-----
---fwllvkspelaaqpsvylavaeelegvsgkyfdvlk-----------ekpp------
------a---peaedeev-akrlwaesvrlvgl-
>103_Burkholderia_thailandensis_TXDOH_542
-------------rglaavvtgassgiglettrvlalrgv--rvvma--vrnvaaghkar
eairaeihg-------a-------------i----vhvlemdlssmdsvrrfasefds--
-------------------lnlplnilinnag----------i---lskd--cirsidgl
elhfatnhi---ghflltnllle-nmkst-srttgvegriinvsssghi-------lty-
pegi---c-fdsv--kdl---s-------rfs--tyiaygqsklanilhstelarilkgd
g-vnisanaihpgfvg-tnl-f---------knwtm-----------anavvnti-----
---grivcktveqgaattcyvalhpqvtgisgkyfsncn-----------letp------
------s---sqasnael-akklwefssniv---
>104_Mycobacterium_marinum_M_552
-------------kgktvivtganigigkmtaldmarrga--rvila--crvketgeaaa
ydirqlsgn-------n-------------q----vlfmnlnlsslesvrsfcrafls--
-------------------seprldilinnag----------f---sgpg----ktaegy
nivfginhl---ghflltsllld-rlkqs-tp-s----rivalasyahe-------wg--
--ki---d-fnki--sv--------psdhikd--ilqsycdsklcnvlfarelanrleg-
--tgvtcysvhpgtvh-tnl-v---------r-slpnw---------ikacikpf-----
---twlflrtpmdgaqtsiycavqegiemytgryfdncq-----------vrqv------
------k---pharddav-akklwevsermtgl-
>105_'Sulfitobacter_sp._NAS-14.1_572'
----------------tavitgassglglatakalaetgr-whvvmg--crdflkasraa
kaagmekgs--------------------------ytivhldlasldsvrqfvgnvrr--
-------------------lgmpvdvvvcnaa----------vyqptakq--psftadgf
emsvgvnhl---ghfllarel---------------------------------------
-------------------------------------------ladltssdypskrl---
--iivgsitgngnlspspel-g--------------------------------------
------------------------------------------------------------
----------------------------------
>106_Drosophila_ananassae_584
----------------tvivtggntgigkatalelarrga--rvima--crnqekaelai
sdikretgs-------t-------------d----vvymqldlgslqavrsftetflk--
-------------------tearldllinnag----------l---vadg----rtadgf
giefgvnhl---ghflltcllld-rlkeg-tg-g----rvvtlgsmayr-------wg--
--ni---d-fdal--itn---khlgtgryswq--ffhaycnsklcnvlfnhelakrlkg-
--tnvtcysvhpgvvk-tel-s---------r-ncslw---------qrfiiepi-----
---arllfldpesgaqttlhcalqegieplsgryffcca-----------pqdv------
------v---akgkddav-akklwevserlsgl-
>107_Vitis_vinifera_586
--------------ravaivtganaglgretaralvkkgy--avvla--trdvergeraa
aevraaaag--agaggt------------------aeamradladfesirrfarafea--
-------------------kyerldalvcnag----------v---malp-nrettvdgn
etqmqvnhl---ghflltslllptmlktp-sndk----rivnvssvahn-------fg--
--tl---d-fhni--nsegffg------ypfl--gwatygrtkmanvlftfelhrrlras
giddvcvnavhpgvvd-tel-n---------r---------------nlsldfypqlkrm
---gqlitpskalgaksgqyvs--------------------------------------
----------emfnd-------------------
>108_Drosophila_ananassae_588
----------------tviitgantgigkeaaidlarrga--rvica--crsksrgeaav
ediknisgn-------n-------------n----valkmldlgslnsirqfakdina--
-------------------keerldvlinnag--------------lagpayrdttedgf
ermmgvnhl---ghflltdllld-llkks-qp-s----rivvvssnahr------mvs--
--sm---n-lddl--mse---k-------sys--gtsvygysklanilfslemskrlkg-
--tsvtinalhpgavm-tel-g---------r-hlddy-----------lqlppflnkam
rwtmsiffrdsrqgaqtviclavdrnlesvsgkyfaeck-----------iset------
------t---aaatnete-akmlwdiseklv---
>109_marine_actinobacterium_PHSC20C1_592
-------------kgktvivtganvgigkmtaldmakrga--rvila--crvketgeaaa
ydirklsgn-------n-------------q----vvfmkldlaslesvrsfcrafls--
-------------------seprldilinnag----------l---sgfg----ktaegy
nivfgvnhl---ghflltsllld-rlkqs-tp-s----rivvlasyahe-------wg--
--ki---d-fnki--sv--------psehvkd--tlqsycdsklcnvlfarelanrlqg-
--tsvtcysvhpgtvh-tnl-a---------r-slpsw---------ikvliepv-----
---swlflrtpmngaqtsiycavqegiemysgryfdncq-----------vrqv------
------k---pharddav-akklwevsermtgl-
>110_Arabidopsis_thaliana_594
---------lpsqqgkkaivtgantglgfetalglaktgc--hvila--crdmdkaaaaa
teirqqipd--a----n------------------vetmaldlsqlasvkefatayrq--
-------------------rhqtlnllinnag----------i---mfpp--ysqtvdgf
esqfcvnyl---ghflltallidlmpdta-es------rvvslssnahk-------fg--
--ki---n-fqdl--qse---q-------nys--ataaygqsklacllfavelqrrlaak
n-knilsvaahpgiap-tel-g-----ryipa---------------flaglirlif---
---vpffansvaqgalptlmaaldpaatg--gdyfgpqg-fgemsgkpgrvek-------
------s---dqakdeai-akqlwetsetli---
>111_Anopheles_gambiae_str._PEST_602
-----------------mflagassgigaetcrvlvmrgv--hvvmg--vrnlsagacvr
deilkqvps-------a-------------k----iyilnldlssmssvrrfaenfka--
-------------------lnlplnilinnag----------v---cfvp--fklsedgi
elhfatnhv---ghflltdllie-kmkvt-aiesgkegrvvmvasikde-------ktdl
ykdm---t-fnyiflfsl---a-------ryn--rflaygqsklanilhsnllsshlkeq
d-akvivnslhpgava-tni-l---------hhwcp-----------lygairai-----
---gkyfvkgveqgaatvcyvalhsqvagvtgkyfsdcn-----------itel------
------k---shaldrdl-akrlwdfslsli---
>112_uncultured_haloarchaeon_604
----------------tviitgantgigkvtardmaqrga--rvila--crslekaeeaa
keirsqtgn-------k-------------n----vvvhkldlasltsvrqfakvind--
-------------------aeprldvlinnag----------v---mvcp--rwetedgf
emqfgvnhl---ghflltnllld-llkkt-ap-s----rvvtlsslahs------fts--
--gi---d-fddi--nye---k-------dyd--rresyhrsklanvlfsrelarrleg-
--tgvksnslhpgviy-sel-y---------r-hq-------------------------
------------------------------------------------------------
----------------------------------
>113_Danio_rerio_608
----------------taiitggtsgigaetarvlakrgv--rvvma--vrdmkkaemvk
eriirenpe-------a-------------d----iilfeidlsslssvarfcsqfls--
-------------------qdlplnilinnag----------v---fspn--lefseeki
eltfatnfl---ghylltemlie-kmidt-aeksgiegriinlssvihn------wvk--
pdcf---s-fpkl--lhp---i------sryn--gtrayaqsklatilhakalskqlkdr
n-anvtinavhpgivk-tgi-i---------r----------------------------
------------------------------------------------------------
------a------------hkglf----------
>114_Drosophila_virilis_618
----------------tilvtgansgigleavklfaanga--evila--crntakaeaav
eqvreqtpd--a----r------------------livmpldladlasvkafvvalke--
-------------------riskldillnnag----------l---mapp--lqrtqdgf
eiqfgtnhl---ghfaltgplldlleaap-ap------rivqisslahr-------sg--
--ki---m-wgnl--nae---k-------rys--rwpfycqsklanlifakdlhrrlrkr
g-sniqvmaahpgysa-thl-q---------d---------------tipggglf-----
---nkvmaqpaemgclpgvmaatsdevvs--ggyygpdgkilelrgypapafa-------
------r---kitdnegl-aqrlwdeserltgv-
>115_Physcomitrella_patens_subsp._patens_620
----------------tavitgassglglqcarallrrdaswhvvla--vrdpargrggh
ggiggakpv--------------------------fgsrggtsrrcgpwrsfveivrtt-
-------------------plppiralvcnag--------------lqvvsgiaftddgv
emtfgvnhl---ghfalvtgild-wlarp-a-------rivvvssgth-dpskhtgmpd-
pryt---c-aadl--ahp---ptd--qntpae--grrryttsklcnvlftyeldrrldhg
e-qgvmvnafdpglmpgsgl-a---------rdyppilrl-------ayrllspmlr---
---vlpfvhstrvsgehlaalavdprfagvtgqyfagak-----------airs------
------s---aesydrak-aldlwetserlla--
>116_Danio_rerio_622
-----------------vivtgantgigketakelarrga--tvyma--crdmtrceiar
leivketnn-------q-------------n----vfsreldlsslasirkfvagfka--
-------------------eqqklhvlinnag----------v---mrcp--ktltkdgf
eiqlgvnhm---ghflltnllld-vlkks-ap-s----rivvvsslaht-------rg--
--ai---n-vddl--nse---k-------syd--egsaysqsklanvlftrelakrleg-
--tgvtvnalhpgvvd-t------------------------------------------
------------------------------------------------------------
----------------------------------
>117_Acyrthosiphon_pisum_624
------------------ivtgassgigvetarvlslrgv--hvvma--vrntdsgakvk
edivkqvpg-------a-------------k----ldvmeldlssmqsvrkfaseyks--
-------------------tglplnllinnag----------i---macp--fmlskdni
elqfatnhl---ghflltkllld-tmkst-sreskregrivnlsseahr-------fsy-
pegv---r-fdki--ndk---s-------sys--smraygqsklcnvlhaneltkqleed
g-vnitanslhpgaim-tnl-g---------ryfnpy----------lavavgav-----
---akyilksvpqgaattcyvalnpqvagvsgeyfqdsn-----------iakp------
------l---plvkdtel-akkvwdfstkl----
>118_Vitis_vinifera_626
------------------ivtggntglgretvrelarrga--tvyma--crdkdkgekar
keivketkn-------s-------------n----vfsrecdlssldsvrnfvdgfkk--
-------------------eqdklhilinnag----------v---fwep--rsltkegf
emhlgvnhi---ghfllthllld-llkqs-ap-s----rivvvsskahe-------rg--
--ri---q-vddi--nsk---l-------syd--egaaycqsklanilftrelarrleg-
--tavtvnalnpgiad-tei-a---------r-nmiff-----rtklaqtilrpl-----
---lwslmksprngaqttlfaaldcdldhvsgqyfsdcr-----------pkel------
------a---paakdddm-arwlwsqsekwtgig
>119_Arabidopsis_thaliana_628
---------------kvvlvtgansgigfetaksfalhga--hvila--crnlsraseav
srileewh--------k------------ak----veamtldlavlrsvqhfaeafka--
-------------------knvslhvlvcnag----------t---falp--wgltkdgl
ettfqanhl---ghfylvqllqd-vlcrs-sp-a----rvivvsseshr-------ft--
--din-ds-sgkl--dls---rlsp-prsdyw--amlaynrsklcnilfsnelhrrlsp-
--rgvtsnavhpgnmmysai-h---------rnsw------------vykllftl-----
---arpftksmqqgaattvycavapeleglggmyfnncc-----------rclp------
------s---eeaqseet-aralwelserli---
>120_Oryza_sativa_Indica_Group_630
-------------qgkkaivtgantglgfetalglaktgc--hvila--crdmdkaaaaa
teirqqipd--a----n------------------vetmaldlsqlasvkefatayrq--
-------------------rhqtlnllinnag----------i---mfpp--ysqtvdgf
esqfcvnyl---ghflltallidlmpdta-es------rvvslssnahk-------fg--
--ki---n-fqdl--qse---q-------nys--ataaygqsklacllfavelqrrlaak
n-knilsvaahpgiap-tel-g-----ryipa---------------flaglirlif---
---vpffansvaqgalptlmaaldpaatg--gdyfgpqg-fgemsgkpgrvek-------
------s---dqakdeai-akqlwetsetli---
>121_Pseudovibrio_sp._JE062_632
--------------------ciattglfrehvppf-------rllfppfqkyitkgfvse
ee----------------------------------------------------------
-------------------agkrlaqvvsnps----------------------ltksgv
ywswnnnsa---------------------------------------------------
-----------------------------sfe----------------------------
-----------------nql----------------------------------------
------------------------------------------------------------
------s---eeasdpek-akklweiseklvgl-
>122_Geobacillus_sp._Y412MC10_638
-----------amagktvivtggntgigkatalelarrga--rvima--crnqekaelai
sdikretgs-------t-------------d----vvymqldlgslqavrsftetflk--
-------------------tearldllinnag----------l---vadg----rtadgf
giefgvnhl---ghflltcllld-rlkeg-tg-g----rvvtlgsmayr-------wg--
--ni---d-fdal--itn---khlgtgryswq--ffhaycnsklcnvlfnhelakrlkg-
--tnvtcysvhpgvvk-tel-s---------r-ncslw---------qrfiiepi-----
---arllfldpesgaqttlhcalqegieplsgryffcca-----------pqdv------
------v---akgkddav-akklwevserlsgl-
