>Chorispora_bungeana_4
---lqaaslvssafsvrkdgklnas-sssfkdsslfgvsit--dliksehgsssirfkre
hnlrn--vairaqtaatsspsvtkssgegkktlrkgnvvvtgassglglatakalaet-g
kwhvimacrdflkaeraaksagmp-----------------kgsytvmhldlasldsvrq
fvdnfr--rsemp------ldvlvcnaavyfp----takeptysaegfelsvgtnhlghf
llsrlllddlk-ksdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--agglngl--nssamidggd-fdgak-------aykaskvcnm-ltmqefhr-r
ch--------e------etgvtfaslypgcia---stglfr--epiplfrflf----ppf
qkyitk-------gyvsetesgkrlaqvvsdpsl-t-ksgvywsw-----------nkas
a-------------------------------sf------------------enqlsqe-
asdve---karkvweiseklvgla
>Arabidopsis_thaliana_8
---lqaaslvssafsvrkdaklnas-sssfkdsslfgasit--dqiksehrssslrfkre
qslrn--lairaqtaatssptvtksv-dgkktlrkgnvvvtgassglglatakalaqt-g
kwnvimacrdflkaeraaksvgmp-----------------kdsytvmhldlasldsvrq
fvdnfr--rtetp------ldvlvcnaavyfp----takeptysaegfelsvatnhlghf
llarlllddlk-ksdyp-----------skrliivgsita-ntntlagn--vppka-nlg
dlrgl--agglngl--nssamidggd-fdgak-------aykdskvcnm-ltmqefhr-r
fh--------e------etgvtfaslypgcia---stglfr--ehiplfralf----ppf
qkyitk-------gyvsetesgkrlaqvvsdpsl-t-ksgvywsw-----------nnas
a-------------------------------sf------------------enqlsee-
asdve---karkvweiseklvgla
>Populus_trichocarpa_10
---lqaaslvssafvfpke---gks-nayfkdsslfgvsls--ehvkadfsscalkckre
fnqgv--gavraqtmvaatpaldrasseskktlgqgtcivtgassglglatakalaet-g
kwhiimacrnflkaeraaksagia-----------------kenytimhldlasldsvrq
fvdtfr--rsgrp------ldvlvcnaavylp----takepaftaegfelsvgtnhlghf
llsrllledmk-isdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--sgglngl--nrsamidggv-fdgak-------aykdskvcnm-ltmqefhr-r
lh--------e------etgiafaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gfvseheagkrlaqvvsdpsl-t-ksgaywsw-----------nkhs
a-------------------------------sf------------------qnqlsqe-
asdae---karkvweiseklvgla
>4>_Nicotiana_tabacum_12
---lqaaalvpsafsiske---gka-sanlknsslfgvsls--dysksdfgsssfkvksq
rrlsn--gavra-tmva-spdvttnspagkktlrkgcvivtgassglglatakalset-g
kwhvimacrdflkaekaaksvgmp-----------------kenytimhldlasldsvrq
fvdnfr--rsgrp------ldvlvanaavyqp----takepsftaegfeisvgtnhlghf
llsrlllddlk-qsdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgm--agglngi--nssamidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gfvseteagkrlaqvvsdpsl-t-ksgvywsw-----------nkds
a-------------------------------sf------------------enqlsee-
asdve---karkvwevseklvgla
>5_Ricinus_communis_14
-----asslvsstfvvlkegks----sasfkdsslfgvsls--dhlkadhsssafrfkre
pnqrv--gavraqtmataspavnraapegkktlrkgsvivtgassglglatakalaet-g
kwhiimacrdflkteraaksagis-----------------kenytimhldlasldsvrq
fvdnfk--rsgrp------ldvlvcnaavylp----takeptftaegfelsvgtnhlghf
llsrllledlq-ksdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dmrgl--agglngl--nssamidggn-fdgak-------aykdskvcnm-limqefhr-r
fh--------e------etgitfaslypgcia---ttglfr--ehiplfrtlf----ppf
qkyitk-------gyvsedeagkrlaqvvsdpsl-t-ksgvywsw-----------nkds
a-------------------------------sf------------------enqlsqe-
asdad---karkvweiseklvgla
>6_Daucus_carota_18
---lqaasflpssfsinkegka----nvslketslfgvtfs--dslrtdfsslrtrrgcr
qisqt--gairsqavat-tpsvnratgegkktlrkgsviitgassglglatakalaet-g
kwhvimacrdflkaeraaksagmp-----------------kenytimhldlasldsvrq
fvetfr--rserp------ldvlvcnaavyfp----takeptytadgfelsvgtnhlghf
llsrlllddln-ksdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--agglngm--nssamidgae-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrtlf----ppf
qkyitk-------gyvseaesgkrlaqvvsepsl-t-ksgvywsw-----------nkds
a-------------------------------sf------------------enqlsee-
asdve---karkvwevseklvgla
>7_Pisum_sativum_20
---lqtasmlpasfsipkegkiga----slkdstlfgvssl-sdslkgdftssalrck-e
lrqkv--gavraetaapatpavnksssegkktlrkgnvvitgassglglatakalaes-g
kwhvimacrdylkaaraaksagla-----------------kenytimhldlasldsvrq
fvdnfr--rsemp------ldvlinnaavyfp----takepsftadgfeisvgtnhlghf
llsrllledlk-ksdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--aggltgl--nssamidggd-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrtlf----ppf
qkyitk-------gyvseeesgkrlaqvvsdpsl-t-ksgvywsw-----------nnas
a-------------------------------sf------------------enqlsqe-
asdae---karkvwevseklvgla
>8_Vitis_vinifera_22
---mqaaalvpsafsipke---gkg-sasfkesglfgvsls--dhvkadfsssalrnkrk
psv----gairaqtaat-tpaitratpegkktlrkgtvvitgassglglattkalaet-g
kwhiimacrdflkaeraarsagls-----------------kenytvmhldlasldsvrq
fvdnfk--rserp------ldvlvcnaavylp----takeptftadgfelsvgtnhlghf
llarlllddlk-qsdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgm--agglngl--nssamidgga-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------dtgitfaslypgcia---ttglfr--ehiplfrllf----ppf
qkfitk-------gyvseeesgkrlaqvvsepsl-t-ksgvywsw-----------nkns
a-------------------------------sf------------------enqlsqe-
asdad---karkvwelseklvrla
>9_Cucumis_sativus_24
---lqaaslvspalsipkegks----svclkdsslfgisfs--dhlksefssstlrckre
lnqqi--gairaqttatespavnkatpdgkktlrkgsvvitgassglglatakalaet-g
kwhvimacrdflkaeraaksagit-----------------kenytvmhldlasldsvrq
fvdnfr--qsgrp------ldvlvcnaavylp----takeptftaegfelsvgtnhlghf
llsrllledln-kssyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--agglngl--kss-midgge-fdgak-------aykdskvcnm-ltmqefhk-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrilf----ppf
qkfitq-------gyvsedeagkrlaqvvsepsl-t-ksgvywsw-----------nkns
a-------------------------------sf------------------enqlsqe-
asdae---karkvwelseklvgla
>10_Vitis_vinifera_32
---lqaasllpsavsihke---gks-naslketgffevsvs--dhlkaelslasl--qel
krrkl--pvgviraqtattpaisqaspegkktlrkgnviitgassglglatakalaet-e
kwhiimacrnflkadraaksagia-----------------kenytvmhldlaslesvrq
fadnfr--rsgrp------ldvlvcnaavylp----takeptftaegfelsvgtnhlghf
llsrlllddlk-qtdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--agglngi--ngspmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gyvseeeagkrlaqvvtdpsl-t-ksgvywsw-----------nkns
a-------------------------------sf------------------qnqlsqe-
asdae---karkvweiseklvgla
>11_Zea_mays_36
--lqaatsflpsalsarke-------gsvkdsasflgvrla-adglkldttalglrtvrv
srs----adiraqtaavsspsvtpaspsgkktlrkgtavitgassglglatakalaet-g
kwhvimacrdflkasraakaagmd-----------------kdsftvvhldlasldsvrq
fvrnvr--qlemp------idvvvcnaavyqp----takepsytadgfemsvgvnhlghf
llarellsdlq-ssdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--agglngv--gssvmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgvtfaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gyvseeeagkrlaqvvsdpsl-t-ksgvywsw-----------nkns
a-------------------------------sf------------------enqlsee-
asdad---kakklweiseklvgla
>12_Hordeum_vulgare_38
--lqaatsflpsalsarke--------gaakdsaffgvrla--dglkldatslglrtkrv
ntssv---airaqaaavsaptatpaspagkktvrtgnaiitgassglglatakalaes-g
kwhvimacrdylktaraaraagmp-----------------kgsytivhldlasldsvrq
fvknvr--qldmp------idvvvcnaavyqp----takepsftadgfemsvgvnhlghf
llarelledlk-asdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--aaglngv--gsaamidgae-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgvtfaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gyvseeeagkrlaqvvsepsl-t-ksgvywsw-----------nkns
a-------------------------------sf------------------enqlsee-
asdte---karkvwelseklvgla
>13_Arabidopsis_thaliana_42
------------------------------------------------------------
------------------------------------------------------------
-----macrdflkaeraaqsagmp-----------------kdsytvmhldlasldsvrq
fvdnfr--raemp------ldvlvcnaavyqp----tanqptftaegfelsvginhlghf
llsrlliddlk-nsdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--agglngl--nssamidggd-fvgak-------aykdskvcnm-ltmqefhr-r
fh--------e------dtgitfaslypgcia---ttglfr--ehiplfrtlf----ppf
qkyitk-------gyvseseagkrlaqvvadpsl-t-ksgvywsw-----------nkts
a-------------------------------sf------------------enqlsqe-
asdve---karrvwevseklvgla
>14_Nicotiana_tabacum_46
---lqaasllpsafsihke---gks-catlkdsslfgvals-ynq-kskfippaawnkel
tkkiaav-piraqiaat-tpavnqstseqkktlrkgnviitgassglglatakaiget-g
ewhvimacrdflkaekaaksvgip-----------------kenytvmhldlaslesvrq
fvdtfr--rsgrp------ldalvcnaavylp----takeptftadgfelsvgtnhlghf
llsrlllddlk-qsdyp-----------qkrliivgsitg-ntntlagn--vppka-nlg
dlrgl--sgglnsl--ncspmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
fh--------e------etgiafaslypgcia---etglfr--nhiplfralf----ppf
qkyitk-------gyvseaeagkrlaqvvrdpsl-s-ksgvywsw-----------nnts
s-------------------------------sf------------------enqlske-
asdae---karklwevseklvgla
>15_Arabidopsis_thaliana_50
--lqaaysllpstisiqke---gkf-naslkettftgssfs--nhlraekistlltik--
rrqkprfstgiraqtvtatppaneaspeqkkterkgtavitgassglglatakaladt-g
kwhvimacrnflkaekaarsvgms-----------------kedytvmhldlaslesvkq
fvenfr--rteqp------ldvlvcnaavyqp----takepsftaegfeisvgtnhlghf
llsrlllddlk-ksdyp-----------skrmiivgsitg-ntntlagn--vppka-nlg
dlrgl--asglngq--nss-midgge-fdgak-------aykdskvcnm-ltmqelhr-r
yh--------e------etgvtfaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gyvseeeagkrlaqvvsdpsl-g-ksgvywsw-----------nnns
s-------------------------------sf------------------enqlske-
asdae---kakklwevseklvgla
>16_Populus_trichocarpa_52
---lqaasilpstvsiyke---gks-naslketgffgvsvp-nnhlkaefdcslikskef
rkrelpvrtiraqtatt-tpaiteaapeakktlrkcvvvitgtssglglatakalset-g
qchvimacrnflkaeraaktagip-----------------kenytvmhldlaslesvrq
fvdtfr--rsgmp------ldvlvcnaavylp----takeptytaegfelsvgtnhlghf
llarlllddlk-ksdyp-----------tkrliivgsitg-ntntlagn--vppka-nlg
dlrgl--vgglndl--nsspmidgge-fdgak-------aykdskvcnm-ltmqelhr-r
yh--------e------etgitfaslypgcia---etglfr--nhiplfrtlf----ppf
qkyitk-------gyvseeeagkrlaqvvsdpsl-t-ksgvywsw-----------nkns
s-------------------------------sf------------------enqlske-
asnae---kalklweiseklvgla
>17_Ricinus_communis_54
---lkapstlpssisicke---gks-nvslkeagffgvsvslpnhlkaecnyslvrskel
kkratptgtiraqtatt-tpaideaapvakktlrkgnvivtgassglglatakalaet-g
ewnvimacrnflkaeraaksvgip-----------------kenytvmhldlasldsvrq
fagnfr--qsgmp------ldvlvcnaavyfp----iakeptftaegfelsvgtnhlghf
llarlllddlk-qsdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--vgglngl--nsspmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgvafaslypgcia---etglfr--ehiplfrllf----ppf
qkyitk-------gyvseevagkrlaqvvsdpsl-g-ksgvywsw-----------nqys
s-------------------------------sf------------------enqlsee-
asdte---kakklweiseklvgla
>18_Pinus_mugo_58
----------svafalqke---ggh-sasakdsaflgvslv--ehgkkefsfpvirakkv
tsrnt--nvpriraqtvaapvetkdapaskktdrkgnviitgassglglatakalges-g
kwhiimacrdflkaermarsvgip-----------------kenysvmhldlaslesvrq
fadnfr--rsgrp------ldvlvcnaaiylp----taklptytaegfelsvgtnhlghf
llsrllledlk-tsdfn-----------skrviivgsitg-ntntlagn--vppka-nlg
dlrgl--agglngv--nispmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gfvseeeagkrlaqvvsnpsl-t-ksgvywsw-----------nnns
g-------------------------------sf------------------enqlsee-
asdpe---kakklweiseklvgla
>19_Picea_sitchensis_60
----------svafalqke---ggh-sastkdsafrgvslv--ehgkkefsfpvirakkv
tsrnt--svpriraqtvaapvetkearaskktdrkgnviitgassglglatakalges-g
ewhiimacrdflkaermaravgip-----------------kenytvmhldlaslesvrq
fadtfr--rsgrp------ldvlvcnaavyfp----takvptftaegfemsvgtnhlghf
llsrllledlk-ksdfd-----------skrviivgsitg-ntntlagn--ippka-nlg
dlrgl--agglngv--nispmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gfvsedeagkrlaqvvsnpsl-a-ksgvywsw-----------nnns
a-------------------------------sf------------------enqlsee-
asdpe---kakkvweiseklvela
>20_Picea_sitchensis_62
---lhqthigsaafalqkegg-----hsasansaflgvsva--ehgkrefgfpvlrakkv
tsrnt--niarlraqtvaapvetkeapaskktdrkgnviitgassglglatakalges-g
ewhiimacrdfvkaermartvgip-----------------kenytvmhldlaslesvrq
fadnfk--hsgrp------ldvlvcnaavylp----takvptftaegfelsvgtnhlghf
llsrllledlk-ksdfk-----------skrviivgsitg-ntntlagn--ippka-nlg
dlrgl--sgrlngv--nsspmidgge-fdgak-------aykdskvcnm-ltmqefhr-q
yh--------e------etgitfaslypgcia---ttglfr--ehippfrllf----ppf
qkyitk-------gfvseeeagkrlaqvvsdtsl-t-ksgvywsw-----------nnds
a-------------------------------sf------------------enqlsee-
asdpe---karkvwaiseklvgla
>21_Musa_acuminata_66
------asflpsalsarke---gkv-actvkesaflgssil-----ehhkshpvlrtkre
snhsv--gvvkaqttavaapglnqsavhgkkvlrkgvvvitgassglglaaakalaet-e
kwhvvmacrdflkaekaaqsagma-----------------kenysimhldlasldsvrq
fvhafr--qsgrp------ldvlvcnaaiyrp----tartptytadgyemsvgvnhlghf
llanmlledlk-ksdyp-----------srrliilgsitg-ntntlagn--vppka-glg
dlrgl--aggldgr--nssamidgga-fdgak-------aykdskicnm-ltmqelhr-r
fh--------e------dtgitfaslypgcia---ttglfr--ehiplfrllf----ppf
qkfitk-------gfvsedesgqrlaqvvgdpsl-l-ksgvywsw-----------nnns
a-------------------------------sf------------------enqlsee-
asdav---kaqklweiseklvgla
>22_Hordeum_vulgare_subsp._vulgare_&gt_gi|227065|prf||1613434A_protochlorophyllide_oxidoreductase_76
-----------------------------kdtaaflgvssk----------------akk
aslavrtqvatapspvttspgstasspsgkktlrqgvvvitgassglglaaakalaet-g
kwhvvmacrdflkaskaakaagma-----------------dgsytvmhldlasldsvrq
fvdafr--raemp------ldvlvcnaaiyrp----tartptftadghemsvgvnhlghf
llarllmedlq-ksdyp-----------srrmvivgsitg-nsntlagn--vppka-slg
dlrgl--agglsga--sgsamidgdesfdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfsslypgcia---ttglfr--ehiplfrtlf----ppf
qkfvtk-------gfvseaesgkrlaqvvaepvl-t-ksgvywsw-----------nkds
a-------------------------------sf------------------enqlsqe-
asdpe---karkvwelseklvgla
>23_Physcomitrella_patens_subsp._patens_78
------------------------------------------------------------
-----------vraqsvaapastnastsskktdtkstviitgassglglatakvlads-g
ewhvimacrdflkaeraaksvgmp-----------------kenytvmhcdlsslnsvkq
fvdnfr--rsgrp------ldvlvcnaavylp----takeprytadgfelsvgtnhlghf
llanllmediqhkennn-----------srrviivgsitg-ntntvagn--vppka-nlg
dlrgl--aggldgv--rssvmidgge-fdgak-------aykdskvcnm-ltmqemhr-r
fh--------e------ktgvtfaslypgcia---ttglfr--ehyslfrtlf----ppf
qkyitk-------gyvseeesgrrlaqvvsdpsm-n-ksgvywsw-----------nnqs
g-------------------------------sf------------------enelsqe-
asdae---kakklwevseklvgla
>24_Triticum_aestivum_80
-----------------------------kdtaaflgvssk----------------akk
aslavrtqvatapssvttspgsatakpsgkktlrqgvvvitgassglglaaakalaet-g
kwhvvmacrdflkaskaakaagma-----------------dgsytvmhldlasldsvrq
fvdafr--raemp------ldvlvcnaaiyrp----tartptftadghemsvgvnhlghf
llarllmedlq-ksdyp-----------srrmvivgsitg-nsntlagn--vppka-slg
dlrgl--agglsga--sgsamidgdesfdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfsslypgcia---ttglfr--ehiplfrtlf----ppf
qkfvtk-------gfvseaesgkrlaqvvaepsl-t-ksgvywsw-----------nkds
a-------------------------------sf------------------enqlsqe-
asdpe---karkvwelseklvgla
>25_Zea_mays_82
------------------------------------------------------------
-----------attapvatpgsstaakdgkktvrqgvvvitgassglglaaakalaet-g
kwhvvmacrdflkaakaakgagma-----------------dgsytimhldlasldsvrq
fvdsfr--ragmp------ldslvcnaaiyrp----tartptftadgyemsvgvnhlghf
llarlllddmq-ksdyp-----------srrliilgsitg-ntntlagn--ippka-glg
dlrgl--aaglrgq--ngsamidgsesfdgak-------aykdskicnm-ltmqelhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrllf----ppf
qkfvtk-------gfvseaesgkrlaqvvsdpsl-t-ksgvywsw-----------nkds
a-------------------------------sf------------------enqlsqe-
asdpe---kakklweiseklvgla
>26_Marchantia_paleacea_var._diptera_84
------------------------------------------------------------
---------------avtapaetmnkpsskktatkstciitgassglglatakaladt-g
ewhvimacrdflkaeraarsvgip-----------------kdsytvihcdlasfdsvra
fvdnfr--rterq------ldvlvcnaavyfp----tdkepkfsaegfelsvgtnhmghf
llarllmedlq-kakds-----------lkrmiivgsitg-nsntvagn--vppka-nlg
hlrgl--agglngv--nsssmidgge-fdgak-------aykdskvcnm-ftmqefhr-r
yh--------a------etgitfsslypgcia---etglfr--nhvtlfrtlf----ppf
qkyitk-------gyvseeeagkrmaqvvsdpkl-s-ksgvywsw-----------nkds
g-------------------------------sf------------------enelsee-
asnpe---kakrlwelserlsgl-
>27_Zea_mays_88
------------------------------------------------------------
------------------------------------------------------------
-----macrdflkasraakaagmd-----------------kdsftvvhldlasldsvrq
fvrnvr--rlemp------idvvvcnaavyqp----takepsytadgfemsvgvnhlghf
llarellsdlq-ssdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--agglngv--gssvmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgvtfaslypgcia---ttglfr--ehiplfrllf----ppf
qkyitk-------gyvseeeagkrlaqvvsdpsl-t-ksgvywsw-----------nkns
a-------------------------------sf------------------enqlsee-
asdad---kakklweiseklvgla
>28_Physcomitrella_patens_subsp._patens_94
------------------------------------------------------------
---------apiraqgvaapadtkaptttkktdtkstviitgassglglatakvlads-g
ewhvimacrdflkaeraaravgmp-----------------kdsytvihcdlsslnsvkq
fvdnvr--qsgrp------ldvlvcnaavylp----takeprytadgfelsvgtnhlghf
llanmlmediqhkendt-----------nrrviivgsitg-ntntiagn--vppka-nlg
dlrgl--aggldgv--rssvmivgge-fdgak-------aykdskvcnm-ltmqemhr-r
fh--------e------ktgvtfaslypgcia---ttglfr--ehyqlfrtlf----ppf
qkyitk-------gyvseeeagkrlaqvvsdptl-n-ksgvywsw-----------nnqs
n-------------------------------sf------------------enelsqe-
asdae---kakklweiseklvnls
>29_Lycopersicon_esculentum_104
------------------------------------------------------------
------------------------------------------------------------
--------rdflkaekaakslgip-----------------kvnytvmhldlaslesvrq
fvdnfr--rsgrp------ldalvcnaavylp----takeptftadgfelsvgtnhlghf
llsrlllddlk-qsdyp-----------qkrliivgsitg-ntntlagn--vppka-nlg
dlrgl--sgglnsl--ncspmidgge-fdgak-------aykdskvcnm-ltmqeyhr-r
fh--------e------etgiafaslypgcia---etglfr--nhiplfrtlf----ppf
qkyitk-------gyvseeeagkrlaqvvrdpsl-s-ksgvywsw-----------nsts
s-------------------------------sf------------------enqlske-
asdae---karklwevseklvgla
>30_Pinus_strobus_106
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------renytvmhldlaslesvrq
fvdnfr--qsgrp------mdvlvcnaavylp----takvptftaegfelsvgtnhlghf
llsrllledlk-ksdfk-----------skrviivgsitg-ntntlagn--ippka-nlg
dlrgl--sarlngv--nsspmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehvppfrllf----ppf
qkyitk-------gfvseeeagkrlaqvvsdpsl-t-ksgvywsw-----------nnds
a-------------------------------sf------------------enqlsee-
asdpg---karkvweiseklvgla
>31_Chlamydomonas_reinhardtii_110
------------------------------------------------------------
-------------------------------tqqkqtaiitgassglglnaakalaat-g
ewhvvmacrdflkaeqaakkvgmp-----------------agsysilhldlsslesvrq
fvqnfk--asgrr------ldalvcnaavylp----takeprftadgfelsvgtnhlghf
lltnlllddlk-napnk-----------qprciivgsitg-ntntlagn--vppka-nlg
dlsgl--aagvp----aanpmmdgqe-fngak-------aykdskvacm-mtvrqmhq-r
fh--------d------atgitfaslypgcia---etglfr--ehvplfktlf----ppf
qkyitk-------gyvseeeagrrlaavisdpkl-n-ksgaywsw-----------sstt
g-------------------------------sf------------------dnqvsee-
vadds---kasklwdisaklvgls
>32_Acaryochloris_marina_MBIC11017_112
------------------------------------------------------------
-------------------------------q--kqtvvvtgassgvglyaakalalt-g
kwhvimacrnflkaetaaqsvgip-----------------rdsytvihldlacfesihr
fvkdfr--emgrs------ldalvcnaaiymp----llkkplhtaegyelnvgtnhlghf
llcnlmledlm-rsgyd-----------qrrliilgtvta-npkelggkipipapp-dlg
dmrgl--eagfk----apvsmingkk-fkpgk-------aykdsklcnm-ltmrelhr-r
fh--------e------stgitfsalypgcva---ttglfr--nhfalfrflf----pkf
qrfitg-------gfvteelagtrvaqvvsdplf-g-ksgvywsw-----------gnrq
kegrp---------------------------sf------------------eqemsne-
slddt---kaqrlwelseglvgls
>33_Fremyella_diplosiphon_Fd33_114
------------------------------------------------------------
-------------------------------r--kstvvitgassgvglytakamank-g
-whvvmacrnlakaeeaaqsvgip-----------------rdshtilhldlgsldsvrq
fvsnfr--atgkt------ldallcnaaiymp----likeplwspegyeltmttnhlghf
llcnlmledmk-nspyr-----------drrlvilgtvth-npdelggk--ipprp-dlg
nlegf--sagfk----apitmidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------e------stgitfsslypgcva---etplfr--nhyplfqkif----plf
qkyitg-------gyvsqdlsgervaavladpey-k-qsgaywsw-----------gnrq
kkdgk---------------------------sf------------------vqrvspq-
ardde---kaerlwdlseklvgla
>34_Amaranthus_tricolor_116
------------------------------------------------------------
------------------------------------------------------------
kwhvimacrdflkaeraaksagma-----------------kenytimhldlasldsvrq
fvnnfr--qsgrp------ldvlvcnaavylp----tareptytaegfelsvgtnhlghf
llsrllledlk-ksdyp-----------strliivgsitg-ntntlagn--vppka-nlg
dmrgl--agglngl--nssamidggd-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehiplfrflf----ppf
qkyitk-------g----------------------------------------------
------------------------------------------------------------
------------------------
>35_Microcoleus_chthonoplastes_PCC_7420_118
------------------------------------------------------------
-------------------------------q--kstvvitgassgvglyaakalaqr-g
nwhvvmacrnlekaqnaaqevgmp-----------------edsytimhidlgslesvrq
fvakfr--esgks------ldalvcnaaiymp----llkeplrspegyelsvatnhlghf
llshlmledlk-hssae-----------sprlvilgtvth-npdelggk--ipprp-dlg
qlkgf--eagfk----ephsmidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------e------stgivfsslypgcva---dtplfr--nhyplfqkif----plf
qkhitg-------gyvsqelsgervaavvadpey-s-qsgvywsw-----------gnrq
kkdgk---------------------------sf------------------vqkvspq-
arddq---kgermwelsaklvgva
>36_Amaranthus_tricolor_120
------------------------------------------------------------
------------------------------------------------------------
kwhvimacrdflkaeraakrigmp-----------------kdsytvmhldlaslesvrq
fvenfr--rsgmp------ldvlvcnaavylp----tdkeptftaegfelsvgtnhlghf
llsrlllddlk-qsdyp-----------skrliivgsitg-nsntlagn--vppka-nlg
dlrgl--agglngv--nsspmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
fh--------e------etgitfsslypgcia---etglfr--nhvalfrtlf----ppf
qkyitk------------------------------------------------------
------------------------------------------------------------
------------------------
>37_Anabaena_variabilis_ATCC_29413_122
------------------------------------------------------------
-------------------------------r--kstvivtgassgvglyaakalakr-g
-whvvmacrnlekaeqaaqevgip-----------------kdsytiihidlgsldsvrq
fvndfr--atgks------ldallcnaaiymp----likeplrspegyeltmttnhlghf
llcklmledlq-kssaa-----------dkrlvilgtvth-npdelggk--ipprp-dlg
nlegf--aqgfk----ppismidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------e------stgitftslypgcva---etplfr--nhyplfqkif----plf
qkyitg-------gyvsqelagervadviaapey-k-qsgaywsw-----------gnrq
kkdgk---------------------------sf------------------vqkvspq-
ardde---kaerlwdlseklvgl-
>38_Nostoc_sp._PCC_7120_126
------------------------------------------------------------
-------------------------------r--kstvivtgassgvglyaakalakr-g
-whvvmacrnlekaeqaaqevgip-----------------kdsysiihidlgsldsvrq
fvndfr--atgks------ldallcnaaiymp----likeplrspegyeltmttnhlghf
llcklmledlq-kssav-----------dkrlvilgtvth-npdelggk--ipprp-dlg
nlegf--aqgfk----ppismidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------e------stgitftslypgcva---etplfr--nhyplfqkif----plf
qkyitg-------gyvsqelagervadviaapey-k-qsgaywsw-----------gnrq
kkdgk---------------------------sf------------------vqkvspq-
ardde---kaerlwdlseklvgl-
>39_'Synechococcus_sp._JA-2-3B&apos_a_2-13__128'
------------------------------------------------------------
-------------------------------------vvitgassgvglysalalakr-g
-whvvmacrdldkayrvaqqvgip-----------------qgsytlmqidlaslasvrr
fveqfr--nwgrs------ldalvcnaaiymp----llkqplrspegyeltmatnhlghf
llchlmledlk-rstyp-----------drrlvilgtvth-npkelggk--ippqp-hlg
dlrgf--aqgfk----dpismadggk-fepvk-------aykdskvcni-ltmrelhr-l
fh--------e------stgitflslypgcva---ttalfr--hhyplfqklf----pwf
qknitg-------gfvsqelagervaqvvadpef-r-rsgfywsw-----------gnrq
rknak---------------------------pf------------------nqevsde-
aadda---kakllwdlseklvgv-
>40_Nostoc_punctiforme_PCC_73102_130
------------------------------------------------------------
-------------------------------r--kstvvitgassgvglyaakalaer-g
-wyvvmacrdvakaqlaaqsvgiph----------------qgsytimhidlgsldsvrq
fvknfr--asghs------ldalvcnaaiymp----likeplrspegyeltvttnhlghf
llcnlmledlk-ksss------------eprlvilgtvth-npdelggk--ipprp-dlg
dlqgf--aegfk----epismidgkk-fepvk-------aykdskvcnv-ltmrelhq-r
yh--------e------stgivfnslypgcva---etplfr--nhyplfqkif----plf
qkyitk-------gyvsqelagervaavvadpey-n-qsgvywsw-----------gnrq
kedgk---------------------------sf------------------vqkvspq-
arddd---kgdrlwqlsaklvgla
>41_Cyanothece_sp._PCC_7822_132
------------------------------------------------------------
-------------------------------r--kstaiitgassgvglqaakaladl-g
-wyvvmacrdiektkrvaqevgmp-----------------adsyniiyidlaslqsvre
fvkyfr--alsrp------ldalvcnaaiymp----llkeplwspdgyeltmatnhlghf
llcnlmlddlk-qsavk-----------paklvilgtvth-npnelggk--ipprp-dlg
nlqgf--aagfk----apysmidgka-fepvk-------aykdskvcni-ltmrelhr-r
yh--------a------stgiifnslypgcva---ttalfr--nhypkfqkyf----plf
qkyitg-------gfvseelsgqrvaqvvaepdf-a-qsgvywsw-----------gnrq
kkngq---------------------------af------------------vqkvstq-
agdda---kavrlwelseqlvgl-
>42_Cyanothece_sp._PCC_7424_134
------------------------------------------------------------
----------------------------------kstviitgassgvglqaakalals-g
-wyvimacrdlektrrvakevgmp-----------------sgsymiihidlaslesvrq
fvrdfr--aigrs------ldalvcnaaiymp----llkeplrspegyeltvatnhlghf
llcnlmledlk-kssas-----------ppklvilgtvth-npdelggk--ipprp-dlg
dlkgf--aegfk----epytmidgkk-fepvk-------aykdskvcni-ltmrelhr-r
yh--------e------stgivfnslypgcva---ttalfr--nhyplfqklf----plf
qkhitg-------gfvseelsgqrvaqvvtdpaf-a-qsgvywsw-----------gnrq
kkngn---------------------------af------------------vqkvssq-
ardde---naerlwelseqlvgl-
>43_Lycopersicon_esculentum_136
---lqaaallpstfsipke---gkt-saslkdsslfgisls--dhvksdfg-ssfkiksg
rkssl--gairaetmva-spgvtstpvtgkktlrkgcvvitgassglglatakalaet-g
kwhvimacrdflkaeraaksagmp-----------------kenytimhldlasldsvrq
fvdnfr--rsgnp------ldvlvcnaavyqp----takepsftaegfelsvgtnhlghf
llsrlliddlk-qsdyp-----------skrliivgsitg-ntntlagn--vppka-nlg
dlrgl--argldgl--nssamidggd-fdgak-------ayedskv--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>44_Cyanothece_sp._ATCC_51142_138
------------------------------------------------------------
----------------------------------kstviitgassgvglyaakaladr-g
-wyvvmacrnqpkahqaaqsvgip-----------------ldsytvmqidlgsldsvrq
fvkdfr--atgks------ldalvcnaaiymp----llkeplrspegyelsmttnhlghf
llcnlmledlk-rspap-----------ekrvvilgtvth-npnelggk--ipprp-dlg
nlegf--adgfk----epvsmidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------d------ntgivftslypgcva---dtplfr--nhyplfqkif----pwf
qknitg-------gyvsqelagervadvvtkpey-g-qsgsywsw-----------gnrq
kkdrka--------------------------af------------------vqkvspq-
aqdea---kaermwelseklvgl-
>45_Cyanothece_sp._CCY0110_140
------------------------------------------------------------
----------------------------------kstviitgassgvglyaakaladr-g
-wyvvmacrnqpkahqaaqsvgip-----------------ldsytvmsidlgsldsvrq
fvkdfr--atgks------ldalvcnaaiymp----llkeplrspegyelsmttnhlghf
llcnlmlqdlk-rspap-----------ekrvvilgtvth-npnelggk--ipprp-dlg
nlegf--aegfk----epvsmidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------e------ntgvvftslypgcva---dtplfr--nhyplfqkif----pwf
qknitg-------gyvsqelagervadvvtkpey-g-qsgsywsw-----------gnrq
kkdrka--------------------------af------------------vqkvspq-
aqdea---kaermwelseklvgl-
>46_Trichodesmium_erythraeum_IMS101_142
------------------------------------------------------------
----------------------------------kstvvitgassgvglhaakalakt-g
ewyvvmacrdiskaekvaqevgmt-----------------qdsytvmhldlaslevvkr
fvktfr--esgrs------lealvcnaavylp----llkepmrsidgyeisvatnhlghf
llcnlmledlk-kspak-----------dkrlvilgtvta-npkelggkipipapp-dlg
nlqgf--eqgfk----tpisminakk-fksgk-------aykdsklcnv-ltmrelhr-r
yy--------k------stgivfsslypgcva---dtplfr--nhyplfqklf----plf
qknitg-------gyvsqdlagervaavvkdpey-k-esgiywsw-----------gnrq
kkdrk---------------------------sf------------------vqevsde-
asddd---kaiklwelssklvgls
>47_Lyngbya_sp._PCC_8106_144
------------------------------------------------------------
-------------------------------q--kstvvitgassgvglqaakalakk-g
-wyvvmacrnlektekaaqtvgip-----------------adtytiipldlaslesvhq
fvktfr--esgks------ldalvcnaavylp----lekepqrsadgyelsvatnhlghf
llcnlmledlk-hsats-----------eprliilgtvta-npkelggkipipapp-dlg
nmqgl--eagfq----apismidgkk-fksgk-------aykdsklcnv-ltmrelhr-r
yh--------e------stgivfsslypgcva---ttalfr--nhyplfqkif----pwf
qknitg-------gyvseelagervamvvaepey-n-tsgvywsw-----------gnrq
kegrk---------------------------sf------------------mqevsne-
alddn---kaeklwklsaklvgma
>48_Nodularia_spumigena_CCY9414_146
------------------------------------------------------------
-------------------------------q--kstvvitgassgvglqaaralsqk-g
-wyvvmacrnlskaenaakslgme-----------------pdsytvmhidlgslesvrq
fvkdfr--asgks------ldalvcnaaiymp----likeplrspegyelsvatnhlghf
llcnllledlk-nspss-----------eprlvilgtvth-npkelggk--ipprp-dlg
dlqgf--aagfk----epiamidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------e------shgitfsslypgcva---ttalfr--nhyplfqkif----plf
qryitg-------gfvteeesgdrvaevvsdpqy-n-qsgaywsw-----------gnrq
kkngk---------------------------sf------------------lqevsne-
asddd---kaermwelsaklvgla
>49_Gloeobacter_violaceus_PCC_7421_148
------------------------------------------------------------
-------------------------------------viitgassgvglhaadslaqs-g
rwhvvmacrdkakaqnaaaslgmr-----------------pqsytivhldlaslasvrr
fvqdfr--algqp------ldalvcnaavytp----tareprytadgfelsvgtnhlghf
llcnllledlq-nspaa-----------eprlvilgtvth-npkelggs--ipprp-dlg
dlrgl--eqgfk----aphtmidgka-ynpvk-------aykdskvcnl-ltmrelhr-r
fh--------t------shkitfsalypgcva---tsglfr--esprlfqilf----pvf
qkyvtg-------gfvseaeaggrvaalvddpay-s-rsgvywsw-----------gnrq
kkdgk---------------------------sf------------------iqdvste-
asded---karrlwdlsaglvgla
>50_Synechococcus_sp._PCC_7335_150
------------------------------------------------------------
---------------------------------qssnviitgassgvglyaakslaar-g
-whvimacrnlpkaervakevgmp-----------------egsytilkldlssldsvrq
fvedfr--atgrs------ldalvvnaaiykp----slkspersvdgyeisvatnhlghf
llcnllledmk-kaahp-----------eprlvtlgtvta-npkelggkipipapp-dlg
dlkgm--elgfk----spiamidgkk-fkpgk-------aykdsklcnm-ltmlemhr-r
yh--------d------etgivfnalypgcva---esdlfr--dapklfqtif----pff
qknitg-------gyvseeesgdrvakvvdeegf-n-ksgvywsw-----------gnrq
dknre---------------------------af------------------cqevsne-
aadan---kagklwdlseklvgla
>51_'Thermosynechococcus_elongatus_BP-1_152'
------------------------------------------------------------
-------------------------------------viitgassgvglyatkalanr-g
-whvimacrnlekaeqaaknlqip-----------------peaytilhldlsslasvrg
fvesfr--alnrp------lralvcnaavyyp----llkepiysvdgyeitvatnhlghf
llinllledlk-nspes-----------dkrlvilgtvta-nrkelggkipipapp-dlg
nlegf--ekgfk----kpiamingkp-fksgk-------aykdsklcnm-ltarelhr-r
fh--------e------stgivfnslypgcva---dtplfr--hhfplfqklf----plf
qkkitg-------gyvsqelagervamvvadpef-r-qsgvhwsw-----------gnrq
kegrk---------------------------af------------------vqelsae-
asdeq---karrlwelseklvgla
>52_Crocosphaera_watsonii_WH_8501_154
------------------------------------------------------------
-------------------------------r--qstvvitgassgvglyaakaladr-g
-wyvvmacrnqpkahqaaqslgia-----------------ldaytvmhidlgnldsvrq
faqdfr--atgkt------ldalvcnaaiymp----llkeplrspegyelsmttnhlghf
llcnlmledls-hssap-----------ekrmvilgtvth-npdelggk--ipprp-dlg
nlegf--adgfk----epismvdgkn-fepvk-------aykdskvcnv-ltmreldr-r
yh--------e------stgivftslypgcva---dtplfr--nhyplfqkif----pwf
qknvtg-------gyvsqelagervadvvtkpey-g-esgsywsw-----------gnrq
kkdrqa--------------------------af------------------vqnvspq-
aqdea---kaekmwnlseklvgla
>53_'Arthrospira_maxima_CS-328_156'
------------------------------------------------------------
-------------------------------q--kstvivtgassgvglyaakaladr-g
-ahvimacrnlekaeaaaqelgip-----------------edsrtilhidlgslesvrr
finsfr--atgrt------leglvcnaaiymp----likeplrspegyeltmttnhlghf
llcnvmmedmk-rspae-----------dkrmvilgtvth-npdelggk--ipprp-dlg
dlegf--akgfr----epvsmidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------e------etgitftslypgcva---dtplfr--nhyplfqkif----pif
qkyitk-------gyvsqelagervaavvldeey-r-qsgaywsw-----------gnrq
kkgrq---------------------------sf------------------vqrvspq-
ardee---raekmwnlslklvela
>54_Leptolyngbya_boryana_160
------------------------------------------------------------
---------------------------------qkptvvitgassgvglyaakalvkr-g
-whvvmacrnlekadsaakslgms-----------------pdsytlmhidlgsldsvrk
fvtqfr--esgks------ldalvcnaavhmp----llkepmrspegyelsvatnhfghf
llcnllledlk-hsthn-----------dprliilgtvta-nskelggkipipapa-dlg
dlsgl--eagfk----apiamidgkp-fkagk-------aykdsklcnm-itsrelhr-r
yh--------d------stgivfntlypgcva---dtplfr--nslpvfqkvf----pwf
qknitg-------gyvsqelagertaqvvadpef-k-qsgvhwsw-----------gnrq
kegre---------------------------sf------------------vqelsek-
vtdda---kakrmwelseklvgla
>55_Cyanothece_sp._PCC_8801_164
------------------------------------------------------------
-------------------------------tqdqktviitgassgvglyaakaliqkwg
-yhvvmacrnldktyrvaqelgfp-----------------sdsytvlpidlgslgsvry
fvqafr--etkkp------ldallcnaaiymp----llkeplrspegyeltmttnhlghf
llcnllledlq-rsssp-----------eprvvilgtvth-npdelggk--ipprp-dlg
nlegf--eagfv----ephsmidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------d------stgitfsslypgcva---ttalfr--nhyplfqklf----plf
qkhitg-------gfvseelagervadvvaapey-n-qsgsywsw-----------gnrq
kkdre---------------------------sf------------------vqqvspq-
ardde---kaekmwdlsaqlvgla
>56_Cyanothece_sp._PCC_8802_166
------------------------------------------------------------
-------------------------------tqdqktviitgassgvglyaakaliqkwg
-yhvvmacrnldktyrvaqelgfp-----------------sdsytvlpidlgslgsvry
fvqafr--etkkp------ldallcnaaiymp----llkeplrspegyeltmttnhlghf
llcnllledlq-rsssp-----------eprvvilgtvth-npdelggk--ipprp-dlg
nlegf--eagfv----qphsmidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------d------stgitfsslypgcva---ttalfr--nhyplfqklf----plf
qkhitg-------gfvseelagervadvvaapey-n-qsgsywsw-----------gnrq
kkdre---------------------------sf------------------vqqvspq-
ardde---kaekmwdlsaqlvgla
>57_Synechocystis_sp._PCC_6803_168
------------------------------------------------------------
----------------------------------kptviitgassgvglygrkalidk-g
-whvimacrnldktqkvadelgfp-----------------kdsytiikldlgyldsvrr
fvaqfr--elgrp------lkalvcnaavyfp----lldeplwsaddyelsvatnhlghf
llcnllledlk-acpda-----------dkrliilgtvta-nskelggkipipapp-dlg
nfegf--eagfk----kpiaminnkk-fksgk-------aykdsklcnm-lttrelhr-r
fh--------q------etgivfnslypgcva---dtplfr--nhyslfrtif----pwf
qknvtk-------gyvsqelagervamvvaddkf-k-dsgvhwsw-----------gnrq
qagre---------------------------af------------------vqelseq-
gsdaq---kaqrmwdlseklvgl-
>58_'Phaeodactylum_tricornutum_CCAP_1055/1_170'
------------------------------------------------------------
-------------------------------------vvitgassglglncattlakt-g
ryfvvmacrdvekgkqvakekglp-----------------dnsyvvmklelgnlqsvrd
fvsnlkafkaarp------lthlicnaavykp----kdpepawtddgfemsmgvnhlghf
llvhllmddms-rak-------------garvcivgsitg-ntntvgggl-vypqa-dlg
klqgf--ekgak----kpvamadgkp-ffgak-------aykdskvcnm-mtvselnr-l
yh--------k------dtgivfssmypgcia---etalfr--ekrpwfrkaf----pwf
mkyvtg-------gyvgmeeagerlaqviddpqc-t-ksgvywsw-----------ngga
qt---vgrwspdgkpr-----gaggsgg---eif------------------enqqsda-
vrdlp---takkmwklsreavgls
>59_Thalassiosira_pseudonana_CCMP1335_172
-----------------------------ssqirtqrlttsnnnniiamptntysqspti
lsemlttaelpqklyfpkedkepakvlgglkigtrkltvitgassglglncaatlakt-g
rhfvvmacrdvekgkrvakefgmp-----------------ddsyvvmklelgslqsvrd
fvfnlkafksarp------vnnlicnaavykp----tdpepawtddgfeqsmginhfghf
llvnlmvddla-kak-------------garccivgsitg-nsntv--gl-vypra-dlg
nlqgf--aqgak----epiamadgkp-ffgak-------aykdskvcnm-mtvselhr-r
yh--------d------stgiafssmypgcia---etqlfr--ekrpwfqkaf----pwf
mkyvtg-------gyvgmeeagerlaqvvddpqc-t-ksdvywsw-----------ngga
qq---vgrwsddgkpk-----gaggsgg---eif------------------eneqsda-
vrdre---taqkmwdysvravgl-
>60_Cyanothece_sp._PCC_7425_174
------------------------------------------------------------
-------------------------------q--kptviitgassgvglyaakalank-g
-fhiimacrdlhkagqaaqtvgip-----------------qgsyslmhidlgdldsvrr
farevs--asgrp------lkalvcnaaiymp----llkeplrspegyeltmttnhlghf
llcnllledlk-qsrve-----------dkrvvilgtvth-npdelggk--vyprp-dlg
kfegf--aagfk----epvsmvdgkk-fepvk-------aykdskvcnv-ltmkeldr-r
yh--------d------ttnitfsslypgcva---dtplfr--nhyptfqklf----plf
qkyitg-------gyvsqelagervaqvvadpef-r-esgaywsw-----------gnrq
kqgrk---------------------------af------------------mqkvsrq-
arnnd---kaeqmwvlseklvgla
>61_Synechococcus_elongatus_PCC_6301_178
------------------------------------------------------------
---------------------------------qqptviitgassgvglygakalaar-g
-whvvmacrnlqkaaeaakslgin-----------------penyslmeidlgslasvrr
fvdqfr--atgrs------ldalvcnaavylp----rlkepqrspegyeisvatnhfghf
llcnlllddlk-rspap-----------ekrlvilgtvta-nskelggkipipapa-dlg
nlegl--eagfk----apiamidgkk-fkpgk-------aykdsklcnm-ittrelhr-r
fh--------d------stgivfgslypgcva---dtplfr--ntpklfqkif----pwf
qknitg-------gyftqelagervaqvvadpef-k-tsgvhwsw-----------gnrq
qkdrq---------------------------sf------------------vqelsdk-
asddr---taqrlwdlsaklvgl-
>62_Ostreococcus_tauri_182
----------------------------------------------------rtrrapai
rqpstsrarrtstlavaraagsssqnimpsngankpvaiitgassglglytakaliek-g
-yfvvmavrdprkgetkanelgfd-----------------kksyavmycelgelasvre
fcsgfrrspyvkn------fqalvcnaalylp----natvpsytkdgfeecvgvnhlahh
lmclellddlakapdan-----------mkrliivgsvtg-ntntlagq--vppra-glg
dlsgl--rngfknsdrnqgahidgsr-figak-------aykdsklcnm-ldikvfae-r
yg--------e------stgikfstmypgcia---dsnlfr--nhtpffrwlf----pil
qknvtk-------gyvseeeagqrlasivydpry-t-eqgaywawkgggdqlwdnfnnnn
edtrti--------------------------af------------------nnkpsre-
grdma---kanamfdistelvg--
>63_Pinus_mugo_184
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------k-ksdfk-----------skrviivgsitg-ntntlagn--ippka-nlg
dlrgf--sarlngv--nsspmidgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------e------etgitfaslypgcia---ttglfr--ehippfklsf----pps
qkyitk-------gfvseeeagkrlaqvvsdpsl-t-ksggywsw-----------nnds
s-------------------------------sf------------------enqlsee-
asdpr---karkvwgiseklvgla
>64_'Microcystis_aeruginosa_NIES-843_186'
------------------------------------------------------------
-------------------------------k--kptviitgttsgvglyaakslaqr-g
-wfvvmacrdipkmeqaakelnip-----------------rdnyciefidlgsldsvrr
fvknfr--algrs------ltalvcnaaiylp----llkeplrspdgyelsmatnhlghf
llsnllledlk-nspsp-----------drrlvilgtvth-npdelggk--ipprp-dlg
dlegf--akgfk----epitmadgkk-fesvk-------aykdskvcnv-ltmrelhk-r
yh--------q------stgitftslypgcva---dtplfr--nhypffqqff----pwf
qknitg-------gyvsqelagervamvvadpey-r-qsgaywsw-----------gnrq
kkegk---------------------------sf------------------vqrvspq-
ardde---rgakmweysaklvgla
>65_Microcystis_aeruginosa_PCC_7806_188
------------------------------------------------------------
-------------------------------q--kptviitgttsgvglyaakslaqr-g
-wfvvmacrdipkmeqaakelnip-----------------rdnyciefidlgslnsvrr
fvknfr--algrs------ltalvcnaaiylp----llkeplrspdgyelsmatnhlghf
llsnllledlk-nspsp-----------drrlvilgtvth-npdelggk--ipprp-dlg
dlegf--akgfk----epitmadgkk-fesvk-------aykdskvcnv-ltmrelhk-r
yh--------e------stgitftslypgcva---dtplfr--nhypffqqff----pwf
qknitg-------gyvsqelagervaivvadpqy-r-qsgaywsw-----------gnrq
kkegk---------------------------sf------------------vqrvspq-
ardee---rgekmweysaklvgla
>66_Bigelowiella_natans_192
------------------------------------------------------------
--------------------------------------vitgassglglntarslies-g
kwhvvmavrdpekarreaermgfp-----------------kdrysieevelssfesvrr
makkl---krgrq------idtlicnaalylp----ahqnpeytvdgyetslqvnhlshf
lllnlllptik-ksr-------------dprvivvgsitg-ntntvggga-vwpwa-dlg
klnglaekagte----kgpemingga-wngak-------aykdsklanm-mtifeadr-r
lh--------k------dsgvtfstmypgcia---etglfr--dkkpwfrklf----plf
mryvtg-------gyvseweagdrlaevassdrc-k-esgvywgw-----------ngaa
kt---vaylkpgtdasnrgltgaggagg---sie------------------elppspe-
arnae---karrlwelsakavgl-
>67_Synechococcus_sp._RCC307_194
------------------------------------------------------------
--------------------------------------ivtgassgvglwttkalidq-g
-wtvvmacrdgakaqqalvelglgr----------------paeaiilpldlsdfesvka
fvelfr--glnrp------ltalvinaavykp----llkepewsaqgyelsmatnhlghf
llarlllddlk-aspaa-----------dkrlitlgtvta-nskelggkipipapa-dlg
dlsgf--aqgfk----apiamasgkk-fkpgk-------aykdsklcnm-itslelhr-r
fh--------g------atgisfsslypgcva---dtplfr--nslpafqkif----pwf
qknitg-------gyvsqalagervaqvvadpaf-r-ssgahwsw-----------gnrq
kkdgk---------------------------qf------------------eqelsdk-
asdpa---talrvwdlssalvgl-
>68_Cyanobium_sp._PCC_7001_210
------------------------------------------------------------
-----------------------------------gtvlitgttsgvglhatkalvdr-g
-wtvvtanrdpvraaaaaeslgip-----------------saqlhhlridlgdldsvra
gvetlvs-slgrp------ldalvinaavykp----rlkqperspqgyelsmatnhlghf
lliqlllpdle-hsthp-----------srrvvilgtvta-nskelggkipipapa-dlg
dlsgf--aagfk----apiamasgka-fkpgk-------aykdsklcnm-ittqelhr-r
lh--------g------stgivftslypgcva---dtplfr--ntprlfqkif----pwf
qknvtg-------gyvsqalagervaqvvadpef-a-vsgvhwsw-----------gnrq
kqggr---------------------------qf------------------sqelsdk-
asnpd---tarkvweyslklvel-
>69_Ostreococcus_lucimarinus_CCE9901_212
------------------------------------------------------------
--------------------------------------ivtgsssglglytakalikn-g
-yfvvnavrspekmqvkanelgld-----------------essyaimylelgdlqsvrd
fatefrrskyvkn------fqalvcnaalylp----natvpsytkdgfeecvgvnhlghh
llsllllddlaeapdan-----------mkrliivgsvtg-ntntlagq--vppra-glg
dmsgl--rngfknsdrnqgalidgtr-figak-------aykdsklcnm-ldikafae-r
fg--------e------stgikfstmypgcia---dsnlfr--nhtaffrwff----pil
qknvtk-------gyvseeeagerlasivydpry-s-eqgaywawkgggdqlwdnynnnn
ddtrti--------------------------af------------------nnkpske-
grdma---kanevfdistelvg--
>70_Dinoroseobacter_shibae_DFL_12_214
------------------------------------------------------------
--------------------------------------ivtgassgvglhatkslidr-g
-whvtmacrdlakaeaaarsldld-----------------pgryalahldlgslasvra
fhania--rdhds------ldalvcnaavykp----rltqpgrspdgfeisvatnyfghf
llanlmlplle-gap-------------sprlitlgtvta-nseefggkvpipapa-dlg
dfagl--kagfr----apvamidgkp-fkagk-------aykdsklctm-mmsrelht-r
hh--------a------rtgivfatlypgcva---dtplfr--dtpkafqtif----pwf
qknvtk-------gyvsqalsgervamvvadpef-a-qsgvhwsw-----------gnrq
regrs---------------------------af------------------aqglstk-
atdaa---rsaelweltaaltgl-
>71_Prochlorococcus_marinus_str._MIT_9313_220
------------------------------------------------------------
-----------------------------------gtvlitgttsgvglyackalvyr-g
-wqvitanrhplravaaaervgip-----------------aaqlthlrmdlsdlqsvrd
gvetllg-sleqp------ldalvcnaavyqp----rlrkpkrsaqgyelsmatnhfghf
lliqlllenlg-kak--vfqsargsylsaarvvilgtvta-nykelggkipipapa-dlg
nlsgf--eqgfh----apismasgks-fkpgk-------aykdsklcnm-ittqelhr-r
lh--------e------qsgilftslypgcva---dtplfr--ytpkifrflf----pif
qrlitg-------gyvtqakagqrvaqvvtnpef-g-vsgvhwsw-----------gnrq
kknre---------------------------sf------------------rqelser-
atdpi---takrvwelsmklvgl-
>72_Synechococcus_sp._WH_8102_228
------------------------------------------------------------
-----------------------------------gtvlitgttsgvglnatcalvkr-g
-wtvitanrspqraaaaaddmdlp-----------------kerlqhvlmdlgdldsvrr
avd-----alpdr------ldavvcnaavykp----klkqperspqgyeismatnhlghf
llvqlllgrlq-nsshp-----------srrvvilgtvta-nskelggkipipapa-dlg
dlsgf--eagfk----ypvamasgkp-fkpgk-------aykdsklcnm-istqelhr-r
lh--------g------esgitftslypgcva---dtplfr--ntpkafqtif----pwf
qknitg-------gyvsqalagervadvvahpdf-a-esgvhwsw-----------gnrq
kkdgq---------------------------qf------------------sqelsdk-
atdpd---tarrvwdlsmqlvgl-
>73_Oryza_sativa_Indica_Group_230
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------midgge-fdgak-------aykdskvcnm-ltmqefhr-r
yh--------g------etgvtfaslypgcia---ttglfr--ehvplfrllf----ppf
qkyitk-------gyvseeeagkrlaqvvsdpsl-t-ksgvywsw-----------nnns
a-------------------------------sf------------------enqlsee-
asdpe---kakkvwelseklvgla
>74_Paulinella_chromatophora_232
------------------------------------------------------------
-----------------------------------gtvlvtgtssgvglytakaliak-g
-whvisvsrniekaklalqnfggn-----------------nanlthltidlgdlnsvkn
cvhefr--rlgkt------ldalvcnaavylp----rlkepiispqgyeismatnhlghf
lliqlllsdlq-lsrhp-----------srrivilgtvta-nskelggkipipapa-dlg
dlsgf--eegfq----mpismanskk-fkpgk-------aykdsklcnm-itarelhr-r
lh--------n------stgiifsslypgcva---dtplfr--ntpsafqtif----pwf
qknitg-------gyvsqglagervaavvtdrnf-a-qsgvhwsw-----------gnrq
krngk---------------------------ef------------------vqelsnq-
asdeg---tskklwdlsmnlvdi-
>75_Oryza_sativa_Indica_Group_242
lqaatttsflpsalsarke--------gavkdsaflgvrlg--dglkletsalglrtkrv
stssv--airaqasaavssptatpaspsgkqtlrkgtavitgassglglatakalaet-g
rwhvvmgcrdflkasraakaagme-----------------kgsytivhldlasldsvrq
fvgnvr--rlgmp------vdvvvcnaavyqp----takqpsftadgfemsvgvnhlghf
llarelladlt-ssdyp-----------skrliivgsitg-ngn----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>76_Thalassiosira_pseudonana_CCMP1335_248
------------------------------------------------------------
-------------------------------------vvitgcssglgretvknllat-d
kyhvvgavrdvdkmeavaeldgfn-----------------mdnfkimelelnsfesvdk
fcdnlkdyqlakp------idrlicnagvyqp----sldyakwsvdgheqtmqinflshf
lmisklmpgms-vap-------------dprvimvgsvtg-ndntvgggg-vypia-dlk
nldgf--kagfk----npiamadgyg-figak-------aykdsklclm-mtsnflhs-k
yh--------r------ntgiafssiypgcia---etplfr--ekrawfrkyf----pif
mkyitg-------gyvgvdeagqrlfqvahdprc-s-ksgvywsw-----------n---
------------------------------------------------------------
------------------------
>77_'Phaeodactylum_tricornutum_CCAP_1055/1_250'
------------------------------------------------------------
--------------------------------------iltgassglgrktamallrt-g
eyhvigavrdldkmeavaevdgfd-----------------lenftpmycelnsfesvrs
fcenveefrmskp------idrlicnagvyqp----slehakwsldnheqtmqinflshf
lmistmmksmm-esp-------------dprvimvgsvtg-ndntvgggg-vypia-dlh
elegl--kqgfk----npiemadgyg-figak-------aykdsklclm-mmanflht-k
yn--------k------ltgisfasmypgcia---esplfr--ekrpwfrkyf----pif
mkfitg-------gyvgeheagqrlfqvahdprc-s-ksgvywsw-----------nggp
regrgveaiekggqis-----ggggagggwdsif------------------endqsgk-
vldve---talnlfkystditg--
>78_&apos_Nostoc_azollae&apos__0708_252
------------------------------------------------------------
-------------------------------r--qstvvitgtssgvglqaakalaqt-g
qwqvvmacrnlskaeeaaqsvgir-----------------qgsytiihldlasldsvrq
fvkdfr--atgrs------ldalvcnaaiymp----likeplwspdgyelsvatnhlghf
llcnlmledlk-kssas-----------eprlvilgtvth-npnelggk--ipprp-dlg
dlkgf--eagfk----apysmidgkk-fepvk-------aykdskvcnv-ltmrelhr-r
yh--------e-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>79_Cucumis_sativus_256
------------------------------------------------------------
------------------spavnkatpdgkktlrkgsvvitgassglglatakalaet-g
kwhvimacrdflkaeraaksagit-----------------kenytvmhldlasldsvrq
fvdnfr--qsgrp------ldvlvcnaavylp----takeptftaegfelsvgtnhlghf
l-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>80_Prochlorococcus_marinus_str._MIT_9202_268
------------------------------------------------------------
----------------------------------kglvlitgttsgvglntlkpllrf-g
-weviavnrsnkraikiakdyltked---------------iknvhfmeidlsdlddvrk
gcdeile-rfkkp------inslicnaavykp----rlkrperspqgfensmavnhfghf
lminlllenil-ssegeivlngkttlf-kpritvlgtvta-nyselggripipapa-dlg
dlsgf--kngfl----spismangkk-fkpgk-------aykdsklcnm-vtvqelsk-r
yp---------------aekiivnslypgcva---dtklfr--dtpwlfrllf----pif
qkfitr-------gyvsqrlagervakvatykef-a-kpsvhwsw-----------gnrq
rtgrk---------------------------af------------------sqklskr-
iidtk---tsqqtydltsqlvgl-
>81_Cupressus_sempervirens_274
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ptftaeg-elsvgtnhlghy
lls-llledlk--sdck-----------skrvmivgsitg-nt-tlagt--ippka-nlg
dlrg---aarcngv--nss-lidge--fdgak-------aykdskacnm-ltmqd-hr-r
yh--------e------vtgit-asly-gcia---ttglfr--ehvp-frlll-------
-qyitn-------gfvseeeag-rlaqvvsdpsl-t-ksgvywsw-----------nnds
a-------------------------------s---------------------------
------------------------
>82_Pinus_taeda_276
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------cia---ttglfr--ehvppfrllf----ppf
qkyitk-------gfvseeeagkrlaqvvsnpsl-t-ksgvywsw-----------nnns
a-------------------------------sf------------------enqlsee-
asdpe---kakklweiseklvgla
>83_&apos_Nostoc_azollae&apos__0708_278
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------t-----
------------------------------------------------------------
------------------------------------------------------------
-------------------gitfsslypgcva---ttalfr--dhyplfqklf----pif
qkyitg-------gfvseeeagkrvaevvadpay-n-qsgmywsw-----------gnrq
kkngk---------------------------sf------------------vqkvsne-
asded---kaerlwelsaklvgla
>84_Ostreococcus_lucimarinus_CCE9901_280
------------------------------------------------------------
-------------------------------tetkkrvvitgsnsgigldaatklaas-g
dwvvvlacrtrakaeaakanilsatnad-------------ganiecvecdlssldsvra
fvrevr--ktgg-------vdalclnagveys----gdpvvhrtrdgfeetfgvnhlghf
llanllledle-kssea-----------hprivvtasevh-dpaspggsvgsgahigdlr
gle----rdg------aafemadge-afdadk-------aykdsklanm-lfmyeler-r
lq----------arn---skitvnafgpglit---rtglfr--nq--------nplfvkv
fdfatneifh---vaetvsgggnclvfmltdpsleg-sggvywnn---------------
--------------------------------dl-spgapp-slvaaghkfaqtnssve-
sndav---eaqklwklseslvgla
>85_Ostreococcus_tauri_282
------------------------------------------------------------
----------------------------------kkrvvitgansgiglsaattlals-g
ewtvalacrtkekseqaraemvsrgva--------------esdvecyecdladldsvra
carelr--rngs-------idalalnagvefs----gdpvvhrtaqgleetvgvnhlghf
lltnllledle-rsela-----------hprivvtasevh-dpaspggsvgngatlgsle
gfe----rdg------krfemadgg-nfdadk-------aykdsklmnm-lftyeler-r
lr----------erg---skitvnafgpglit---rtglfr--hq--------nplfvkv
fdfatnevfh---vaetvdrggdclvymleepsleg-vggvyfnn---------------
--------------------------------gl-apgtpp-----tghkfertdssve-
snnqd---earklwvisedfvgl-
>86_Lycopersicon_esculentum_284
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------f----ppf
qkyitk-------gyvsetesgkrlaqvvsdpsl-t-ksgvywsw-----------nkds
a-------------------------------sf------------------enqlsee-
asdae---karkvwevseklvgla
>87_Cyanothece_sp._ATCC_51142_286
------------------------------------------------------------
-------------------------------------viisgannglgyacakelaln-k
diylvlacrdnekatkaveklknttk---------------nnqieyicldlaslqsvrq
feakfa--qknlpp-----lgiiicnagvqf------iqrrtytddgmettfavnhlghf
llvnlllkhlk-p---------------pgriifvssdth-dpskitgm----ppp-nfq
dpn-------llarpeldptlkdkgvsdlgri-------ayttsklcni-lcayelsr-r
ld--------kqrlsteehpitvnvftpglmp---gtglaq--dypplakivwdyilplf
-sffpk--------intpqqsgralarlvedpqlkn-vtgkyfsg---------------
--------------------------------lq------------------miessqe-
sydve---kaqqlwdksvelvgl-
>88_Taraxacum_officinale_288
------------------------------------------------------------
----------ktkavatttpsvtqtskggkktlrkgtviitgassglglatarslaet-g
kwhvimacrdflkaeraakssgmp-----------------kenytvmhldlasf-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>89_Lycopersicon_esculentum_292
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------f----psi
qkfitk-------gfvseaesgkrlaqvvsdpsl-t-ksgvywsw-----------nkns
s-------------------------------sf------------------enqlsee-
asdve---karkvwevseklvgla
>90_Thalassiosira_pseudonana_CCMP1335_302
------------------------------------------------------------
----------------------------------kqrilitgsnsgigldaaqrlalr-g
h-evvlacrtldkaiaaadkiktniandsedavdaialik-tlkltpmecdladlksids
fvnelk--ktssgeegrmmfdavcynaglsrnt---aatdvlrtkqgfeltvgtnhfghf
ylnhlmmplik-kdg--------------grmvvtasgvh-dpdspggaqgipatlgdla
gleqavargd------gkfdmvdgg-efnadk-------aykdsklcnv-lftrelqr-r
lk----------esg---snvkvncfnpgliv---gtglfr--dq--------nqvftkv
fdvaatslfk---vgetthwgggaleymalssevanergglfyt----------------
---------------------------------a-ppgsskygddafgrefkatqaske-
arasdvdgkakrfwelseklvgv-
>91_Potamogeton_distinctus_322
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---itk-------gfvseeeagkrlaqvvrdpsl-t-ksgvywsw-----------naas
a-------------------------------sf------------------enqlsqe-
asdag---kakkvwelseklvgla
>92_Zea_mays_332
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----q-------gfvseaesgkrlahvvsdpsl-t-ksgvywsw-----------nkds
a-------------------------------sf------------------enqlsqe-
asdpe---kakklweiseklvgla
>93_Microscilla_marina_ATCC_23134_334
------------------------------------------------------------
-------------------------------------vivtgansglglytskhlllq--
dyavvlacrnlkkaakaqkwlhkktg---------------kkrtkiahldlasfnhirk
fclntplnn----------vygvvcnagisy------ahptrftqdgieetfgvnhlghf
llvnlllgkaq-n---------------lqriavvssdah-npdiqgyh----ppp-yye
ral-------elaypd-dsrvinweke--gal-------ryansklcnv-lfvyhlae-e
lk--------k----thrqhilvnafnpgfip---gtglgk--nsspvskflwfnvlplf
-srfsk-------airtanesgkalaslisea---n-asgkyydg---------------
--------------------------------fk------------------ekpsskq-
sydkk---qaqklwwrseelahl-
>94_Vitis_vinifera_336
------------------------------------------------------------
--------------------------------------ivtgassgigtettrvlalr-g
v-hvvmgvrnmaagqevkeaivkeip---------------takvdvmeldlssmasvrk
fasefn--ssglp------lnilinnagttg------pym--lskdniemlfatnhlghf
lltsllldtmk-kttqesgk--------egrivivsseghrftyr---------ggirfd
nin------------------dks--gysspf-------aygqsklanv-lhanelar-r
fk----------edg---vditanslhpgaiv----tnifr--h-ss------------i
lsglvntvgky--vlknvqqgaattcyvalhpqvkg-vsgqyfsd---------------
--------------------------------cn------------------iakpgaq-
akdpe---lakklwefstgli---
>95_Gymnochlora_stellata_338
------------------------------------------------------------
-------------------------------------vmitgantgigraaaeqlcta-g
h-svivvcrtivkaqktieeikatfgdkv------------tgnliplecdvsdldsvrr
lvrdfr--dlnlp------lnvlvanagislnaqekgdeftqrskdgfeltiatnylghf
lltnlllpdle-ksg-s-----------dsrivitgsevh-dpsspggsvgpgatlgdls
glk-------------skapmvdgg-pydadk-------aykds---nh-vfmlelqr-r
lk----------akg---vtvtansfgpglit---rsaffk--nq--------nglfsrl
fdfatndifh---vaetvdfggaclsymalskdleg-kggl-wln---------------
--------------------------------av-qpgkp---------vfeqlqpsie-
ardtk---kakmlydmsleavgla
>96_Synechococcus_sp._WH_7805_346
------------------------------------------------------------
-------------------------------------ilitgassgigleatrrlals-g
h-qltlfcrtpergeqtrsqlvaagam--------------psqvswlladladlrsvqs
acdqll--draep------ldalvlnagqqra----gaeapvfspqgleitfavnqlahq
liatrllpllr-lgs-------------qprlvitasdvh-npasgggrvgqpadlgdla
glk-----ag------agfamldgsasfdgdk-------aykdsklcnv-llgrelnr-q
ld----------------ammpviawspglviprssggffr--hnrq-----snplgmll
falvardvlr---vtesvqtagrlladlitdsgyaa-sgfsywsn---------------
--------------------------------rlvrpgv---------hrfseaetsae-
gadlq---kavdlfrlsddli---
>97_Prochlorococcus_marinus_subsp._marinus_str._CCMP1375_354
------------------------------------------------------------
-------------------------------------ifitgatsgigyqcslrlika-g
h-qliipcrdidrrefvlrsfardqinisev----------eelvslpildlgdlnniek
fanefv--snnsr------idtiilnaglqyt----gdkqirrssqgieltfavnhlshq
yliqalldill-ksd-------------fprvvitssevh-npdspggkigesaslgnle
gik-----as------ryfkmidgsytfsadk-------tykdsklcni-lfakelnr-r
lt----------lrn---lsmpvicwapglviprtqegffr--ysrk-----nnelgqrl
falfardifr---itesperageilknlaisdrylt-ngfnyysn---------------
--------------------------------kiqgfsr---------mkfentnvsee-
aneei---kakelwelsnkii---
>98_Oryza_sativa_Japonica_Group_360
------------------------------------------------------------
--------------------------------------vitgassgigletarvmalr-g
v-rvvmavrnvaaghraseairaeip---------------gagihvlemdlssmdsvrr
fatefe--alnlp------lnilinnagimt-----rnct--rsidglelqfatnhighf
lltnlllenmk-rtssktgv--------egrivnvsssahfvtyp---------kgicfd
kvk------------------eps--rfisli-------aygqsklani-lhstelsr-v
lknnretveyeqedg---vnisanavhpgvvt----tnlfr--h-rt------------i
inalvksigrf--vhktveqgaattcyvalhsqftg-isgkyfsn---------------
--------------------------------cn------------------ldtpssq-
asnae---lanklwefsskiv---
>99_Mycobacterium_tuberculosis_C_362
------------------------------------------------------------
--------------------------------mntgtavitgassglglqcarallrrda
swhvvlavrdpargrgghggigga-----------------kpvfgsrggtsrrcgpwrs
fveivr--ttplpp-----iralvcnaglqv------vsgiaftddgvemtfgvnhlghf
alvtgildwla-r---------------parivvvssgthdpskhtgmpdprytcaadla
hpp------------------tdqntpaegrr-------ryttsklcnv-lftyeldr-r
ld-------------hgeqgvmvnafdpglmp---gsglar--dyppilr---------l
ayrllspmlrvlpfvhstrvsgehlaalavdprfag-vtgqyfag---------------
--------------------------------ak------------------airssae-
sydra---kaldlwetserlla--
>100_Oryza_sativa_Indica_Group_366
------------------------------------------------------------
--------------------------------------vitgassgigletarvmalr-g
v-rvvmavrnvaaghraseairaeip---------------gagihvlemdlssmdsvrr
fatefe--alnlp------lnilinnagimt-----rnct--rsidglelqfatnhighf
lltnlllenmk-rtssetgv--------egrivnvsssahfvtyp---------kgicfd
kvk------------------eps--rfisli-------aygqsklani-lhstelsr-v
lknnretveyeqedg---vnisanavhpgvvt----tnlfr--h-rt------------i
inalvksigrf--vhktveqgaattcyvalhsqftg-isgkyfsn---------------
--------------------------------cn------------------ldtpssq-
asnae---lanklwefsskiv---
>101_Prochlorococcus_marinus_str._MIT_9303_382
------------------------------------------------------------
-------------------------------tvhsrrilltgassgigyqaavrmhra-g
h-qlvlpcrdrstatatlkklseetvqhqqe----------rspvsapvmdladlesikh
cadell--sigkp------idtlilnaglqyt----gaakaqlssqgyeltiavnhlghq
alsirllplld-agm-------------sprvvvtasevh-dsnspggrfgkpaglgdlt
glk-----tg------agfemidgsssfnadk-------aykdsklcnv-lfarelar-r
ls-------------lrsiqmpvlawapglviprssggffr--ysrr-----ynewgqrv
fslvvrdvlr---isesaenagallsrlateqslnt-spfsyrsn---------------
--------------------------------rldgpgq---------hrfeeaniske-
aqdnn---lakslwevsaeligl-
>102_Prochlorococcus_marinus_str._NATL1A_398
------------------------------------------------------------
------------------------------------tvmitggssgigfqavlklisl-g
h-niilpcknisranevltnlfnhsldessn----------kgeiytpimdlsdlssids
lcsevk--nrrwt------idvlilnaglqyt----gsktprrstqgieltfavnhlshf
yltqkilpfid-irn-------------dpkiiitssevh-npnsgggkvgakaslgklk
gle-----sg------agfemidgn-kfnadk-------aykdsklcni-lfarklsd-n
fm----------kkk---lsipviawapglvisrdnqgffr--ysrk-----ynqlgqil
faflardilk---ittsnkkaglllsnlaclskykk-pgfnyysn---------------
--------------------------------kiisssk---------fifeetetsnd-
aqrgd---lsdnlwelsksli---
>103_Oryza_sativa_Japonica_Group_404
------------------------------------------------------------
------------------------------------taivtgassgigaetarvlair-g
a-hvvmavrnlaaaqpvrdailadap---------------aasldlmeldlasmdsvra
fasdfa--akglp------lnilinnagvma-----tpfs--lskdgielqfatnhvghf
llthllletmk-ktsresnv--------egrivnvsseghrfayr---------egirfa
kin------------------des--eynsig-------aygqsklani-lhanelar-r
fk----------deg---vnitanslhpgsii----tnllr--h-hs------------i
ldvlhrtlgkl--vlknaqqgaattcyvalhpqvkg-vsgkyfsd---------------
--------------------------------sn------------------vneasek-
gndme---lakrlweysieli---
>104_Synechococcus_sp._BL107_420
------------------------------------------------------------
---------------------------------------mtgansgigevaarhlqes-g
h-vltvvcrsreraeqslewi--------------------qdpsqiliadlanlnavkn
mahqlg--ldgqq------fdvlvlnaglqya----gvdtprwsqqgfeltwavnhlahq
cllqlvlpllq-dsp-------------sprvvitasevh-npttgggrvgqpaglgtla
gld-----qg------kgasmvdgtspfsadk-------aykdsklcnl-lmglelsh-r
qp-----------------qlpvlcwspglviprskdgffr--eswk-----anpwgqav
fgfiardlfr---lteqperagslllslikgdhd-a-tgmrymsn---------------
--------------------------------havapgk---------hifestepspe-
amnid---lartlwqlsedli---
>105_Arabidopsis_thaliana_424
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------krlaqvvsdpsl-t-ksgvywsw-----------nnas
a-------------------------------sf------------------enqlsee-
asdve---karkvweiseklvgla
>106_Synechococcus_sp._WH_5701_434
------------------------------------------------------------
--------------------------------------litgassgigqqaalllhra-g
h-qltlpcrdqasadatrqkllasg----------------gsdlltpicdladlesidh
cakell--stgep------idslvlnaglqds----gaseprrsaqgheltiavnhlghq
alamqllplle-rse-------------aprlvvtasevh-dpgspggrvgepaglgnla
glr-----ag------agfamvdgrtpfnadk-------aykdsklcnl-lfareler-r
lr----------rrg---tampvlawspglvvprssggffr--ysrr-----hnewgqrl
falvardllr---ltatpeqagalladlataasygs-sgfsyyvn---------------
--------------------------------rlvspgr---------lhfesaepsae-
aqdda---laealwsvsaqlvgl-
>107_Elaeis_guineensis_456
------------------------------------------------------------
-------------------------------------aivtgassgigsetarvlslr-g
v-hvvmavrnlstgasvkeaivkeip---------------takvdvmqldltsmasvrk
fasdfd--nlnlp------lnilinnagvms-----tpft--lsqdgielqfatnhvghf
llthlllenmk-ntsreski--------egrivnvsseghrfpyr---------egirfd
kin------------------dqs--gygswt-------aygqsklani-lhanelsr-r
fk----------eeg---veitanslhpgsii----tnllr--y-hs------------f
mdvlsrtigkl--vlknvqqgaattcyvalhpqvkg-vsgkyfds---------------
--------------------------------sn------------------igepsak-
akdtd---lakklwdftmdli---
>108_Caenorhabditis_elegans_460
------------------------------------------------------------
---------------------------------------itgttsgvgtetarafilk-g
a-hivminrnyaasetlkqsllcetp---------------daridivqcdlsslasvkk
taeeyl--tkkwp------lhglilnagv-------lgrkekttadrfeahfginhlahf
llikellpvlr-ssa-------------psrivilsstls-----------------kft
sin-------------pdskieeklgtlcpknatewyyrlyakskmcnm-liafklhrde
fe----------------ngisvysvhpgsav---rtnlhr----------------dvp
fwsifnflsip--ftknasqgaatslycavhpevqe-lsgrywes---------------
--------------------------------cw----------------ddelnldekv
ardee---lqealweyseelvg--
>109_Vitis_vinifera_472
------------------------------------------------------------
-------------------------------------aivtgassgigtetarvlalr-g
v-hvvmavrnmaagrevkeaiakeip---------------takidameldlssmasvrk
fasefs--ssglp------lnllinnaglma-----tpfm--lskdnielqfatnhighf
lltnllletmk-ktaresnk--------egrivnvssrrhrfsyh---------egirfd
min------------------dqs--gynrls-------aygqsklanv-lhanelsr-r
lk----------ddg---anitanslhpgaia----tnlfr--h-vp------------l
vggfidifgky--vvknvqqgaattcyvalhpevkg-ttgeyfad---------------
--------------------------------sn------------------iakgssq-
andpe---lakklwdfslsli---
>110_Zea_mays_484
------------------------------------------------------------
-------------------------------------avitgassgigletarvlalr-g
v-hvvmavrnvsaglkareaivakip---------------varidvleldlssiasvrr
fasnfd--slnlp------lsifinnagvmt-----rsct--rscdglelhfatnhighf
lltnlllenmk-ktcrdsgi--------egrivnltssahsityr---------egicfd
kih------------------dps--slndfv-------aygqsklani-lhsnelsr-i
lk----------edg---vnisanavhpgvim----tnlfr--n-rt------------i
vsallnsigri--icrtveqgaattcyvamhpqvrg-isgkyftn---------------
--------------------------------cd------------------vanpssq-
asdae---lakklwqfslqiv---
>111_Populus_trichocarpa_488
------------------------------------------------------------
--------------------------------------litggasgiglettrvlalh-k
a-hviiaarnmvaaneakqlilkede---------------darvdvlkldlssiksire
fadnln--sldlp------lnilinnagimf-----cpyq--lsedgiemqfatnhlghf
lltnllldkmk-etarttgv--------egrivnlssvahihtyk---------dgirfn
nin------------------dkk--rysdkr-------aygqsklani-lhakelsr-r
fq----------eeg---vnitanavhpglim----tnlfk--h-sa------------i
lmrtlkffsff--lwknvpqgaattcyvalhpslkg-vtgkyyvd---------------
--------------------------------cn------------------slgpsaf-
ardea---larklwdfsnkli---
>112_Oryza_sativa_Japonica_Group_492
------------------------------------------------------------
--------------------------------------iqsggasgigletsrvfamr-g
a-hviiaarnteaasvvrkkiieenp---------------kahidvlkldlsslksvra
fadqfn--smnlp------lnilinnagvmf-----cpfg--lsedgvemqfatnhlghf
lltnllldnmk-atakstgi--------egrivnlssvahlhtyp---------kgiefd
kln------------------dek--tyddkm-------aygqsklani-lhakelsr-r
lk----------eeg---anitincvhpglim----tnlmr--h-sf------------f
lmrvlqfatyi--lwksvpqgaattcyvglnpqlkg-vtgqyfad---------------
--------------------------------cn------------------vektsrf-
arnda---lakqlwefsekli---
>113_Zea_mays_496
------------------------------------------------------------
-------------------------------------avitgatsgigletarvlalr-g
v-rvvmavrnvsaglmakdaivaktp---------------daridvleldlssiasvrr
fasefd--slklp------lnilinnagvmt-----rnct--rscdglelhfatnhighf
lltnlvlenmk-stcrdtgt--------egrivnvtsaghvmtyp---------egirfe
tir------------------dps--glndfi-------aygqsklani-lhtnelsr-i
fk----------eeg---vnisansvhpglia----tnlfrafg-rt------------i
iaaffntvgri--vrrsveqgaattcyvavhpqvkg-lsgkyfan---------------
--------------------------------cn------------------iaspssq-
asdae---lakklwefslqtv---
>114_Arabidopsis_thaliana_500
------------------------------------------------------------
-------------------------------------aivtgassgigvetarvlslr-g
v-hvvmavrntdsgakvkedivkqvp---------------gakldvmeldlssmqsvrk
faseyk--stglp------lnllinnagima-----cpfm--lskdnielqfatnhlghf
lltkllldtmk-stsreskr--------egrivnlsseahrfsyp---------egvrfd
kin------------------dks--syssmr-------aygqsklcnv-lhaneltk-q
lk----------edg---vnitanslhpgaim----tnlgr--yfnp------------y
lavavgavaky--ilksvpqgaattcyvalnpqvag-vsgeyfqd---------------
--------------------------------sn------------------iakplpl-
vkdte---lakkvwdfstkl----
>115_Ricinus_communis_510
------------------------------------------------------------
--------------------------------------iitggasgigletarvlalr-k
a-hviiasrnldaaneakklilkdhe---------------narvdvlkldlasiksvre
fadnfi--aldlp------lnllinnagimf-----cpyq--lsedgieiqfatnhighf
lltnlllekmk-etarttgi--------egrivnlssiahihtyk---------ggilfd
dln------------------nkr--sysdkr-------aygqsklani-lhakelnr-r
fq----------eeg---vnitanavhpglim----tplmr--h-sa------------l
imrilhifslp--lwknvpqgaattcyaalhpslkg-asgkyfvd---------------
--------------------------------cn------------------eikpsaf-
arddl---larklwdysnkli---
>116_Ricinus_communis_522
------------------------------------------------------------
-------------------------------------aivtgassgigtettrvlasc-g
v-hvvmavrnlvsgrnvketiikeip---------------takvdameldlssmasvrk
fasdfn--ssglp------lnilinnagvma-----tpfm--lskdnielqfatnhlghf
lltnllldtmk-ktahqsnr--------egrivnvsseahrysyh---------egirfd
kin------------------drs--gyssfr-------aygqsklanv-lhaneltr-r
lk----------edg---vnitanslhpgaiv----tnlfr--h-mn------------i
ingmvnvlgkl--vlknvqqgaattcyvamhpqvkg-isgeyfsd---------------
--------------------------------sn------------------lakasah-
grdve---lgkklwdfsmklv---
>117_marine_gamma_proteobacterium_HTCC2148_528
------------------------------------------------------------
------------------------------------nalvtgantglgkettrvlalc-g
a-nvtmacrdqvkaeqaredillgasgaid-----------esqlslleldlnsldktqq
aaeeyc--qrgee------lhllinnagimi-----pmer--rtvdgfeahlginhlahf
lftnllleplt-aae-------------garvialsslam-sfas---------lkhglk
din------------------wen-rkfsgwp-------aygnsklmnh-lfarelsk-r
ye------------g---ngivahavhpgvvs----telar--dqng-------------
lfsmigvlatp--lmknveqgaatqvlaaispeygd-sgglyfkd---------------
--------------------------------cr------------------vakpqhkl
andga---laeelwqrsvelvgl-
